### ISSUE TITLE
[BUG] : 403 error

### ISSUE THREAD

**Issue by emo-waffles** [Shabinder/SpotiFlyer#1005]
Same bug after update.... download fails

Tried downloading *Lauv* song 

https://open.spotify.com/track/0du67LyuJeUjQChxl8rTa8?si=fdfbmsXuSFKxwyKtvCScNw&utm_source=copy-link

Phone : samsung galaxy s21 ultra. 

java.lang.Exception: Client request(https://r3---sn-u2bpouxgoxu-coxl.googlevideo.com/videoplayback?expire=1643321874&ei=ssXyYYvMJKvI8gPN7pOoCg&ip=59.148.12.201&id=o-AFj2UJrR6ostXK-eRRpmCzPAzdD35d3eGqNnzRNqM8qD&itag=140&source=youtube&requiressl=yes&gcr=hk&vprv=1&mime=audio%2Fmp4&ns=WNPguDOpsZ1suH2QiL1-VfoG&gir=yes&clen=2573422&dur=158.826&lmt=1642728082094051&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311224&n=hDTlIjqODcCz3Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPcNebMVvd5q4jt-GJmO0C582k14loGGUDDpVIUieDacAiACwGyDKLZhEj0PYLdnAjvGKr1qfJHrJRniObbiUnrmvg%3D%3D&title=26&cms_redirect=yes&mh=A6&mip=203.219.148.146&mm=31&mn=sn-u2bpouxgoxu-coxl&ms=au&mt=1643301208&mv=m&mvi=3&pl=23&lsparams=mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgUScsPZLJ9xJ1CFNymAnLTnQuAY3PhFfOOveCxXVJkZgCIQDN5NdnEpUGXiJGlTB06wZFIlmuGA5eMMfxwDv3ezqP9Q%3D%3D) invalid: 403 Forbidden. Text: ""
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Working fine: 
![image](https://user-images.githubusercontent.com/44765050/151404775-c26e5c87-c44b-4050-ad51-7ad683ab3cba.png)

Retry downloading the same song, Maybe some network issue was there.

**Comment by emo-waffles** [comment]
![Screenshot_20220128-024827](https://user-images.githubusercontent.com/85346722/151405056-06297307-29eb-44ed-bde3-321dbf6af557.jpg)

**Comment by emo-waffles** [comment]
> 
Yes even after retrying i restarted my phone also, fresh install as well, and even turned off wifi see if that was problem all the same.   got PC version as well and its doing the same for me.

**Comment by Itroublve** [comment]
Using a VPN did the trick for me, and after the newest update (?). It works fine again (for me)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
