### ISSUE TITLE
[BUG] : CAN'T DOWNLOAD IN 3.6.1 

### ISSUE THREAD

**Issue by Kaiser17331** [Shabinder/SpotiFlyer#1011]
READ THIS!
This Shit

java.lang.Exception: Unable to resolve host "dl212.y2mate.com": No address associated with hostname
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Describe the bug:**
Can't download 

**Media Links Used:** 

https://open.spotify.com/track/27CoqKZ8jrIG8g5cD7WQfv?si=squmkioKTbS-GP7NM2ka6A&utm_source=copy-link

**Screenshots:**
![Screenshot_2022-01-28-13-42-52-654_com shabinder spotiflyer](https://user-images.githubusercontent.com/98190476/151603814-e4bd5d00-c608-4400-bcd5-9d2c0f606c19.jpg)
![Screenshot_2022-01-28-13-39-40-259_com miui securitycenter](https://user-images.githubusercontent.com/98190476/151603820-b475c248-464f-4c4f-ba3b-e274718a9e89.jpg)
![Screenshot_2022-01-28-13-39-27-950_com shabinder spotiflyer](https://user-images.githubusercontent.com/98190476/151603824-b8f67f73-a042-46db-b1b4-d3955f537109.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [Xioami Redmi 9 ]
 - OS:   [ Android 11]
 - Version:   [3.6.1]
 - Country: [Peru]

**Additional context:**
I hate this

**Comment by Kaiser17331** [comment]
Can't download in 3.6.1 anything

![Uploading Screenshot_2022-01-28-13-39-27-950_com.shabinder.spotiflyer.jpg…]()

**Comment by Kaiser17331** [comment]
![Screenshot_2022-01-28-13-42-52-654_com shabinder spotiflyer](https://user-images.githubusercontent.com/98190476/151604169-85affbae-6a35-46eb-870c-596a0f2fb35e.jpg)

**Comment by Shabinder** [comment]
Can you once try on a vpn if it works ?

**Comment by Kaiser17331** [comment]
> Can you once try on a vpn if it works ?

yes, but it doesn't download, it restarts

**Comment by Shabinder** [comment]
what restarts ? is the stacktrace the same even on a VPN ?

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
