### ISSUE TITLE
no ffmpeg?

### ISSUE THREAD

**Issue by girlnobodyknows** [Shabinder/SpotiFlyer#1016]
only one song was downloaded from my spotify playlist omg
said to copy paste this issue:

```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)

```
good luckk & thank you very much i very much vibe with this app you are awesome

**Comment by Shabinder** [comment]
have you installed FFmpeg in your system ?

**Comment by Shabinder** [comment]
Seems like above suggestion worked for you.
So closing this issue now.

**Comment by girlnobodyknows** [comment]
> Seems like above suggestion worked for you.
> 
> So closing this issue now.

haha yess it worked, thank u so much u're so cool
