### ISSUE TITLE
Song not downloading, says FFmpeg not on path. 

### ISSUE THREAD

**Issue by thewudm** [Shabinder/SpotiFlyer#1035]
**Describe the bug:**
FFmpeg is on path, but the app says its not and it fails to download the song. 
<img width="271" alt="Screenshot 2022-02-01 at 11 10 12 AM" src="https://user-images.githubusercontent.com/70529254/151918352-b4bef5c3-ad31-420d-b3dc-7f36a8fcd0c5.png">

<img width="835" alt="Screenshot 2022-02-01 at 11 25 25 AM" src="https://user-images.githubusercontent.com/70529254/151919675-abe10ebf-7fcc-40f6-833a-84ed6342a08e.png">

**Media Links Used:** 
 [Spotify link to the song "Lemonade - Internet Money" ](https://open.spotify.com/track/02kDW379Yfd5PzW5A6vuGt?si=01677e5b1bf24386)

**Expected behavior**
The song being downloaded 

**StackTrace:**
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 16 more

```

**Device Info (please complete the following information):**
 - Device:   MacBook Air M1 2020
 - OS:   MacOS
 - Version:   BigSur 11.6
 - Country: India

**Comment by Shabinder** [comment]
did you tried restarting after adding ffmpeg to the path

**Comment by thewudm** [comment]
Yes. It still says "FFmpeg not found at path".

**Comment by KnightKing2179** [comment]
how to add ffmpeg to path

**Comment by thewudm** [comment]
> > how to add ffmpeg to path
> 
> [Click here for instructions](https://www.thewindowsclub.com/how-to-install-ffmpeg-on-windows-10)

We're on mac my guy.

**Comment by enricobachiorrini** [comment]
This solved the problem for me: https://github.com/Shabinder/SpotiFlyer/issues/891#issuecomment-1164216867

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
