### ISSUE TITLE
[BUG] : No FFMPEG found at path

### ISSUE THREAD

**Issue by ChillaxJDM** [Shabinder/SpotiFlyer#1065]
**Describe the bug:**
Tried reinstalling app on my windows couple times, even running as adming, still getting the error No Ffmpeg found at path

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
``` com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more


**Device Info (please complete the following information):**
 - Device:   PC
 - OS:   Windows 11 Pro
 - Version:   Latest
 - Country: Germany

**Additional context:**
<!--- Add any other context about the problem here. --->

**Comment by ChillaxJDM** [comment]
![Screenshot 2022-02-05 160115](https://user-images.githubusercontent.com/99084889/152647291-ce3ff4c4-12d7-4444-99ac-0ae5b81aa979.JPG)

**Comment by Shabinder** [comment]
Try installing FFMpeg by following any guide online and add that to path

**Comment by FireMS** [comment]
Not sure if this is still an issue, but the files are still there and playable. If you set the directory to the Spotiflyer folder using MP3Tag, you can still see all the music that was individually downloaded, from there you can move it to any other folder by right-clicking and selecting move, from there you can easily listen to the music all the way through, no corruption or anything.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
