### ISSUE TITLE
I am seeing this issue on opening Spotiflyer. “Warning! FFmpeg not found at path” 

### ISSUE THREAD

**Issue by Basic6969** [Shabinder/SpotiFlyer#1111]
at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more

**Comment by squashroom** [comment]
getting the same error message, wont download specific songs but others work fine

**Comment by Basic6969** [comment]
> getting the same error message, wont download specific songs but others work fine

mine solved, just download the latest ffmpeg from here https://ffmpeg.org/download.html and paste all .exe files in system 32 
c;/windows/system32

**Comment by squashroom** [comment]
thanks, worked for me.
you should close the issue since theres now a solution for anyone looking

**Comment by daerias** [comment]
MacOS 12.6 ffmpeg installed but same error appears

**Comment by wwwonka** [comment]
> MacOS 12.6 ffmpeg installed but same error appears

Same here on Ventura. Spotiflyer 3.6.1

**Comment by prithvibidkar** [comment]
> > getting the same error message, wont download specific songs but others work fine
> 
> mine solved, just download the latest ffmpeg from here https://ffmpeg.org/download.html and paste all .exe files in system 32 
> c;/windows/system32
A noob question, should I download source code or PCP key?

**Comment by Basic6969** [comment]
> > > getting the same error message, wont download specific songs but others work fine
> > 
> > 
> > mine solved, just download the latest ffmpeg from here https://ffmpeg.org/download.html and paste all .exe files in system 32
> > c;/windows/system32
> > A noob question, should I download source code or PCP key?

source code

**Comment by Ubuntu-droid** [comment]
> ```
> at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
> at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
> at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
> at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```
> 
> Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified at java.base/java.lang.ProcessBuilder.start(Unknown Source) at java.base/java.lang.ProcessBuilder.start(Unknown Source) at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141) ... 14 more Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified at java.base/java.lang.ProcessImpl.create(Native Method) at java.base/java.lang.ProcessImpl.(Unknown Source) at java.base/java.lang.ProcessImpl.start(Unknown Source) ... 17 more

yeah, I have the same issue. i downloaded the ffmpeg from its website pasted all exe files in system 32 folder. and I also downloaded it through winget ffmpeg using powershell app pre-installed on windows. the app sill shows the same error. can someone help me fix this?
![SpotiFlyer 10_26_2023 8_13_24 PM](https://github.com/Shabinder/SpotiFlyer/assets/78688295/99f9b7d2-07b4-4bb4-8e86-c7b2530d2790)

**Comment by Ubuntu-droid** [comment]
yeah, I have the same issue. i downloaded the ffmpeg from its website pasted all exe files in system 32 folder. and I also downloaded it through winget ffmpeg using powershell app pre-installed on windows. the app sill shows the same error

**Comment by Lesproges** [comment]
> yeah, I have the same issue. i downloaded the ffmpeg from its website pasted all exe files in system 32 folder. and I also downloaded it through winget ffmpeg using powershell app pre-installed on windows. the app sill shows the same error

same here
