### ISSUE TITLE
[BUG] : Can't download song

### ISSUE THREAD

**Issue by Pastelblue1** [Shabinder/SpotiFlyer#1200]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

Hi, so I wasn't able to download this song I have the report here. The song is Ex Factor by Lauren Hill:

java.lang.Exception: stream was reset: INTERNAL_ERROR
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
