### ISSUE TITLE
Crash: Broadcast Issue (Samsung Galaxy A21 Users)

### ISSUE THREAD

**Issue by Shabinder** [Shabinder/SpotiFlyer#129]
I have received **crashes from 6 users** all using **_Galaxy A21,_** Issue is as follows:

**Stacktrace:**
```
android.app.RemoteServiceException: can't deliver broadcast
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2182)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Shabinder** [comment]
Removed Broadcast from the app, and instead bind to Foreground Service
