### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by mainakmukherje** [Shabinder/SpotiFlyer#1351]
java.util.concurrent.CancellationException: Executor was closed.
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor.close(ParallelExecutor.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$killService$1.invokeSuspend(ForegroundService.kt:7)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:23)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:3)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:1)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:12)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:5)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:3)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.shabinder.spotiflyer.service.ForegroundService.killService(ForegroundService.kt:1)
	at com.shabinder.spotiflyer.service.ForegroundService.onStartCommand(ForegroundService.kt:6)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
	at android.app.ActivityThread.access$2100(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
