### ISSUE TITLE
[BUG] : Failing to download specific song

### ISSUE THREAD

**Issue by DriedPaint** [Shabinder/SpotiFlyer#1468]
**Describe the bug:**
Copied link of song ‘F**k you - Ceelo Green', download failed after following usual procedure. Issue seems to repeat with this song

**Media Links Used:** 
 https://open.spotify.com/track/4uecNcubrVaYShl8bdQhEL?si=KQVdWy9OTHaJN9qhrqrl2g&utm_source=copy-link

**Expected behavior**
 song to download normally. When I downloaded playlist of songs, some show fail, I hit download individually and it worked. I even searched link of this song individually. It should have worked after that.

**StackTrace:**
```
java.lang.Exception: Client request(https://snoidcdnems07.cdnsrv.jio.com/aac.saavncdn.com/047/1ee2d20d16e4a15e81b7f9c4beb8666f_160.mp4) invalid: 404 The specified blob does not exist.. Text: "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:26637259-f01e-000b-1096-85c617000000
Time:2022-06-21T17:43:39.4028169Z</Message></Error>"
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

```

**Device Info :**
 - Device:   Redmi Note 7 Pro
 - OS:   Android 10
 - Version:   3.6.1
 - Country: India

**Comment by heartlog** [comment]
There's no problem in downloading it at all.
If you are trolling then, don't joke around here.
If there's really a problem then clear the catch, that will fix your problem.

**Comment by DriedPaint** [comment]
> If there's really a problem then clear the catch, that will fix your problem.

Cleared the app cache from settings, tried downloading the song again using spotify link, didn't work. Even the error log files look similar.

https://open.spotify.com/track/4uecNcubrVaYShl8bdQhEL?si=UjCIPHx6S_Kn4jW8O8c-Ug&utm_source=copy-link

The link I used...

**Comment by heartlog** [comment]
Maybe it's blocked in your country ?

**Comment by heartlog** [comment]
> > If there's really a problem then clear the catch, that will fix your problem.
> 
> Cleared the app cache from settings, tried downloading the song again using spotify link, didn't work. Even the error log files look similar.
> 
> https://open.spotify.com/track/4uecNcubrVaYShl8bdQhEL?si=UjCIPHx6S_Kn4jW8O8c-Ug&utm_source=copy-link
> 
> The link I used...

![Screenshot_20220811-100111](https://user-images.githubusercontent.com/76758776/184065120-1ec3f513-5214-419d-8ded-a004de8fd3d4.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
