### ISSUE TITLE
[BUG] : No FFMPEG found at Path, tried multiple solutions  

### ISSUE THREAD

**Issue by badthanos** [Shabinder/SpotiFlyer#1607]
**Describe the bug:**
No FFMPEG found at Path, installed through Homebrew, Added Paths to .bash_profile, ffmpeg is located at /usr/local/bin etc., multiple restarts and so forth

**Media Links Used:** 
https://open.spotify.com/playlist/3Xk51iuDLAvQ0fkzzPJ6Il?si=8590f629890c4832
https://open.spotify.com/playlist/3NgkCmLvO7UrtMsVBEeFVU?si=ef99ec25a916432b

**Expected behavior**
Download Playlist, Error message should have dissapeared

**Screenshots:**

**StackTrace:**
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:315)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:245)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 16 more

```

**Device Info (please complete the following information):**
 - Device:  MacBook Air (13-inch, Early 2014)
 - OS:   Mac OS 
 - Version:   10.14 Mojave
 - Country: Germany

**Additional context:**

**Comment by debmaj2** [comment]
Facing the same issue

**Comment by Kaothi23** [comment]
Try installing FFMpeg by following any guide online and add that to path

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
