### ISSUE TITLE
This and "Not FFmpeg found in path" 

### ISSUE THREAD

**Issue by MrDanonix** [Shabinder/SpotiFlyer#1641]
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)

**Comment by JaviAibar** [comment]
I answerd to "Not FFmpeg found in path" here: https://github.com/Shabinder/SpotiFlyer/issues/1729#issuecomment-1256069480

**Comment by mihin19** [comment]
For the 'No FFmpeg found in path' message in windows 10 close Spotiflyer, download the ffmpeg.exe and place it into the folder C:\Program Files\SpotiFlyer  Run Spotiflyer and it should work without the warning,
