### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by thaynos** [Shabinder/SpotiFlyer#172]
it just opens a small black window when i open the app from the start menu
and then it crashed
if i do it with admin privs it shows the small window with the logo and crashed
i downloaded using the exe and i repaired the file

**Comment by Shabinder** [comment]
try running .jar file 
 and send the crash report here which will appear in the **console**.
 
 `java -jar <filePath>.jar`

**Comment by thaynos** [comment]
```
C:\Users\GUEST123\Downloads>java -jar <SpotiFlyer-windows-x64-3.1.0>.jar
The system cannot find the file specified.

C:\Users\GUEST123\Downloads>java -jar SpotiFlyer-windows-x64-3.1.0
Error: Unable to access jarfile SpotiFlyer-windows-x64-3.1.0

C:\Users\GUEST123\Downloads>java -jar "C:\Users\GUEST123\Downloads\SpotiFlyer-windows-x64-3.1.0.jar"
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedClassVersionError: org/jetbrains/skiko/GraphicsApi has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethod(Unknown Source)
        at java.awt.Component.isCoalesceEventsOverriden(Unknown Source)
        at java.awt.Component.access$500(Unknown Source)
        at java.awt.Component$3.run(Unknown Source)
        at java.awt.Component$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Component.checkCoalescing(Unknown Source)
        at java.awt.Component.<init>(Unknown Source)
        at java.awt.Container.<init>(Unknown Source)
        at java.awt.Window.<init>(Unknown Source)
        at java.awt.Frame.<init>(Unknown Source)
        at java.awt.Frame.<init>(Unknown Source)
        at javax.swing.JFrame.<init>(Unknown Source)
        at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.desktop.kt:31)
        at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt:114)
        at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt)
        at androidx.compose.desktop.AppWindow_desktopKt$Window$1.run(AppWindow.desktop.kt:83)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Shabinder** [comment]
You need to install a recent jre like 15.0, 16.0 , etc

**Comment by thaynos** [comment]
i jsut installed the official one from the website day before yesterday

**Comment by thaynos** [comment]
JavaSetup8u291 was what i installed

**Comment by thaynos** [comment]
```
C:\Users\GUEST123\Downloads>java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by thaynos** [comment]
i re-installed it using JavaSetup8u291,exe

**Comment by Shabinder** [comment]
so now app works?

**Comment by thaynos** [comment]
no

**Comment by thaynos** [comment]
if i only click on the app and open directly with java it doesnt work at all. it opens a cmd window and closes. 

> ```
> C:\Users\GUEST123\Downloads>java -jar <SpotiFlyer-windows-x64-3.1.0>.jar
> The system cannot find the file specified.
> 
> C:\Users\GUEST123\Downloads>java -jar SpotiFlyer-windows-x64-3.1.0
> Error: Unable to access jarfile SpotiFlyer-windows-x64-3.1.0
> 
> C:\Users\GUEST123\Downloads>java -jar "C:\Users\GUEST123\Downloads\SpotiFlyer-windows-x64-3.1.0.jar"
> Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedClassVersionError: org/jetbrains/skiko/GraphicsApi has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.access$100(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.Class.getDeclaredMethods0(Native Method)
>         at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
>         at java.lang.Class.getDeclaredMethod(Unknown Source)
>         at java.awt.Component.isCoalesceEventsOverriden(Unknown Source)
>         at java.awt.Component.access$500(Unknown Source)
>         at java.awt.Component$3.run(Unknown Source)
>         at java.awt.Component$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.awt.Component.checkCoalescing(Unknown Source)
>         at java.awt.Component.<init>(Unknown Source)
>         at java.awt.Container.<init>(Unknown Source)
>         at java.awt.Window.<init>(Unknown Source)
>         at java.awt.Frame.<init>(Unknown Source)
>         at java.awt.Frame.<init>(Unknown Source)
>         at javax.swing.JFrame.<init>(Unknown Source)
>         at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.desktop.kt:31)
>         at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt:114)
>         at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt)
>         at androidx.compose.desktop.AppWindow_desktopKt$Window$1.run(AppWindow.desktop.kt:83)
>         at java.awt.event.InvocationEvent.dispatch(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)
> ```

this issue is when i try to open using cmd

**Comment by thaynos** [comment]
it opens sometimes and it loads all the songs in my palylist but when i click the downlaod button it opens some java window.

**Comment by Shabinder** [comment]
You need to add new java in path , 
Please watch some yt video or read a guide on how to do that

**Comment by thaynos** [comment]
i added java to path it still doesnt work. 
i added the java.exe to path. 
"C:\Program Files (x86)\Java\jre1.8.0_291\bin\java.exe"
```
Microsoft Windows [Version 10.0.19042.1052]
(c) Microsoft Corporation. All rights reserved.

C:\Users\GUEST123>java
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -client       to select the "client" VM
    -server       to select the "server" VM
                  The default VM is client.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.

C:\Users\GUEST123>
```

if i try using the java -jar format 
```
C:\Users\GUEST123\Downloads>java -jar SpotiFlyer-windows-x64-3.1.0.jar
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedClassVersionError: org/jetbrains/skiko/GraphicsApi has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethod(Unknown Source)
        at java.awt.Component.isCoalesceEventsOverriden(Unknown Source)
        at java.awt.Component.access$500(Unknown Source)
        at java.awt.Component$3.run(Unknown Source)
        at java.awt.Component$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Component.checkCoalescing(Unknown Source)
        at java.awt.Component.<init>(Unknown Source)
        at java.awt.Container.<init>(Unknown Source)
        at java.awt.Window.<init>(Unknown Source)
        at java.awt.Frame.<init>(Unknown Source)
        at java.awt.Frame.<init>(Unknown Source)
        at javax.swing.JFrame.<init>(Unknown Source)
        at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.desktop.kt:31)
        at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt:114)
        at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt)
        at androidx.compose.desktop.AppWindow_desktopKt$Window$1.run(AppWindow.desktop.kt:83)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

C:\Users\GUEST123\Downloads>
```

i used the latest stup from the java website

**Comment by Shabinder** [comment]
You are doing it wrong :

>i added the java.exe to path.
"C:\Program Files (x86)\Java\jre1.8.0_291\bin\java.exe"


Java 8 wont work , try adding java 15 ,

and path wil be `C:\Program Files (x86)\Java\jre****\bin\`
no .exe at end

after adding try `java -version` to confirm its available

**Comment by thaynos** [comment]
i cannot find java jre 16 only java sdk 16.

**Comment by thaynos** [comment]
```
C:\Users\GUEST123>java -jar C:\Users\GUEST123\Downloads\SpotiFlyer-windows-x64-3.1.0.jar
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
Debug: (Kermit) System Time:1623594604 , Token Expiry:1623479501
Debug: (Kermit) Requesting New Token
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=BQAFaEBH4iOa_prHl70f9oREj39nE3ANEAZ0oDWR_EQotd98I3CfXCjPzXNkTkf1E-MCfwo036cvBmg9t_I, token_type=Bearer, expiry=3600)
Failed Direct3D call. Error: 0x887a0001
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffff3604b89, pid=14320, tid=10768
#
# JRE version: Java(TM) SE Runtime Environment (16.0.1+9) (build 16.0.1+9-24)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (16.0.1+9-24, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x34b89]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\GUEST123\hs_err_pid14320.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
[hs_err_pid14320.log](https://github.com/Shabinder/SpotiFlyer/files/6644055/hs_err_pid14320.log)

**Comment by thaynos** [comment]
btw it crashed when it was stuck on the logo and i pressed full screen button

**Comment by thaynos** [comment]
when i open with with admin cmd and with spotify open it successfully loads

**Comment by thaynos** [comment]
![image](https://user-images.githubusercontent.com/83282129/121811657-1e361480-cc76-11eb-8df4-ad5209ce2c6f.png)
![image](https://user-images.githubusercontent.com/83282129/121811658-1f674180-cc76-11eb-8b56-9e1e2e24b3cd.png)
