### ISSUE TITLE
[BUG] : Getting error while downloading a youtube music link

### ISSUE THREAD

**Issue by Badass-Nemesis** [Shabinder/SpotiFlyer#1829]
**Describe the bug:**
Can't download this song from youtube music link

**Media Links Used:** 
https://youtu.be/MzmwWPPHyzs

**Expected behavior**
It downloaded without any error yesterday, but only this time it started giving me error and still isn't downloading.

**Screenshots:**

![image](https://user-images.githubusercontent.com/71874901/194757979-caa185c8-685d-4b94-8b33-40219e952c51.png)

**StackTrace:**
```
java.lang.Exception: Client request(https://rr1---sn-5hne6nzk.googlevideo.com/videoplayback?expire=1665331221&ei=tZtCY6_MLIrR1wLX2Y-gCQ&ip=31.210.22.181&id=o-ACfGWDIxo2lXHpI2JmzyuSFj7Ge07-OlpyvK_hXiFMZR&itag=140&source=youtube&requiressl=yes&mh=uL&mm=31%2C26&mn=sn-5hne6nzk%2Csn-4g5lznes&ms=au%2Conr&mv=m&mvi=1&pl=24&gcr=nl&initcwndbps=250000&vprv=1&mime=audio%2Fmp4&ns=7-6WRDbm2Ad_5F7s8MeKGkoI&gir=yes&clen=3098971&dur=191.364&lmt=1631543516794156&mt=1665309218&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=tEpj2kZiIxjUJg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIdRNJkG3P6qxdSOUR97Z3ocasqpyP3UQfjC_hKKU0WHAiAHGrgKttxx_HjZX_wDVJH2Yx5Ea5K7gdO-0qAddeEuNA%3D%3D&sig=AOq0QJ8wRAIgGElhrOSR74z1kYmzRPJY4LGyJQ6-QfJydtkJU0uKEJkCIEAXlHS1TbUfsCs-z9GQNWfaZmjufpQ7J-9fT2WmgWUd&title=%40+my+worst) invalid: 403 Forbidden. Text: ""
 at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
 at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
 at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
 at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
 at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
 at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
 at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
 at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
 at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
 at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
 at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
 at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
 at h.w.j.a.a.resumeWith(ContinuationImpl.kt:9)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
 at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Device Info (please complete the following information):**
 - Device:   Realme X7 Max
 - OS:   Android 12 (Realme UI version 3.0)
 - Version:   12
 - Country: India

**Additional context:**
Nothing. Just wanna tell you that I love the app.

**Comment by Shabinder** [comment]
Thanks for the report,
Can u try again, sometimes while processing the link expires and hence the error.

**Comment by Badass-Nemesis** [comment]
Thanks. It's working now.
