### ISSUE TITLE
[BUG] : <Download Fail>

device: Galaxy s10e
issue, no SAAVN match found, truly a loss of a song



### ISSUE THREAD

**Issue by vickensemerdjian** [Shabinder/SpotiFlyer#1967]
DownloadLinkFetchFailed(errorTrace=Find Link for The Art of Heartbreak 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for The Art of Heartbreak)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:299)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Yt1sMp3 Failed for TJNrr-tCcHg:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=763a7d47e952dba6')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=DHEi8JSfKPGRf_Kvy413tSPzAVANx7vsbf1_E4nsCZA-1667367143-0-gaNycGzNCCU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value=".OB5WKUlnwWm7L_HNz0MNlERC18bnTqvzaeF57nqbhA-1667367143-0-AYif0kInDdgJ_Ucct05ZAT9iybvJ7ib92RRJmx70AtY2rv8YDIVa1hGx8i96iDUmwdXxGHEpErY_J7RxtrS6D3JOEJg8UGhzITE8y3UXdSxwof5BBC4Yl7ImuZqPoZfJw5pVNyBM3lpLVlfdvVpH5GBfbylkAC5i1trgERw7xrp6D23t5aYpsRYi5v_sJrp1hZ-eAoJeaoIXVuJO_ASf1udrKuDrM3AkTeZTDcC_HcCLXrUTKTsW32d-MNiufokIUiGeZXxSdt5KeTogmpdA-ykKDPXesmkiyRFJ-Py9GuW4J-8JtPKSzNa3O7GOpppJ2obZ2XLigcSb7U4ZfmD1r-oAu7B-eoE5JcjFIbV_DrmeijlJb2XOTz_ewyj0dzBDF-9xQ_6BE-8C4TM5ljVF7HnkTxIQxWxQihluVbljyfyf_D47L4AIPnn94zNeHk_5bmZnob0ofKVA-p1tXupQfJFlgHhcUXlVu_yNezTLOKdf__f5j_N4HH5Tfs1YrrWBLdnSBLTepUYG4VUH61qmKoH2wFcYQ-eFtDYaYNu7gn4ATjV65VMM4AS3ISxjPVWZPEroBHbn_9BpbtVd-J85x3KC8s-I9PDhaDk0MYRPDJGfVW5Y3bAHMr-UFWeDqAir115W8rRq_gVpUsaUJcVST3EQylbCSPXtOJdg385MvGCA">
            <input type="hidden" name="r" value="gVR5FYaBmY37hKAkqf20cSOF0TSBgzjZdk32IDdQ_2U-1667367143-0-AcpFtbwBnQQFkluUTK3qqYkmDb2o+Y30IJ/UlCrt+SplzepQLZMZIZ3VW9v06VCcFeUJIyihPZKAZn9dCUlY88sqieAKRiMlTS34MQbZ/tMagvWAk/SNgjtzVT82+/G7bn4nfXOcNUuw7+E992wpz5Q8tgddM0YrSJ/UqABg9Gtw0J0a1d2xbavd2LHl+6a019YZderqLYebD0uqLJ6eUoxJWRwn13NbbGPvFu/jDOR1Q/03iWCyStDoa4nkWXYhyr+QZUKwbGnqEfVan8eIrabhxbtLKV5BOmqVbIZWarX0kqFoUMAViY15MqR5qFV9oOMLvUcbhx3BoMNJw5oKX3zc4IyIxzxVEu66FBbatjTnXZ1SkKB2heACKRxwtSa3IIP86PGG5jn94LtrAgHx6sWSCSToc70cRb2TiekP75ADOG93udaA3XHsKcFLH/17W60N4C6b+KD7hd84+VDbFDCTNOGI6rAcdfIrkmFLcOAFM5+tpUN6f0y+hgrNFcGTB2+Jl76+3QLWH5dyTm6jx+7s9sKoM9GuibfKRjaVMjvcMAeGTw87FTKtycxfTd32vT+nM6UYW/yuFC8Je9ySHuIhhZj/PKhyP5wfl3RbdtLgpZA0t3f+FLfd2j8fUdF62wFrOQasXUGAgzdnLztgJDE0S3cx/Oc+Nc5XCgzQoQSBa+3C3edym5nycYJKO+IsEmLBI2vM7y1JdhNp/DiBhN89REIg5GCWfhjczG2iMHqxcSkyTUaf93wd3i98bj2JZPvobo/nsCsI7BcrZEvpWGOJx5KEsNaLCS/d2E+uY+/6/dLPQSL2YMEJd+ZHWe8/AmPF/RrgldEYVaNf+zrshFQ0b1GZGWmtiU8edZ4T8lr2HoK8xFaaIqmArxjfaWEVNhZtcG2eajFk5mxWN4i1R8CB+UFmT1c4epHvAW8oLC29psOxFplyh0S4mEY/SEmr9c09bCXN2I5bJ9hnNiEWb7a2W9lx+6qy8BwZT1wywADQ/FnXgwv5I3RUfT3BqMKBa2hn/P/EOAq4dkIBm4G/s4H/DE7iUNsnOr503NGjkhDnakPays0sZBUxd5HW2kSnM8AV+VrGR9Hpl4Gr2LJ7joQ9k4tSUKIyhGUrcoBy4Wx/1vLvmvTbG/Q/NlXm1AFSaigwyKXXZD0/wp2dC1Z2e+KI+LLbEqpE1aJTG2oScal1ngmiE6WYr4CXB+vRFwJ53+sAhff0RV1e4oyq9C/yJsxbNo6qA5Z1qk3qUdYAzcqNxHuNhAaIx0RoWlJxYtefdg3li4KyGHfk6PLnseCufMO9+owoln0bbP7dc08Y+sAludBi25a6lVxs6p+fAQU5H3akuRiFg3XSuYwjXx18QJyUl0xg8uytBr6BzTOMmi8c3EI5ixGTHBXXSXH8+XmlWeVVnOMKWN4IU4FuRloRVqiktnxgcM/UU7GKlBPjCg4v9DSvynCoy7PqU0GBVVn4uTWuBKxiLsNKH8nBlx5tzWpPLz5p/HkDwwNPm/Yv75QFQkJU75j3YMWEWFPTEUAn2Jsp2bXNg4LVx6t+u+hTb65Vgm7NQTQ7SNmIoLI2Zqb/YXbo9Z21wsyzMsWU2RQDaQitVFECCYsJVaaDQXSoIztXOUGw3LEvT15RvM7gW9mI1ykPET7vMtk8IuaLCxOoBh8S5a56Exla8rXFDrome0RaI+pzWXoghFkx6/FL5tsnVvtG84HvjfrAw1ecD3eIOrPV4suaXptvvC3yCu7+6dNqYflnlYpWF0NbDcmhI0Zoc651wSG3FQ+rJS8NdT8kR5woVDWvsCVSZZDlKxGiyo241CpzkFGi0uF9SUuK3kLcxOwwpuWsdeogW24FqWXmo4CtMaNlgebX87vw9XuWKZT3O8y9VdhUm/IF4D+xhUT95SWH7W/zHHQooIXay//9esMqeH6JELVFsQedRHuIFWrMdzbM+Bjq2UQgWp7Pl2XSYn9ucgIAzTNHo3GZuPyfF+vAcdIWD4+ERORHcJYwY1x6+AmTOQbRS3B3r6hH4EW8">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'non-interactive',
            cNounce: '43127',
            cRay: '763a7d47e952dba6',
            cHash: 'b90c5f940ae9a77',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=DHEi8JSfKPGRf_Kvy413tSPzAVANx7vsbf1_E4nsCZA-1667367143-0-gaNycGzNCCU",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'mqv3tpwtpE3oFfbUU9l8fReIyBPMP0iDP3sWSndknPhDeGaIIEWldb9OusQMCkXlkPLYS2AhJEghUacsVYDBTwtbUn0b9vHvjRz5pKcxOnb1QnItGicZqbHPqwrtGVm76n8ureZLh/xN1lcVjVE/SbTh3Y672ded3jb+JPt7QzlKTSD/iKSRPbsvJpi3xh6XRg2ZQVD2pSvBMWASGsHrMXhqSEwu+ILUA4hDd8XA2QLDP5s7sWfayQLZuq8auZ1ERihYgxAmx1+7IRNv4NpN8sJ6s73atZjkP+j99YfvZd49pk5xKd78nXjunrdW7lpGwvphboqIep/H7JULlXOKfJH799M+3O/wQ2vItm4fQ7CwMdVdZHx/c9fBeP95PS9w+UnklmyO02lUaoui+3EqMnyxAqySveIpi0R7IxtOusyPXnbLYgNyW1YB1t/oCI2L1xgxTaNBLp645i6wq6HGJt5n04AKyf1My6lR3Aqu4y5H8Omhdf3/5+6j3FB/OZh0R+8zoac5hctJsBP7wqfWtI2LUW1XSum5e4O0QOzPHOuHaNALiHJ53iZ7wRDynypt73ecRSnbEMx9aGylsx404v8mlhiX/DdNkfAJIsrrCqcWYJWpoCNB5/MLj62Yfplu',
                t: 'MTY2NzM2NzE0My42NzAwMDA=',
                m: 'Z6CvfhfqGZ6K9zfBwkzcPJatDWDGn0mvTidjDnRA6Gc=',
                i1: 'zDY9/Csf28UC4J9PsPhvjg==',
                i2: 'XVt8L8og6iBFPkollJQBiQ==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=763a7d47e952dba6');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=763a7d47e952dba6';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=DHEi8JSfKPGRf_Kvy413tSPzAVANx7vsbf1_E4nsCZA-1667367143-0-gaNycGzNCCU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>763a7d47e952dba6</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:187)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr4---sn-a5msenle.googlevideo.com/videoplayback?expire=1667388744&ei=5wBiY9WFM8Hfkgbo-ICQAw&ip=2600%3A1700%3A7703%3A185f%3A3c0c%3A217a%3A8f70%3Ab2c2&id=o-AMtRF94xYDY50zkM7sUhqoMCY7cZR5tjxQKCVgCGrerP&itag=140&source=youtube&requiressl=yes&mh=vZ&mm=31%2C29&mn=sn-a5msenle%2Csn-a5mekn6d&ms=au%2Crdu&mv=m&mvi=4&pl=40&initcwndbps=1391250&vprv=1&mime=audio%2Fmp4&ns=scHPm3X314F_Yx9qxPA2FUsI&gir=yes&clen=2180299&otfp=1&dur=134.675&lmt=1577637415264098&mt=1667366715&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=oQe3hSYxanOTfi1MDI&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgPrgn_mYIxDAc-8VmomfVd12Sjmdluq8DYJTiLIxUDFkCIEbpKAGH4moApeHFx7IuFfXD9Q61_xIJPIwxpyke-Lp8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgIjAEDCLgTIBpqtjgQvVq75NhDiHPSpA0tzojUyAfSf8CIQCnQGtW-TC6-C9k1Tipms5QgjloukjsJwTdNc-wjfti2A%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr4---sn-a5msenle.googlevideo.com/videoplayback?expire=1667388744&ei=5wBiY9WFM8Hfkgbo-ICQAw&ip=2600%3A1700%3A7703%3A185f%3A3c0c%3A217a%3A8f70%3Ab2c2&id=o-AMtRF94xYDY50zkM7sUhqoMCY7cZR5tjxQKCVgCGrerP&itag=140&source=youtube&requiressl=yes&mh=vZ&mm=31%2C29&mn=sn-a5msenle%2Csn-a5mekn6d&ms=au%2Crdu&mv=m&mvi=4&pl=40&initcwndbps=1391250&vprv=1&mime=audio%2Fmp4&ns=scHPm3X314F_Yx9qxPA2FUsI&gir=yes&clen=2180299&otfp=1&dur=134.675&lmt=1577637415264098&mt=1667366715&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6211222&n=oQe3hSYxanOTfi1MDI&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgPrgn_mYIxDAc-8VmomfVd12Sjmdluq8DYJTiLIxUDFkCIEbpKAGH4moApeHFx7IuFfXD9Q61_xIJPIwxpyke-Lp8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgIjAEDCLgTIBpqtjgQvVq75NhDiHPSpA0tzojUyAfSf8CIQCnQGtW-TC6-C9k1Tipms5QgjloukjsJwTdNc-wjfti2A%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:1873)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
