### ISSUE TITLE
[BUG] : Cannot download almost every music i try to

### ISSUE THREAD

**Issue by Cebolacius** [Shabinder/SpotiFlyer#1971]
**Describe the bug:**

the loading bar hangs for about 1 minute and then stops, and the error occurs 

**Media Links Used:** 
https://open.spotify.com/album/3D6BriGykla1Qi2YzeoE7X?si=7BgnR7IFS3uvf79C9Pl9Xw&utm_source=copy-link

**Expected behavior**
Download the music normaly

**Device Info (please complete the following information):**
 - Device:   [e.g. Samsung A10]
 - OS:   [e.g. Android 10]
 - Version:   [e.g. 3.6.3]
 - Country: [eg: Brazil]

**Additional context:**
<!--- Add any other context about the problem here. ---!>
java.lang.Exception: Connect timeout has expired [url=https://dl178.y2mate.com/?file=M3R4SUNiN3JsOHJ6WWQ3aTdPRFA4NW1rRVJIOGxmOGxtOTV4NmhFa0NLZ0NxNTE4a2VLcEw4eHdQcVlieGRmblEvaE4raXZNWk5LT2RWMnZ1NGgxQnlHbnJwTnZueEtXek5nUlp0c3BHeFBkMWV1enhYZHhqQWlvWE9xTEVLQkdaR1YrdDBsdTFudkNtcWVEN1VTcDRDejc0VjZWTVNBSTZnPT0%3D, connect_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:92)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
