### ISSUE TITLE
Majority of spotify playlist not being downloaded and has an error. [BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by OniCodes619** [Shabinder/SpotiFlyer#2016]
**Describe the bug:**
i tried to download a spotify playlist and although i can assume the llong sownload times is because of the sheer size of the playlist, even when the download is done majority of the songs do not actually download and a error messege follows. Im still getting "no ffmpeg found at path" but im not sure if it is the reason this problem exist. If it is i have already followed the wikihow and the instruction to fix that error and it did not work.

**Media Links Used:** 
spotify playlist :    https://open.spotify.com/playlist/046qgTXOO7AAIIUOObKuJa?si=02d32eb07d834f59
**Expected behavior**
long load times for download and after download is complete it does not work (showing an x icon on most tracks)

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - ideapad s145
 - OS:  windows os
 - version : win 10
 - Country: United States

**Additional context:**
As said before i have followed the wiki how on the error messege remedy and im still encountering it although i am still un certain if it shares correlation with the lack of downloaded songs.

Error what went wrong:
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
