### ISSUE TITLE
Download error 

### ISSUE THREAD

**Issue by grgryforsythe** [Shabinder/SpotiFlyer#2033]
DownloadLinkFetchFailed(errorTrace=Find Link for Erotica 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Erotica)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:299)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Yt1sMp3 Failed for bo2cSJVwPDo:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=76bdbbf56b11d9a5')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=1GT1D4Yw2pFJLtHMmaHDgFF.Pm3M5dHVquHSBKwkRaU-1668743345-0-gaNycGzNCCU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="gplFSg_QC1dXoHLpSoOpKrPBemmdpsVA6Dysw5v_mVg-1668743345-0-AUryWXVN0Tku_tUldGC81p5JPv8Rv4H1mK-CPeaw4OVaMLGZ9ZNCHVr-PxRZCkHP1fw-agJuJbqJKoOeUro6-WCOZBT6m3TAk8X2pNI7JLTU8mH0WPNJvKL7FCfQ-YpKG8mRpTzGaDbDrRa4B3YZH3BdIqXlJfmpkyqAIr4SJAXhaYufCCV5d7_8jvICcQJsbuNS67u2Qy2EthbjwECeoYVck2LKJxmZ9gsJ-3zsII0ldlwuhmDJc3llgbcntkPeVlw40EVZLSYcuqdue9pZ-5QatIr29ltTWWsrYcOTJu8fINHZKetO45u0mli41bBM-fZoW1EbPIt_Ryjt9XVQoyb65nKkxpy4_g71Etam2CrOG9F6Bzo7mD20C-D2kSHto1yrJ-ZJcuv-tWm-tIgOjQdTIE9-9ZBXB2w_7jDvD8ZxdRt8CkvgteRDosrNGatMdKLPnlc2XQ1sgGM-3zNsHeU0yVLslSZF5rDrgV6DmKgs6YVyURz1gbPY_LmKXBct34MzBYOfypBKZeiyK9eUiREBu8z9ZAjhk9TBirlZDhBPzaee0Su4SmjXoNgaM6piHCitDhZgBIh7GsfyvkZdtocVrInZOHQXuAwrvo0KD1fqChUmsxv_T_Qh8JzfXysgnGASv_JEsmIyqV907Y2PGNHiB7IpTKkvmpJeZF8QJhn5">
            <input type="hidden" name="r" value="e9oaa2Pl75iIIUG1UdkT0j3wgICKKKzijXolvlFQgr8-1668743345-0-Aena+yUA3Sdq7F1xGg+SXNdTQYnqg9W/LmNs7HsGStUjNaSYGeulCu3F5PKKokP/NWw5d9g43/898BkGhSVdThlilJC7oIu/FFvgMnkSZUhlYD6isJiu/UlIhUh8zASBbk3q05mSkxJRFt7Pt9dhyurAT1V18NJZnpu1wS5ogAZ1JC/ESNnDG+v6c8tk6FUCiMdtXNXstTxZRJfwjK1lndtUknw689SIZ6bPjxrloZlOD57OKpTSYI2vc6yHezPE9kCa77w77DYkl+8j0D2OCyyMnK5Nv6EQ7uGbmPJ2KMA+TWv4XPrxa9EYupoMGtTkB2vkn4QRfwFam6S5l8OKyf25i8c+J2voojxt4PUIyP8Qe9Vfwp0/mZo3ZzDo6ftuQrSilECvlUKy/Ive6lTx2j/kohWOI90/2SultVWgn+Rc8HMn4me13ZUtMV4kKr2rQxVVUY+Cae055ugd+jWckmq8KM32vlY0bSnwS+reZC8VPA7HC3IUnLvtLS0BRkwCd3tLnCTzfFW6rl+N7Jy9Ypi9xvsza+IkKZrx/1yXbGnI6wforr3hLO44x0JtdXTgkL1R56dplnsioOfV2qS4yWMYGFM/mtFM/B3JPQIOQWESE1Qxxw9gGxt4ZPCZobw3cGevGRq09MtDBD1XynLCvRI1uv0QpGStmMaRVHGeRVRS+m0FyHBtoA8t45TcJR3aB+3ZFdt5cVDSqrA9REP4PXIH46e4rYomPN8UyIb4BHXsaRKVa9VWuqbfIVUHFM7zi0oiGEpTPh02BhHa5C2l1FBdsebKAWAsJ/3PsLcJ3ZkO5Ey4FBh/VrO+5mfGepaeFJVAPu4vezl5yvCCFuOaOcT7Gqs/8c2oiCi17wF8ppgUI5Q2+4jyc4gydhShg1iS52yTaX6M/x384B5Af2W/GIybjxQFmB1RPcC7MFz1RxD6putkPhupNIAxfFXWMMzYyOdSdyR4zVj3fwAKnl02YiMHTOyscFCNqU1v80cTKbT7wbwhGjCL70q2pymMOw/Gu81nJjvYvxfyFWSkgwMrwTfcpg+zJk2tFCTVvzgfWBwamZRpMNcMxp4IiTnUQkeh5emnRjowKTDIjE7oxwy9sad6VmKOPGPTYhItRlGgAEoezpl8jfYmiOJOsmTMcH5O/bPHVQq4CxsQwgABS3a3KYxdT0y/QJ/a1VhNTOuOsqq5QOFWNVYPHHOEk0F2t1M29s08yWcJUC+6anQJrvakqMXIYdRLgiM+ObIbzMbD3l5if5rho9lHTD7AToz0MhhJXe/BqZu07Q+Qd4qIgHBC1G+5+kr6zx/NTHGYyP8h/dxudzzhWnGkPSPmgWrS9gfA5iu8yV0RQRkPV4QzEaLImWK52Frr1Ws/X3KCFgFXfgO7wUj3kLfq7pgHesA4KzJr3PFM8Ox/X8vFaX0HESSo/BOjieing3IWlJ/vhHFb12a5Xc0Vq4uQSn4UUII+ed4zGdchVCz22o3Vwqpwpzo0uEOzAntwPByVjy6Pq+IUCvu9uUrRNCHP8v+/AYTPG1QtuC9Ubtip6aqK8GNpDuOT7+x695UshM0m7QhzIsfiVqyqVvVuzY2nk8m4IpFdIbwbTmCUM1keH+/sTcbfbT4y/P/aZ3bOVdpQ9JRdzdSV2hUH7PwcN9hLjGV/PU7DDA2Bd2xCJYytfOHGYBpfo3Tf67FB+cfwwEiTkMjEavxHxMM006oSZItVLE2yaN8Ay4UPBiL/hmkHxddIYqSfyV3w8jhKS2idEoTwBZmT7pTfP4rS2gVWkHodJ99aPuTLKK2QTiD9v35gr4jFx5/vblHRzht/Y4Tu9tU/Jp//A6di15Ba+ZMuspcmSwnfQAQyLbqSDMtCUtmack467XZ0xL7/vsC95r7cBygKPv3AsY52Y5qT1s6B/rysW+a5kEkiEKoSZ90A9MNJSJ54hac5Ksj+NfLwOKJTizujPfV2o8ARsYDno7r4G2t2/WLWo7AqCa0K3dvkTX6hG5Toc/caEgWToRhuo/Ka6gkeJQgeEewintTd">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'non-interactive',
            cNounce: '82960',
            cRay: '76bdbbf56b11d9a5',
            cHash: '9ba65c869aa2e00',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=1GT1D4Yw2pFJLtHMmaHDgFF.Pm3M5dHVquHSBKwkRaU-1668743345-0-gaNycGzNCCU",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'sbMZ068F+VwBKeZZSDL/y+mp5qNobnfynPmEOZAiCBxLom6K5l+sYSNWFIqlD4gXdxKPg+qbo1RMVhKKXF7b6ya0m6wJht1WHCF+wlIrUWKojQvMOoSY8Dw42sfAfH0hoF+t3oxQ/x8CD4r8bTDsj3q4RWR2wR+r82JbOg4g+eYrpPprN+B80Xj4h+H3MRtCCJX5T8i2dCwfVvIW8eVXI90BXuLp5H5r37haIipSZ857ofx9NfOiRthCpAVZ+h0EX/AlXczBUgP4tpnJ7l+tnrK6iXiCYeE4KWKslAE7qYRIUhXioKZa4qq/3qmEzk5nEdMcmhJRgDPOji4TcGZNBErEw9PlSCnH5rBOWexnH4z+tF50CtQtbANxHLSQ3e4AiZbV4c6+zQ0r8WKplO/GZpJypCMtnNMAe6oyOhYKJtuzdHGqfwEKRPDL2At4mlnsxOVChgqFTZ9svydYKBTA1193VHrmO1x+LGm4UkQsZgqfxVuAsdmKB2MMyB/x9JObr8EOVoyUxm7ZMTi7sEZwgRp17sV1qMK9ShxjMiMGUxuZcJ5WE7F1qq7BiZC7Y75azdh12AZlW4QE5cVVu+hDu4LUII/siy42/zuwaoLfOJVYm7DMuObo4Qn3tVp3OAEq',
                t: 'MTY2ODc0MzM0NS41MDgwMDA=',
                m: 'wjQOwegX+TvZdiPcDnzyvfpkSDQLn9eL/2/SbweWPLE=',
                i1: 'a2sfxhXPSI/8J0zI/maFrQ==',
                i2: '7bAS4oHwPAb4I2fgBPQE5A==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=76bdbbf56b11d9a5');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=76bdbbf56b11d9a5';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=1GT1D4Yw2pFJLtHMmaHDgFF.Pm3M5dHVquHSBKwkRaU-1668743345-0-gaNycGzNCCU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>76bdbbf56b11d9a5</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:187)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr1---sn-hp57kndr.googlevideo.com/videoplayback?expire=1668764946&ei=sQB3Y-mfNsaL4QSuo5jYBA&ip=2603%3A9000%3A7202%3A1e92%3A3d8c%3A14c1%3A9389%3A873e&id=o-ALTrmq0fKxKRwu68tmVOkSgL6oAPNCdwzoUwIkbUTAUe&itag=140&source=youtube&requiressl=yes&mh=k7&mm=31%2C29&mn=sn-hp57kndr%2Csn-hp57ynss&ms=au%2Crdu&mv=m&mvi=1&pl=37&gcr=us&initcwndbps=2152500&vprv=1&mime=audio%2Fmp4&ns=folDH7KthgKpnLtOz9Iovu8J&gir=yes&clen=5158851&dur=318.573&lmt=1667679547817919&mt=1668742852&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1311224&n=TIjnSAL_K8XVHI9De&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTUIDikrtJVmIF6LbG9ny9iq8HGf2sK8bwia-IY_DuOoCIFHLMMwosYZ3eNhMoNmIWSZ3N9bDZc6dNcE257aic7va&sig=vrFMwLfjd4AxhF3NFMTGK883O-s0k%3DwjwPOe8ko1AEiAZN0m2Frns3gHA3doBD9qjDr8A_hjFA_vPmH6dIExhzKAhIgRw8JQ0qOBqr) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr1---sn-hp57kndr.googlevideo.com/videoplayback?expire=1668764946&ei=sQB3Y-mfNsaL4QSuo5jYBA&ip=2603%3A9000%3A7202%3A1e92%3A3d8c%3A14c1%3A9389%3A873e&id=o-ALTrmq0fKxKRwu68tmVOkSgL6oAPNCdwzoUwIkbUTAUe&itag=140&source=youtube&requiressl=yes&mh=k7&mm=31%2C29&mn=sn-hp57kndr%2Csn-hp57ynss&ms=au%2Crdu&mv=m&mvi=1&pl=37&gcr=us&initcwndbps=2152500&vprv=1&mime=audio%2Fmp4&ns=folDH7KthgKpnLtOz9Iovu8J&gir=yes&clen=5158851&dur=318.573&lmt=1667679547817919&mt=1668742852&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1311224&n=TIjnSAL_K8XVHI9De&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTUIDikrtJVmIF6LbG9ny9iq8HGf2sK8bwia-IY_DuOoCIFHLMMwosYZ3eNhMoNmIWSZ3N9bDZc6dNcE257aic7va&sig=vrFMwLfjd4AxhF3NFMTGK883O-s0k%3DwjwPOe8ko1AEiAZN0m2Frns3gHA3doBD9qjDr8A_hjFA_vPmH6dIExhzKAhIgRw8JQ0qOBqr) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:1873)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Moto edge 2021, android 12, USA

**Comment by grgryforsythe** [comment]
Moto edge 2021, android 12, USA
Spotify

**Comment by grgryforsythe** [comment]
I just got this error, Spotify
