### ISSUE TITLE
[BUG] : <Issue_Title>download failed


### ISSUE THREAD

**Issue by ggkameleon** [Shabinder/SpotiFlyer#2087]
java.lang.Exception: Request timeout has expired [url=https://rr4---sn-n4g-ator.googlevideo.com/videoplayback?expire=1669831884&ei=bEiHY5q3MqOExgKV4IKICg&ip=2a02%3A8440%3A5219%3A19ba%3A81c0%3A1109%3A573d%3A32f8&id=o-AGfupXVsEVD3rJNc0jjJWfEfPn6ZFZbg0W9ACv0oIsj6&itag=140&source=youtube&requiressl=yes&mh=cb&mm=31%2C29&mn=sn-n4g-ator%2Csn-n4g-jqber&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=48&gcr=fr&initcwndbps=571250&vprv=1&mime=audio%2Fmp4&ns=qjPyy-6C-4tZ9VGG9FQann0J&gir=yes&clen=14389853&dur=889.036&lmt=1571632111139143&mt=1669809899&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1311222&n=7duZH5QpT8z8CRS&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgbjs_zZzt8fq9dD6FEtTpEg30sDHuMK_6Cy5klIQbs6cCIQCwpaxQXnyokMcfvT6ijz10PvcAYtUs6WqZYAoTsgjz9A%3D%3D&sig=AOq0QJ8wRQIgKpiCrCad8uNAtiZ4hKLDo_kKD1VK7q1-BuWvrxPc7DwCIQCIQRz5BWhtVvBIkcTGZCXYjHEengVed8DBjYPupq7shQ%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
