### ISSUE TITLE
[BUG] : Downloading Music Playlist from Spotify 

### ISSUE THREAD

**Issue by rafly-amrie** [Shabinder/SpotiFlyer#2163]
**Describe the bug:**

When downloading playlist from Spotify some music return x icon and i icon, when click i icon, showing error log and hoping to report it in this repo

**Media Links Used:** 

https://open.spotify.com/playlist/0UxOgeHBGFYmK3AZzChu99?si=woj43iukTlWc5uopof9tkw

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```
java.lang.Exception: Request timeout has expired [url=https://dl38.y2mate.com/?file=M3R4SUNiN3JsOHJ6WWQ3aTdPRFA4NW1rRVJIOGtjRUx0dUZ4OFRrR051Qi9oNkZrNTlhSkF1MW1aWWt1NmFPTVd2OTUzQVQ1V1p2QUVTS2dtTk1XWTErbzJmRjJpaHI5MnJzVEV1VllZRE96ck1Qb29obFR3aUhRVGV5R1IrZ0hORGwyc3hNbDFTK2Z5YzdFdUFIdzdqai9nVlNNZVRBZnNENU9iOVBkNGN3TmgwK2ZLcVhDL2JrZytSYXp0YzRSLytQVHVSR2xoYlU3dDRGY2VnSnhhNEJVeTUvaDF2M0orQlpQMThoTmpSVDAvYmJnRlpjdkdmakxMbThsYTNwYXIvejVBUjhjbHc9PQ%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Device Info (please complete the following information):**
 - Device:   [Xiaomi Redmi 2022]
 - OS:   [Android]
 - Version:   [12]
 - Country: [Indonesia ]

**Additional context:**

**Comment by Erictheplague** [comment]
Use YouTube music

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
