### ISSUE TITLE
[BUG] : Most songs in spotify playlist isnt downloading

### ISSUE THREAD

**Issue by MrHitMan1** [Shabinder/SpotiFlyer#2166]
**Describe the bug:**

Some songs in the playlist wont download
**Media Links Used:** 

https://open.spotify.com/playlist/5eQ3nngEaNPacprxPnsTxS?si=144bb8bd5ca44d69
**Expected behavior**

I expected all the songs in the playlist to download 
**Screenshots:**

**StackTrace:**
```com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more

Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [HP generic laptop ]
 - OS:   [WinOS]
 - Version:   [3.6.3]
 - Country: [India]

**Additional context:**

Not only for this playlist, happens with others too
Also sometimes an error pops up saying "check network connection please" even tho im connected to the internet
and another error that comes up when trying to download these songs is this 
![image](https://user-images.githubusercontent.com/91072234/208231471-927428ba-3fc6-4c10-868f-1acdbd4720f0.png)
(ffmpeg is already installed on this system)

**Comment by MrHitMan1** [comment]
Manually adding ffmpeg to path fixed it
