### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Aadamgaming** [Shabinder/SpotiFlyer#2177]
**Describe the bug:**
download failed

**Media Links Used:** 
https://open.spotify.com/playlist/37i9dQZF1DZ06evO0TOYhj?si=a7iTDLYNTkKp3wI8pPOB2Q

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```
DownloadLinkFetchFailed(errorTrace=Find Link for LoveSick 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for LoveSick)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:299)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Yt1sMp3 Failed for JXdh6LaMBCk:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=77c2f38b6ced3607')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=CZJ5vEO7jbfFfdRCGQx3V_yDFAztRcxsuTAcTiqmCg4-1671482405-0-gaNycGzNCBE" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="INP_muoSyhBzMDbYpS6d8CQ3D5wAWqTHw8cWs3S.CnY-1671482405-0-AUjbF5u-l-ctD7NgHUME_weTp12bbJN833xOdymr2FP8eo2GqZnSkpEN2uRKioiMrg3r389hk1mAVyAOQRXyF_w6aknFa4zzVIaS641xrhWT7N4yiXwRO-nZCEByBsHU-uJTVR3nhLKWsvcAd7tneVrZAI9QyX7t2oWUI3KunN7mE1c4oYKno-wn7KTMV_0nGYqCLMKlEPZVQ_4fpD_f054iyVcu8jCMPX689P6ON8sM09-97GOTror6oECrx7flaU3OK-kfBBOvlcvA17PkQwhtLKZSjX5hXHhG7-z0Slk09dqqnOqyxvtb-TFxSYoESbzexh0RPbJgkXaMQ06ntj7yF8CXJOFEfAdySRJHCIkSOzu6sYZbSutK-k7aOhCF1O3-TBIirPhwHXHUvFpG-KqcQHq8IBLoXS59PLT-NqoRsXaQhOrQeBZ8KooP2eEL4pe3QJsN_cRb7mV2pPqSL6tWX66N53Xamw5kekn1Q0uIW68fV5kz8qtcKiYuDUgGo3hBomXg8XIdcvGIdbx4v6lgDFYeCxtFUM548yqWXT_ifwK8LaM1rnOEJeoPRufIkrbAImxGHsjfZ1dO7ccseJr_Q2LNPqBZ9J8v_Ydr3Rxz">
            <input type="hidden" name="r" value="fYcfnCU.htdfZoCDZnDOm0lbYd81Ghcy8Fol4kmbDGM-1671482405-0-Aco1QOHfFfuw3feUhIQ9SGx14Q0CWKiKVEC1ofP7HOI6gDM0nUZAE0W275UsPzBXyZA6iv35L60YCPKmn1orwjePEfr95/bbhumb4vG5aIWK6Djq9pHT8p4z5jVvhBR3MqrBsSR5+EgtzLabRvLrvhcwg+TXn1z+dne/hulgqAo1925xft+jBjyWrTwVKqujvtUIrHSqd9z4Opa21YqiMhOgz1GRTDprJSiP9fheIpCZg00l9p4s5liFNd8ojUmA16NebwumOS1NTqnW+6Q/YPYXYyyiBQOZf4KhvgbZCYVw+fml6Dhg/YDHnQdFazztgODlnZ56RVecN4OF1DF2eU5V50NULExEQsIf2uYd7USOOnuKb9BJSgHxHq3iGZa33wuURC1GpOPTBADeoNFtH+p+lpasMuzfOHtWkhgajzfA4gPJFn1YB1pZJJa778eWdPDTxoL8PQO0xEZcxpDMEfK5oL/8a7PGY5XzOcF0CS6vvchcrug/I0Nx7waBk1Dyh0CDjfhKrnOPFK+9tQ2qptVEDzH41od6SpdP91SxBNKMaET8dHc/7ciHzfUdEDl54FL1KmATLk57MSgU/9v1jAq7DNfontJeH3Y2DkXFKK19ilt9jzstBgncQnK0U5b4iFpKtl5jWlvjlDxa2rRuSfPWdgFjoNaqgY068pNoiFQuIkZXL7mUwZqUvULL8WLvaLPNnIuoIllQLuS4Kbvv8LgKFiXlANHIY2ZuVD7O0mSel/VGL6XBCTE+0nfiCTNRy207ofFR1RYLcAvvMT7/8SN2SUE61XK9xPo6RsnCaR0J+vO61WZKb6LnoQ5ULrbqJoeINFv5p11++Gc+CDUsn7Y/BfT5kkbBg+haAmGxflLStnpAvsVsZ9YqSKBVy/iQ254w0qFtN0aC6w4daUIlJ2Lp17kFqhp8WCYzmRUPOXkhiWyXxvkvt8f2qkFumjAqwA4dXRPIn7K4UG8vodhbUqwliLIcD+JCXFl6tYvu5fpwEZ+4IX7NpWQ5gk2CZvLlzBGgoQut1wI30Www42yXHxsGnm523RCiUVsdSIXvHm8eMGFVm6zHZ68H0WHkP6+cBlrRGBehS6GInp/jryGRiHbeTZiEFEdciGfJynFD7At9LMNbmLyqhvuRegycyk/v6o3UgTE6b+wnKp3WvG01Hmg6y45pl3gPE+3/JDibPBTlRl8e4qyx6GqpTIEUIan/BzjKnh3FffAmaCNQj2Jg2eixsL2S4YlB1tOe4e2o0LFkqDF1C+1KzfJ8iIGqoLenBppl0+VkDRol8JeygnsXSTdytzjPSVQ/7K2MmwtQHN7sc0bJJ2UVVbw/PwlsKmIl/MUEqXVSaORegG3go3gf8WrrSDXy4Jty90tDwHDJe8F+OF4JSygQZ7XtGkW7gdMQDeIk9n2XKE175hrkxo93FRdTTXa53+a5f141ob1moj4Dr5X1MVZrWg7bKC948fnVkypIe4bL1g4hGMzMmSD/C8dUuwXw+Z18i8k6gjz/vL9fLI8x9MGzatSSpvDTMCgPAaqKjjw6yl/TKgQNCbZbh/ALlJxNnTicx6ErZWSca/+DcRQB+yehntvdI99zY/rAtiSXbr6BwFATiqS+2S9ElX5NGd1DxUZPOHcTnXByeH0e1rHpJwt3FV+fYFK/KHwAKF/5eDNEcxjVXWTjY+yrZPhSC7dfrzWsPeqhx8yECo7j9phGUzUbRbarQnDvrzb7Mo2Txe07DJm5FD+JlRm8rJ3LRi4ljei1lI13kqaikvl3oIoabPFnc8+FodbNSNtHxpBhTFoMRQs0CDE2glZrRQKZmdSQfmI31+nHqr/wPqIGkMQuscJI0zX7VcBUCBMBDQOVaC9XkNSzidhIoscRNH9S/6ZwdXl+l9lm8WUFTIIRo7wULiV73DA4evUaNQPICOAbb7HnSeELiGV81chKxlsgNenFH5UiT4EwyET5C2n2GfJUYEifKLQzDkaUVMsUACQUmh5h64AkAOwGI1xoeM0=">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'non-interactive',
            cNounce: '88615',
            cRay: '77c2f38b6ced3607',
            cHash: 'e814506eed0bd52',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=CZJ5vEO7jbfFfdRCGQx3V_yDFAztRcxsuTAcTiqmCg4-1671482405-0-gaNycGzNCBE",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'GSB12WU3VfubxrKL0cjs2AZZFPI7Onaas05bRdx7zS47eDVcNZvUsvtkvgyoldjjLuHp2KSntvj4rKQQUUu7lG8YBJ9XiAvW9W67E8TQlo0iwWfcF4qc2dR/f7uxEaGUGktALOmswTGHwtBMNQ0O3kFFoALInTsvfmoQANaOrZR8DSYejGJllQiFtuL16bqe4wwMLjTfNfRULrKC5PnfH04nnJk26no4IoHXCROzRefP7Jz+OF4WXz3s6MmjaN2J/uVYS1OzgBl46pnucFoDBkEq3gOp9DYQDBww2Sq4K4cuGFa0bHfl8SuWfGUWUQqA8x9qkn3mIBzVwU6z0LeqZ69Vuh+48912CrcEMw8OoLRADKixJE+s903pkATARjAEcRWKiVUHbp9LhK5VWHfuiptd4xT3/EH9QiE5w1qR+ICz974rkHEP0p17CXm3etQqU7OrsvPnaPdo8XvbfYjvgosCS2itozEKljDCboAdSMuudFwwMwLBXs99Vj2tFeBnhjIbXZ6xC1taRACdIzNpDVjMAyPIJJ8XsU/UMbARvYv2Sqw61EwQQ3jzkWt/POdBKgUki/HzNhIDKz5M1B+RgQ==',
                t: 'MTY3MTQ4MjQwNS42NjMwMDA=',
                m: '+XZx//jZYIJWoU1Uw3WUM68XH4MINvjNGmWFkx890wc=',
                i1: 'AAN2v39gRm9Atgj6sOb7fw==',
                i2: 'MNRbr6wZPTgFvBUUnZKdPg==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=77c2f38b6ced3607');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=77c2f38b6ced3607';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=CZJ5vEO7jbfFfdRCGQx3V_yDFAztRcxsuTAcTiqmCg4-1671482405-0-gaNycGzNCBE" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>77c2f38b6ced3607</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:187)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr1---sn-8pgbpohxqp5-cimd.googlevideo.com/videoplayback?expire=1671504006&ei=JcygY-u0MaiDxgLL_ZbYDA&ip=82.40.2.17&id=o-AOAic_NzB7nKRQTuDGBYOLncQ3CwmExGL-eOgfaZBuFj&itag=140&source=youtube&requiressl=yes&mh=f9&mm=31%2C29&mn=sn-8pgbpohxqp5-cimd%2Csn-aigzrnze&ms=au%2Crdu&mv=m&mvi=1&pl=22&gcr=gb&initcwndbps=2036250&vprv=1&mime=audio%2Fmp4&ns=y5ED2vDrj13iPc2srZtl27kK&gir=yes&clen=2367855&dur=146.153&lmt=1638576018989107&mt=1671482252&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432434&n=3isoR57eD7lZE2&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIu8yHWEde-VKjx7qKDD4a5mJO2_XeRxlh6BTyErOC5NAiEAlWMR1vkzB8fHRavDPyzr1pHxG8-R5Bfy8JSnIaAcdIw%3D&sig=AOq0QJ8wRQIhAOxkw760nOzQrJrt9eRIKOOPVnw6fdST1ssA4hlanpJUAiBfhUtS2bo8pHb5d-_OjtwKcX8dNAJmsdTlF1kWBp9glA%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr1---sn-8pgbpohxqp5-cimd.googlevideo.com/videoplayback?expire=1671504006&ei=JcygY-u0MaiDxgLL_ZbYDA&ip=82.40.2.17&id=o-AOAic_NzB7nKRQTuDGBYOLncQ3CwmExGL-eOgfaZBuFj&itag=140&source=youtube&requiressl=yes&mh=f9&mm=31%2C29&mn=sn-8pgbpohxqp5-cimd%2Csn-aigzrnze&ms=au%2Crdu&mv=m&mvi=1&pl=22&gcr=gb&initcwndbps=2036250&vprv=1&mime=audio%2Fmp4&ns=y5ED2vDrj13iPc2srZtl27kK&gir=yes&clen=2367855&dur=146.153&lmt=1638576018989107&mt=1671482252&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432434&n=3isoR57eD7lZE2&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIu8yHWEde-VKjx7qKDD4a5mJO2_XeRxlh6BTyErOC5NAiEAlWMR1vkzB8fHRavDPyzr1pHxG8-R5Bfy8JSnIaAcdIw%3D&sig=AOq0QJ8wRQIhAOxkw760nOzQrJrt9eRIKOOPVnw6fdST1ssA4hlanpJUAiBfhUtS2bo8pHb5d-_OjtwKcX8dNAJmsdTlF1kWBp9glA%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:1873)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Device Info (please complete the following information):**
 - Device:   SamsungGalaxy9
 - OS:   Samsung
 - Version:   10
 - Country: UK
**Additional context:**

Downloaded a play list and only one Spotify song had this problem.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
