### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by jpegvr** [Shabinder/SpotiFlyer#2201]
I got this error message
java.lang.Exception: Request timeout has expired [url=https://rr4---sn-8xgp1vo-hp5e.googlevideo.com/videoplayback?expire=1672108139&ei=CwSqY_yvIaaMkATE4bnYDw&ip=2600%3A1006%3Ab020%3A88c6%3Ad0%3Aa3ff%3Afe63%3Ad4c4&id=o-AC3usfHqYGz0VMidGiWrp1xIZhuhWt3QeDOfDfHFdC-I&itag=140&source=youtube&requiressl=yes&mh=Kg&mm=31%2C29&mn=sn-8xgp1vo-hp5e%2Csn-hp57knd6&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=44&initcwndbps=290000&vprv=1&mime=audio%2Fmp4&ns=oEccbT0yt4PJIyY3OxoidlkK&gir=yes&clen=59083410&dur=3650.710&lmt=1559156176410394&mt=1672086295&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=PA7bVnu9eBUyVMRLP&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKC5lZzRGY8_57VrkoK51UBqtTfWXD2jH_JP8ObhyV_lAiEA9sm-giT2BeBa1VwMK-6jLAL0PEG4uoOvLLykodn_Mnc%3D&sig=AOq0QJ8wRgIhALe8fom2IsJcvsGT3wfjh3hyBbSl7jZlxB7SMCNbGvwdAiEAhbFYESdYrUOqKCyi7QsfaBjFRZiMD0Qz50nJjUOyI-o%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by ericsomto** [comment]
Clear app cache

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
