### ISSUE TITLE
Wont Let Me Download some songs

### ISSUE THREAD

**Issue by darshtechtutorials13456** [Shabinder/SpotiFlyer#2206]
heres the error code thingy, used it on wsa, and normal windows is telling me ffmpeg isnt installed, how can i do that?

android error code : DownloadLinkFetchFailed(errorTrace=Find Link for Alpha Male 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Alpha Male)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:299)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Yt1sMp3 Failed for XTKiVAaW3JE:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=780b30f77bc4dae9')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=QptgwV_95x1AOSznVaBVjc3UlMnCbPlxwqK5lyyiJpU-1672239896-0-gaNycGzNBuU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="X63iUjvhvavIXxUXciWgDx1OIvTP_5_HtP_0GM7zZfY-1672239896-0-AUrCkmUecR8lXGA9DuoJ49NQsyxrtQjd5QG1FHLDUnnWdGf4dlobil9-RICiUsmSawETY0vmXlVT3unF0VI4YrOOuWJrwn2KfOILfNaTpzm8zrQ21-7sMB5kp8VPZ070b_qjtKEYHLjHoQlD6qN0dCfbpnuR1GKrBixMNGomZ3-WXJibF9Dm9P0PI4__OFMOqx2-bC61uI6vwFnije9-V8yJTd5XfqQEKZokpTKMbPQj3O2FwLqqnac1UmKGA_11OQvwZ75TMBUHlczzP6S2wFo5aRyPO6IXjAW9dGQGG-LM6UYb9m6x1NKKSRA4gR0oMggTflYs3DAVPi4pBtTPJWjnvMTB_jBQ4_vaBj_BIZNwVwJ4OeDCBErWlNC_AAEJp-E22tN1sPwKKrI0-0IM28TRICYfDorpiS2P8Oc1NniL_dCAQ57rfPFc70yHSSp-QIdS114fjSRKrVZVqnTpucwwwNz1I0Ulx0K07rIpvbFHzYqp6y416wrSTIY9hBK5mUhgQspkzfaMVZi3zVjiSTmpCDaLj-7KGl3H82_vMVSrWQFQiWu9hPx49QqtgD0rDZQven3uh-FsAR1nlfnAwGO3GuIvfPwc_2Seuy2oEAv3">
            <input type="hidden" name="r" value="fDNeAov0gBKDn0LNRacUQM3xOCpO9ha3wk4kDKpz8_c-1672239896-0-Ab55Alor0RrvcmMossdZeNHVjx4gzB9muqomNVXZFJyyCA7COVx4LkcsRlG8S+hou9j+99Pe/R1FjVUYz5e9qskg3Mll9sXo4rQTC2RNMMWzyBNt1mS6H80sNquyCO+Vc+aOpVnPlRdSBIILFYn/WnuMTVAqdAR24eEeHeklVPT/g9j0pTP6/pboIZIdzdz2zhLLAvfRnciAUHwdLx9DWe70WUarTIUYf6wZHfDbm5J0eGObg4cVnZ4XHigWjp7iaDBPoMXYkQf7033M0tu7Ek8uruvPeR/wp4ulfynOLgR6xSzEDSbIk3QQAxx09njKmFEii7INROrTT9IsGbVdXX/lYuDrcrBb03V3qZpJdju3qlo5sgb2Doyfv1sWB8aKIHJvKfIMhO4QR9IihKADfaUbCChaL8YC4YjYl1EbKAwZtQd+mKq3YmJHCeWyOKmB4I7s5qK1NR/C3PFbe7CBHHKauNKJ9bkLphWSXl7nx+Q/gKRD1GcxEYRxAIzfu9z0XtPXsJlXbEMHA1e+Z71qe0QRcapdBI9GAlkABTRGkX4yjmr9f/XlFNlmUHMT4W/sOi224dIfy+6RZ5LAzszMvKI/1B0FthDNQVGsOIjU6fuHay+oASEoAdPYeFqAwNir8QkWunjetS8IHD2KtdG06Xz38A1TIv7SpWdaWRvyJkP8tj9qGE6Nc9FTunD76ebHXrL9a2OH9NW0aCAd4XG3yFlVu8fya75y5s2OGpLxqG5g0dSqeCohieN/elagWTTma6JPjM/ZGrKhNcyLHZU3WQEtfecfZFcX+oWKkKyDDsXNHFyfpcyOZ7VMJ8Z++1jZbeUS16Y5LsGCOpC/VFB9umBnUMT4kmHyo6RCejdoUoHnTV/ADaf6luQ7+lRIB7Z9PjswyzAZaj7ka/9jxtj+Dw/MqRj3R6ZRMlnJ6ChAHuLtBWmE/tbyuxoBni0sV0bSYtMEXmHEa756Apw/2IFw87K5cEwtVy+8aWXD5rWZ6+9e5Ind7X7SD1Rr2soKzmXTGp3LsJPcqBA3iAOf+6gKgugSrzW7ncWSQtnNuiyd4YpOKuAR6T/ppQvHaTneXu/X7q24HIc0F9QcAcXJUOnKP1A1Sl8yyMRRHoFoC35N2o8ytix10utBmJbYnAvRHVKgURKIvH3EvnSls5LqTkQEUPsWlvCpw8UoYg3mxXM8/gi58n/kb6GtTpgbwIJ1IfngaMd4oilsTBIoXBgUMfWTiHLexh2aK44BsD9rdaqbC590oDtCrL9So6lN4S0Bfh41cHDh1jLuG6H2E0kQzT96siECiVM9TfQMsFp1+CEA6L/Y1e6t7QW0Dnwic+5qS7govpMjkBMjFv2jOjeYIv9bN1m1Cv1/ylKoU+MR5FVdjDpIBcBgXNe1rvW5CWac9aWyOtz5BSH2OTa4b2z7gRqOEkv+sumWTxTehX4/K//h3PRwtNgOm2OJs5RZo/2m08/z0DQapuvbDYqfqy0cAVllUTU3jeF4aQo/tIs7eCKnZLNDLmPDc0+3ERdDhDLdpOBjOj6j9t3W6LYaSab5kLUOI1rW7mT5NvHhsrK8P5FGUm20qiXTMKV4ZuMZ4s3Q9CNmZGoom8l8QnAqFiEe+7xGD+G6LXgLizm+ualCMvXy/W6EbUFA4ztlU9js+5/6HrEevk7+XjiWjoAMbCKVBpzd77JM8hBk52bXrdDvlmBNLNLG">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'non-interactive',
            cNounce: '91770',
            cRay: '780b30f77bc4dae9',
            cHash: 'b1a839fe53ae965',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=QptgwV_95x1AOSznVaBVjc3UlMnCbPlxwqK5lyyiJpU-1672239896-0-gaNycGzNBuU",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'H5SSlwHmmNqYIBbKcg0iZiI6pDMj70FQgJ1WUsDWJV/0iw3u00YxhO5UxMJxxYbfke3NKnVukHJ7r3ViK/YWMGennXLAIfuk7r+qOZd8Eox4caFCCfjtkF1qlt+dOYbasBqQZBx+a/GdVuJgBFJ93tQmIdDDS/XPmZz8NE2j7yMmMuK/nmOSZZqCXI39Xs+hXMJhu4Gr/IvBiQ84SJ8JFtMU+nNVAGx5D/dK7SredjpAroIs+VaURNGUIcApxc/Hg3Ioqv/h66cr3kwG7WjDALTL6ea2zYUDVmF3p1lno0BgPXyoYSkBEPTq9ANTec0JbLWyxgWyu3Xdp3qhb0Zba57HZbO6BhjtJobuWU0XQETEDtVKUkh3mX5MgSOGgIn2eJOagtvS+zMthK1XFTPuE6x2/svA4y9kHMV6itIZzHK2/Y/xm2zpT8msJs9WAMBMpQW/Q3JB/dAqOUUhVkQseN9mGuiI50FWDtKfO9jmKNVC+rfbU7nWnSrra5Ari/sUuOuNCToAsQ4N2Zoz90RqaBKDqQ1lgpMb/h1m+O+mYofJ+pMl6JO232xzrlhfN3wr2YZBsxXFr/+WxHpUAIXK7Q==',
                t: 'MTY3MjIzOTg5Ni4yMzYwMDA=',
                m: 'cLZirf5T4yvMdbquO6a6bNYOcT5MNERqJX4V8EmO/wQ=',
                i1: '/Kurhkn5GEkusYZt7aJBQA==',
                i2: 'dds1lKpuf12zMS4ckgzqWg==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=780b30f77bc4dae9');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=780b30f77bc4dae9';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=QptgwV_95x1AOSznVaBVjc3UlMnCbPlxwqK5lyyiJpU-1672239896-0-gaNycGzNBuU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>780b30f77bc4dae9</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:187)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr2---sn-hp57kndk.googlevideo.com/videoplayback?expire=1672261496&ei=GFusY9eCGbGA_9EPg6SKiAY&ip=97.102.147.156&id=o-AEh3bGRDESzqPXOEfFu1fC9FDjfcxdHnNl30I8dHniEL&itag=140&source=youtube&requiressl=yes&mh=7z&mm=31%2C26&mn=sn-hp57kndk%2Csn-q4flrn7y&ms=au%2Conr&mv=m&mvi=2&pl=16&initcwndbps=1730000&vprv=1&mime=audio%2Fmp4&ns=A8RyMA10-NY6R6efssLz9kMK&gir=yes&clen=3183749&dur=200.411&lmt=1539585586012078&mt=1672239440&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=RYbyAiISWUBOf4XXE&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPtP3j5WFxrlzjeOH4Tvy_M4Gvc5y7d6JS4g9xEOMODrAiEAksmKxEMJpsPMbnEXxCw8iIMP3vRwTa5rYwHAZT37080%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAM9wWBK-elfeUQk1dTnyAfSseO-a-22UV5XpvWtElrL3AiBt6utrvJUbaZf5wUMhhBOWXU1NKQeQUWJxbg_tFfswvQ%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr2---sn-hp57kndk.googlevideo.com/videoplayback?expire=1672261496&ei=GFusY9eCGbGA_9EPg6SKiAY&ip=97.102.147.156&id=o-AEh3bGRDESzqPXOEfFu1fC9FDjfcxdHnNl30I8dHniEL&itag=140&source=youtube&requiressl=yes&mh=7z&mm=31%2C26&mn=sn-hp57kndk%2Csn-q4flrn7y&ms=au%2Conr&mv=m&mvi=2&pl=16&initcwndbps=1730000&vprv=1&mime=audio%2Fmp4&ns=A8RyMA10-NY6R6efssLz9kMK&gir=yes&clen=3183749&dur=200.411&lmt=1539585586012078&mt=1672239440&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5432432&n=RYbyAiISWUBOf4XXE&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPtP3j5WFxrlzjeOH4Tvy_M4Gvc5y7d6JS4g9xEOMODrAiEAksmKxEMJpsPMbnEXxCw8iIMP3vRwTa5rYwHAZT37080%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAM9wWBK-elfeUQk1dTnyAfSseO-a-22UV5XpvWtElrL3AiBt6utrvJUbaZf5wUMhhBOWXU1NKQeQUWJxbg_tFfswvQ%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:1873)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by dave9123** [comment]
Try restarting your phone

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
