### ISSUE TITLE
Bug : unexpected end of stream

### ISSUE THREAD

**Issue by usertry01** [Shabinder/SpotiFlyer#2215]
Unexpected end of stream when downloading the song "Bohemian Rhapsody" by Queen

Song link (Spotify): https://open.spotify.com/track/3z8h0TU7ReDPLIbEnYhWZb?si=2dAgxydYRlGw4wX97S9FyQ&utm_source=copy-link

Bug Code:
java.lang.Exception: unexpected end of stream
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:92)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Edit:
Device: Poco F3
OS: Android 12. MIUI 13
UK

**Comment by ericsomto** [comment]
Have you tried using another source like YouTube Music?

**Comment by usertry01** [comment]
> YouTube

I did, the same result, same bug

**Comment by ericsomto** [comment]
Try clearing your app's cache

**Comment by vehosah** [comment]
> Try clearing your app's cache

Tried that, but it didn't work

**Comment by usertry01** [comment]
Fixed the problem by redownload the app a few times. I will close the issue
