### ISSUE TITLE
Time out [BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Sggfr** [Shabinder/SpotiFlyer#2323]
The track I'm trying to copy from you tube is just under 14min in length. 
This is the error message I got

java.lang.Exception: Request timeout has expired [url=https://rr2---sn-aigl6nsd.googlevideo.com/videoplayback?expire=1675518381&ei=TQ3eY4jIIZX9WMqmpOgN&ip=2606%3A40%3A61%3A664b%3A0%3A0%3Ac60%3Ad0aa&id=o-AFNuw64vggH8jzeC2uG40cJX93JBqCNs6f5deDjyrssH&itag=140&source=youtube&requiressl=yes&mh=ZX&mm=31%2C29&mn=sn-aigl6nsd%2Csn-aigzrnss&ms=au%2Crdu&mv=m&mvi=2&pl=48&initcwndbps=2765000&vprv=1&mime=audio%2Fmp4&ns=Ly1YfTdCTJTiPzWSDE1mkMsL&gir=yes&clen=13098117&dur=809.261&lmt=1670499958655982&mt=1675496724&fvip=1&keepalive=yes&fexp=24007246&beids=24462254&c=WEB&txp=5532434&n=74o3CkY3wBIbG9&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgV6fIwCpRKJtxO0WTqx48b4lVlfrjuK0hQhFzTI7LRmgCIQC-Fjw4Sv_NvWStH8giQOqK__syvx8a9YdTJNvWd2p8ww%3D%3D&sig=AOq0QJ8wRQIhAMAIbMHNo6HIqqmmSKCHV7_9tdT4ckitNzvQORvSG0o3AiAUtbHinzL3xbIS0i0p3CD6hlFOEGXMMHOpXO1qce5MBA%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

	READ THIS!
	If some Song Download Failed with StackTrace having any of the following reason:
		- DownloadLinkFetchFailed(trackName=For Those About to Race, jioSaavnError=java.util.NoSuchElementException: Collection is empty., ytMusicError=MP3ConversionFailed(extraInfo=Client request invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY !
			- Please Dont Open issue! , Online Converter Was Busy! , try again after some time and download will be successfull . 
-->

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
