### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by xJoshXDx** [Shabinder/SpotiFlyer#2349]
**Describe the bug:**
I have no clue 

**Media Links Used:** 
https://open.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP?si=713rnUHzT8m16y0eN8lCOw

**Expected behavior**
I expected it to download 

**Screenshots:**

**StackTrace:**

java.lang.Exception: Request timeout has expired [url=https://rr4---sn-a5mekn6r.googlevideo.com/videoplayback?expire=1676198424&ei=uG3oY_vwCIrRkgbo2azgDA&ip=2600%3A6c51%3A647f%3A960d%3Ace59%3Aceb5%3A85b7%3A4686&id=o-AOW7aA0G30orrBJ8bblOVtBa8r7SLNYvLr32NOjw90nf&itag=140&source=youtube&requiressl=yes&mh=IJ&mm=31%2C26&mn=sn-a5mekn6r%2Csn-o097znss&ms=au%2Conr&mv=m&mvi=4&pl=32&gcr=us&initcwndbps=1923750&vprv=1&mime=audio%2Fmp4&ns=di_2S6232lKYAKOWWlNOO4QL&gir=yes&clen=11770799&dur=727.106&lmt=1588020158701604&mt=1676176387&fvip=1&keepalive=yes&fexp=24007246&c=WEB&txp=5531432&n=Zz4VM0TNTGvJy3&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJlkGdvFvNlrGPHwnnixIqbbVgfDvIKMtemlDkKxsh3AAiEAkfMybN1vGB0CwPNtwPnI-2TfwMHbtNOpCiGIcTCFdzU%3D&sig=AOq0QJ8wRQIhAPoNmgFLJGQXKLngfacCQj0cvS-vee6nSBd-dIntqyi2AiBrMJGm4eUHxoXUIrNaLzWELUq-uGtcZLsFe0UgZ57Vbw%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Device Info (please complete the following information):**
 - Device:   pixel 6
 - OS:   Android 13
 - Version: latest
 - Country: U.S.

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
