### ISSUE TITLE
[BUG] : stream was reset: INTERNAL_ERROR - Can't download song from album

### ISSUE THREAD

**Issue by Lokotursta** [Shabinder/SpotiFlyer#2355]
**Describe the bug:**
Unable to download "I Always Wanna Die (Sometimes)" by The 1975 while downloading full album. Doesn't download either if I try to download that song in particular. Throws error.

**Media Links Used:** 
https://open.spotify.com/album/6PWXKiakqhI17mTYM4y6oY?si=UjAS8Y4FTIaxYmPkVJooTg&utm_source=copy-link

**Expected behavior**
I expect for each song in the album to be downloaded completely without issue.

**Screenshots:**
![Screenshot_2023-02-13-02-13-01-251_com shabinder spotiflyer](https://user-images.githubusercontent.com/102843078/218377478-cf28ab96-cd43-4789-bea7-d5619f7594d7.jpg)
![Screenshot_2023-02-13-02-12-58-202_com shabinder spotiflyer](https://user-images.githubusercontent.com/102843078/218377497-cdd7be42-255a-4f36-a27f-e51f96b70dc4.jpg)

**StackTrace:**

```
java.lang.Exception: stream was reset: INTERNAL_ERROR
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)
```

**Device Info (please complete the following information):**
 - Device:   Poco M3 Pro 5G
 - OS:   Android 12
 - Version:   MIUI Global 13.0.4
 - Country: Chile

**Additional context:**
Tried downloading the song by uploading the youtube link and not the spotify link. Didn't seem to work either.
Also, not really relevant to the issue, I downloaded an other full album perfectly before the problem showed up.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
