### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Endeavourking** [Shabinder/SpotiFlyer#237]
java.lang.Exception: Request timeout has expired [url=https://hostquick.onlineconverter.com/file/20edb2748edd1b58ff37ce4c90353dda62/download, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:12)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at com.shabinder.common.di.DirKt$downloadFile$2.invokeSuspend(Dir.kt:37)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Probably Internet Connection Slow or Converter was unreachable try again it should work
