### ISSUE TITLE
[BUG] : Maybe Song Specific Problems

### ISSUE THREAD

**Issue by CK90GH** [Shabinder/SpotiFlyer#2379]
**Describe the bug:**
Bug prevents certain songs from downloading 

**Media Links Used:** 
https://open.spotify.com/track/3jagGO7eHHuaD53ibehkux?si=nn0GQCL6QhS7mSLxQ0C0nQ
**Expected behavior**
To Download 
**Screenshots:**

**StackTrace:**
```
java.lang.Exception: stream was reset: INTERNAL_ERROR
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

```

**Device Info (please complete the following information):**
 - Device:   Oppo A12
 - OS:   Android 9
 - Version:   Unknown 
 - Country: Philippines 

**Additional context:**
Pretty sure its specific to certain songs and possibly has nothing to do with device or location 
List of songs that failed to download:
Ode to sleep - Twenty one pilots 
Fairly local - Twenty one pilots 
Blood and thunder - Mastodon 
Cut my lip - Twenty one pilots 
Lemon tree - Fool's Garden

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
