### ISSUE TITLE
Problem downloading specific song multiple times

### ISSUE THREAD

**Issue by MiniMizer1** [Shabinder/SpotiFlyer#2423]
Error code pasted: 

java.lang.Exception: Request timeout has expired [url=https://rr1---sn-bvvbax4pcxg-50nl.googlevideo.com/videoplayback?expire=1677893421&ei=zUoCZJeBKsitlu8Py8aD6AQ&ip=136.62.0.208&id=o-AJTjZmY0hGwC8saXrUJ2-pSs3VL5RovLSsyh00vFu5Kg&itag=140&source=youtube&requiressl=yes&mh=e7&mm=31%2C29&mn=sn-bvvbax4pcxg-50nl%2Csn-q4fl6nsy&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=20&gcr=us&initcwndbps=1362500&vprv=1&mime=audio%2Fmp4&ns=SiJVjIdkDpHPD69DPuiyKSYL&gir=yes&clen=11713086&dur=723.573&lmt=1580374132273466&mt=1677871503&fvip=3&keepalive=yes&fexp=24007246&c=WEB&txp=5531432&n=jHLkkrKhgSlLNhM&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKAP6r5XWZvynilfET5jW2db4aw1Nw8uIw6q8BnC655UAiEA_ScQFkPDm2MVOSaE7GQRhgCKNdnXGOu21MCvoQ5-Hy8%3D&sig=AOq0QJ8wRAIgHzjUShGLtto-KOUOokgsKkBPJp0OpRxUyw9SFZ3jEM4CIAeAz2OQWOsNm8-v5VMKUF6YR_3tpBH3oYn-81HgeYC1, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
