### ISSUE TITLE
[BUG] : <Error Downloading Any Song>

### ISSUE THREAD

**Issue by GeorgeSakketos** [Shabinder/SpotiFlyer#2433]
**Describe the bug:**
Trying to download any song from YouTube, YouTube Music, Spotify etc. ends up giving the same error,  this also happens on another phone i tried downloading the same song. For more context the phones i tried downloading songs on are a Xiaomi Redmi Note 10 Pro (My phone) and a Samsung Galaxy A3 (An older phone) both had the app on the latest version.

**Media Links Used:** 
 - https://music.youtube.com/watch?v=7pOFG7lw1r0&feature=share

- https://music.youtube.com/watch?v=YL5VIiyTVso&feature=share

- https://music.youtube.com/watch?v=rMOHocI5siI&feature=share

- https://open.spotify.com/track/2nkoWsTZa8LKPNGdjI5uxj?si=DMakWqUeRXqlKvV3j4U6Pg&utm_source=copy-link

**Expected behavior**
I expected all of the songs mentioned above to be successfully downloaded with there Covers and everything and to be playable. 

**Screenshots:**
![Screenshot_2023-03-05-14-10-05-843_com.shabinder.spotiflyer.jpg](https://user-images.githubusercontent.com/79644911/222959651-2f6831d1-b94e-49ee-9400-a128e8d7d299.jpg)

![Screenshot_2023-03-05-14-09-55-522_com.shabinder.spotiflyer.jpg](https://user-images.githubusercontent.com/79644911/222959662-0a05eafd-bf16-4f5b-beab-a8e037f2c038.jpg)

![Screenshot_2023-03-05-14-09-45-509_com.shabinder.spotiflyer.jpg](https://user-images.githubusercontent.com/79644911/222959666-dc920a97-eb5f-4cfd-9363-f65b9afc2a7b.jpg)

![Screenshot_2023-03-05-14-09-34-035_com.shabinder.spotiflyer.jpg](https://user-images.githubusercontent.com/79644911/222959668-d20401cf-a916-4545-8b21-898155c49fdb.jpg)

**StackTrace:**
```
java.lang.Exception: off=0, len=4088 out of bounds (size=0)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

```

**Device Info (please complete the following information):**
 - Device:   Xiaomi Redmi Note 10 Pro
 - OS:   Android 13
 - Version:   13 TKQ1.221013.002
 - Country: Greece

**Additional context:**

**Comment by GeorgeSakketos** [comment]
Side note, if i use a vpn it works.

**Comment by Frimac07** [comment]
> Side note, if i use a vpn it works. 

I didn't know that, thx for telling.

**Comment by elfacki20** [comment]
With VPN work thx again

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
