### ISSUE TITLE
[BUG] : Download failing

### ISSUE THREAD

**Issue by AdrianWazHere** [Shabinder/SpotiFlyer#2459]
![Screenshot_20230310-211625](https://user-images.githubusercontent.com/91392118/224420083-2acf9da2-42b0-484b-822d-3452e99bb1c3.jpg)

I opened the app to download some songs from spotify and i clicked the download button on all the songs to download them but the downloads failed. I reinstalled the app and tried again. But it failed again.

Song i tried to download:
https://open.spotify.com/track/3IPGG5Niex4hGlXFOYWzp9?si=0xJqxG6UQBSLh7SGcf6QAQ&utm_source=copy-link
https://open.spotify.com/track/5e1SWZlh4fcOA1t2QB5QXG?si=FkJ38HDaS2ibVuy5rYB-Zw&utm_source=copy-link
https://open.spotify.com/track/2sLEtGlGvLB4ydp97Q5Mcw?si=T0JkCzSIRGyMi6PW-8jtLA&utm_source=copy-link
https://open.spotify.com/track/1vux5TJpXtc7tbjA1YODpp?si=lkGrqKiiTauE1xtG8rdzlQ&utm_source=copy-link
https://open.spotify.com/track/7fEoXCZTZFosUFvFQg1BmW?si=5XE5pVyNRYW423WDODybLw&utm_source=copy-link

The code:
java.lang.Exception: off=0, len=4088 out of bounds (size=0)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by ericsomto** [comment]
You exceeded the download limit 
Send a token to the developer as an appreciation for the ones you downloaded

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
