### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by malteser0** [Shabinder/SpotiFlyer#2485]
**Describe the bug:**
tried to download an album from Spotify but the songs didn't download 

**Media Links Used:** 
https://open.spotify.com/album/0Dt3FbpMQwjoT5KNAw0IXR?si=MuRraJgCRe-N8TMEuDPkNA

**Expected behavior**
expected the songs to be downloaded

**Screenshots:**
![Screenshot_20230314-001632](https://user-images.githubusercontent.com/127800744/224853103-14e83398-e8fe-4964-97d6-2dfe722917e7.jpg)
![Screenshot_20230314-001642](https://user-images.githubusercontent.com/127800744/224853107-e97e9b77-ae13-44f5-b7bb-a0c0192302c3.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```not sure if this is the stack trace

java.lang.Exception: off=0, len=4088 out of bounds (size=0)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)


**Device Info (please complete the following information):**
 - Device:   [Samsung A50s]
 - OS:   [Android
 - Version:   [latest version bcos i tried redownloading the app]
 - Country: [malta]

**Additional context:**
<!--- Add any other context about the problem here. --->

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
