### ISSUE TITLE
No working link. Need help

### ISSUE THREAD

**Issue by Argee74** [Shabinder/SpotiFlyer#2505]
java.lang.Exception: off=0, len=4088 out of bounds (size=0)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

	READ THIS!
	If some Song Download Failed with StackTrace having any of the following reason:
		- DownloadLinkFetchFailed(trackName=For Those About to Race, jioSaavnError=java.util.NoSuchElementException: Collection is empty., ytMusicError=MP3ConversionFailed(extraInfo=Client request invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY !
			- Please Dont Open issue! , Online Converter Was Busy! , try again after some time and download will be successfull . 
-->

**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

**Comment by Argee74** [comment]
![Screenshot_20230317_005740](https://user-images.githubusercontent.com/127552587/225777969-5896b88f-6dd8-43b0-ba25-7ab55d3ed7f0.jpg)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
