### ISSUE TITLE
[BUG] : Don't download a audiobook of Youtube Music 

### ISSUE THREAD

**Issue by iamalvarotab** [Shabinder/SpotiFlyer#2512]
java.lang.Exception: Request timeout has expired [url=https://rr1---sn-8vq54voxn25po-h5qk.googlevideo.com/videoplayback?expire=1679103379&ei=M8EUZO-UFKuQxN8PlNe2mAs&ip=79.109.76.105&id=o-APx6U_YluxBxAw3e0R9dS9HZcuhENCvJ4-624CCoO3JG&itag=140&source=youtube&requiressl=yes&mh=tQ&mm=31%2C29&mn=sn-8vq54voxn25po-h5qk%2Csn-h5q7knez&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=1307500&vprv=1&mime=audio%2Fmp4&ns=vapiGv2-43choUxcSdHrSykL&gir=yes&clen=378647314&dur=23396.518&lmt=1543463345896397&mt=1679081335&fvip=4&keepalive=yes&fexp=24007246&c=WEB&txp=5533432&n=TAI5MWmWigcSsU&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPVQn0Sfuk28-SYw2jbtCdNQDVDxPg5AbaxG1TpKTf-3AiAdPn3yms30HQurJhvKK7YfYMfhh8OVCZ836oVp-bjUtQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgdOUODfq4cMS537bzSdkpz6_7-BXIwBzOIMfMZG3kT4MCIQDgJvbewLVj6S8I1AKbUAjyWlGe3QPRFhfohn2RrX1kJA%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
