### ISSUE TITLE
macos version dosent launch on m1 mac

### ISSUE THREAD

**Issue by Reaster0** [Shabinder/SpotiFlyer#252]
when i launch the macos version (using java so) the app crash instantly before even opening a window

i'm running macos big sur 11.4 on a m1 mac and using java 8 v291

great job btw i've tested the app on other system, i'm older than you and i'm not able to code an app like that yet haha

**Comment by Shabinder** [comment]
> great job btw i've tested the app on other system

Thanks

>i'm older than you and i'm not able to code an app like that yet haha

That actually doesn't mean/show anything... even you can do program apps like these actually these arent that complex , if you are interested to learn and while going through source code if you wanna ask something, ping me up... will be glad to help :smile: 

> i'm running macos big sur 11.4 on a m1 mac and using java 8 v291

Can you kindly share **crashlog** when you try to open the `jar` from **console**

**Comment by Reaster0** [comment]
this is what you want? 
it says that my version of java is not up to date buuut i made the installation yesterday '^'

Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedClassVersionError: org/jetbrains/skiko/GraphicsApi has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6224)
	at java.awt.Component.access$500(Component.java:186)
	at java.awt.Component$3.run(Component.java:6178)
	at java.awt.Component$3.run(Component.java:6176)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Component.checkCoalescing(Component.java:6175)
	at java.awt.Component.<init>(Component.java:6144)
	at java.awt.Container.<init>(Container.java:285)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.desktop.kt:33)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt:116)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.desktop.kt)
	at androidx.compose.desktop.AppWindow_desktopKt$Window$1.run(AppWindow.desktop.kt:85)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Shabinder** [comment]
> java.lang.UnsupportedClassVersionError: org/jetbrains/skiko/GraphicsApi has been compiled by a more recent version of the Java Runtime (class file version **55.0)**, this version of the Java Runtime only recognizes class file versions up to **52.0**

**52 = Java 8**
53 = Java 9
54 = Java 10
**55 = Java 11**
56 = Java 12
57 = Java 13

you have java 8 installed and in your path , install **java 11** and confirm later by using `java --version` and then app will work fine

**Comment by Reaster0** [comment]
thanks for your kind answers, since oracle don't seems to propose "java" in version later than 8 on mac, i've downloaded java se runtime 16 and since that the app work great thanks!

**Comment by erj14** [comment]
I'm having the same problem and I'm running Java 19 but I do have java 8 downloaded would that be the problem.
