### ISSUE TITLE
DownloadLinkFetchFailed 

### ISSUE THREAD

**Issue by Sonickai** [Shabinder/SpotiFlyer#2524]
DownloadLinkFetchFailed(errorTrace=Find Link for Connect To Consume 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Connect To Consume)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:44)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(JioSaavnRequests.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Yt1sMp3 Failed for NE3rTIIgEpc:io.ktor.client.features.ClientRequestException: Client request(https://yt1s.com/api/ajaxSearch/index) invalid: 403 Forbidden. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico" alt="Icon for yt1s.com"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            yt1s.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7aa844a81e835319')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            yt1s.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=WTD3qVcDlHMtOq.SIOext3.ubquzezhj4Jt649Mp1DE-1679255676-0-gaNycGzNCPs" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="SErUJYMf1LI5HgaU2A.1J6myV8W_jTvJMRL8Tsz.Ua0-1679255676-0-AX_j00zlS4oxxab2ervakCT_elWRtZyuoBuV10o3kqrsK8KeMqGN-_ack6qbIW-EBrMx8lCBFCCoIFwB98d7vIBe9TG5c2-o1ibf0aosIBO0wjZNdyArd-WH6dugNd3D5_fINHMWrdhhO5edCwVkhNKhs5fKnePPnlzEWsasDvaJM5wdfVaVXb2rEHwFS-xQTH9soGJ2kEW7iqRz_ur_xQPGWTXZLOqkcYvkswd_xY77h_uqE39MRhHHevK0r1rDWpjOPSfGaA0Z7JovNBWLh1QOFQYcYvcgNFZm1Vy1cWhZ0yvaSMcy9QvPP4inRaS3SNOuW2z4dqstIuDJvmCV1b4h-6qDTx_hgPWwmfmN1up-tNEHknOx9P4V-LmnML03d8EF8bANL9gGi47sHBK-qz5qbXw7soJPKqv7l1Qzrxfa_jKMZaVrNg2N4Iixa8u1OhSXStQDYxDWYbWIEWkhFk9n_N4uibkp46BSIFgaRLlOF_31AJFnoSP3exz-FI5D0zOJU20oDtMO884AYLhenYW0wZ_Doz7PqIkVRHK6ubKeck02Q9vX6szqwwdOeDTVW_txos15w0ZoFF-XeeRgPX9SQ11lbTEDXu_jrJxMQgSwd2MBW67I__zVa7vR1iVqn_oZcf43b_MJG_MkUjfL_-LHM9CET6-7AAjrn3SSA5FH9K7U2sD4RCEgO2neAzu-32AcfXimS1DGzPcW0C-e87C5vF5jlJbKF-ZVYelOuTv1MpVUrxaaO8vfbxrHagRdJlkYx0yVE5UWDJeiwdQKQ_SY0MeosTOtAIMmNorNVjKpJTPKrfn1IUhB2_6xz41zlyGHfe_wcCVxTQ8tt2MgidD4S9AHQnGTMINdIP7pobyouIfqxCr2zZwa2FoUqbcuwPcGae1WZKzWPOx3tdHH7gFmMi_8Rhvc9QK_4G36vPvns7iq2G8gkORymc9qlXopPeEZdXrGGk8GJJXbvSQe5A88tjZ0kZ0kdYx80vlCRIPWotxfSoRP3vaj39BlNHcqf_AvHKsd3rNl5S85KTkRlii5_fB_QgeLWVFp6UZHHO-mIWNZIMvFK5uW1OLfT0TK7Q7oiJxxTLgVwWL8Rc7HhuQd2zt5aAQOiLlYbRcluDDRTqncC1q8FSOR38XseA-XyTmPqtz4oxrCZI0HTvqg97wbCAF4XlrFKV1GbHOdvGZaZqiUAsPWYH5vpFHnO4k3_9Cjm0aBM8SWFtgTafx9lIl35mULnmwdY83AOKokfuhiZ88Ifa97wOwUCzlukxX6YSrQiVydMHbl9MlgbmAcdRW-bsVYfIiRhkPhjZ91qigTS_rzmgj_KRB6-f8V-fjBUEDkxM6KdV7D7s86QOBNWr8CXMzgyYColCBtnuMVuLOO4vPZsru0CLif8nRx8tU7Cz9U-Qqs90VQGQZ4ghqYQBy_V6B4vIyqh4Vb6SBMw-ywpto_4NNiQzJcfYNrXR4-s4AXIMixVjzeDkJX00s_2rt-QlTlRWS51FKlWtgS-ZL-4i646j10hjLEzObXH4luZX2ezJ7W3TYHf5z6d5xdk6dD7slKM2Njfg6rbb6iTtj91tF5NDrKgUwD8vTZgnhuYpl7kY6cBNP6z-vvjE7jzNCbY2IhD1jQ12VyNdBFXGzaOnUlth_9iSx_ZYWQ64X_KA5kGWqAAYLww3_413iHcWlh51AUMuoGc7xZOse2tWYNcy3vahQoX9FFYIGSncTT-Aw3u9rRH5Gf6jqtwJS1FMXt_VNobRxjyX-1MZASHY-zXqKsyRkmIThfC4Pjmy6zTgNPn3eLNhOHwfdb0C1DFTaqo4K8FMACQgDlahgRkOKE-52rRBu9HnQqfaerojC0WyoQEaf2_ehEVgSEVbFQdBrf6dWOlSb_6EjVTGwjeNI7khK3RI38OeAjetOyzZ-TgRfAAOCKR3EcDCZmUABwAJMC-kHSqrfplcH3WsFwTMLHU3kiVNuJDsjGegyBVFXvpcgFH5ASQnFzFse9JfrWhFXdP7o_MucgclhH-zdTyaIxefX2hBRa7CkL71dYJvIRMbe0VaoON2CLLYlQph0MxjPqczGoqTs0_nh6VKjCDcR1hMm_WGaCtj5uHPNpU54gVZHEF0JubxdfS-BjTlPTYFv_pkiXbWkZpTblmqu_qiD7tiEKlDlMSooOkQe5ULAkh4Aiq752jqkBd98uXAX4LjJwcUivHkn87w_1uES9ctW1q2f3-BTSBaEdNELkylXw3Q">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'yt1s.com',
            cType: 'non-interactive',
            cNounce: '85925',
            cRay: '7aa844a81e835319',
            cHash: 'c326a797c240254',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=WTD3qVcDlHMtOq.SIOext3.ubquzezhj4Jt649Mp1DE-1679255676-0-gaNycGzNCPs",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '60000',
            cTplV: 4,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'OXZ3a5lJBLl5NfUYYWcrxmmdSvesW59hU0qFWE8AX6fR+KzIsX9blG5HP/oEhNDBe3ZTorg+5OqN37hmEyazlNw7srIlD3zI+xWKS+GtVNfT+eqG5j78HwIh5G+Yg8zzmCeJrT6LF+169KYpFLngFsrGHqggNJr2bkdMW0kQAZ06sJ2QdeBarWAYtN9jHLwAQtzB1Y2l9PodGY6r7g9v7PVhfA983sspGkWvzPoFjU/d3GRxy7QVwqpydBYQqGm1atlyb3wNyUu0f1l3SZa3ATZ1NacM5Bua8MVR4FPlP0z7wdXkpPXb342OoLfsKrEyj8trgYHvk5VQVOkkCOn0oYY16P9yUbbL9GBTvKbhfkYWlz6OV3wBPyk/BI4pWB5Bp8+Hp7yXb2UD2c+Hq8VOw9TTSPgUCCt9oCiSXYfRlzDH4TZgwvNLcd8wn630c5Kmn8fyDqSIVRxUhsAgz34mGWXnYqQNImE5743JCUeEPwLUsNBUE1xoO3Sybk0IMhWO8MMPdgfNAkSep/18eEkttkrqj6YPHfO+IhejftGi1ObMC1E2S83MFJNPpIFpAC0vpbNawZNG1P0A0QMvtM3a9+mGc6eHNTIvsqa143TaBXaAJIFxzAMFdiAM/Q5GBVxorKXbnCGNFXidfGbdiUFz7bK6coOKqFwAT3/AyK3GniLXjBG0H+NE9CxqMem56wFzJZwPpdqqFemFO1M3EPWHhA==',
                t: 'MTY3OTI1NTY3Ni4xNzcwMDA=',
                m: 'I/81yDT5po+wRIw4vmsOe52tSz1djXWOME8gbn/ftmE=',
                i1: '4q7x2VP1vJxg2fNT9BRPQg==',
                i2: 'Ia3I9izz+x2DaM3n9BevWA==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7aa844a81e835319');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=7aa844a81e835319';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=WTD3qVcDlHMtOq.SIOext3.ubquzezhj4Jt649Mp1DE-1679255676-0-gaNycGzNCPs" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>7aa844a81e835319</code></div>
            </div>
            <div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=j" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr3---sn-a5mekn6s.googlevideo.com/videoplayback?expire=1679277276&ei=fGgXZLG6J8OTkwaB5IjQAw&ip=2a0d%3A5600%3A46%3A5001%3A0%3A0%3A0%3A2074&id=o-AFN7Q1By26oZ3ITzM65ctR6jIVosIBuxziA_LJ2CXGnF&itag=140&source=youtube&requiressl=yes&mh=iN&mm=31%2C26&mn=sn-a5mekn6s%2Csn-o097znzr&ms=au%2Conr&mv=m&mvi=3&pl=62&gcr=us&initcwndbps=593750&vprv=1&mime=audio%2Fmp4&ns=-jNYBUGpHEuV-scsEscObJcL&gir=yes&clen=3155648&dur=194.825&lmt=1669597530426169&mt=1679255376&fvip=5&keepalive=yes&fexp=24007246&c=WEB&txp=2318224&n=vXwyRo7A7F-ovx&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOrr3pio5R5avXKmkwbLdDH0M5D7kAWr950_cFrCcgQcAiA8_KBX561DWidBHdo1hPRvbgjkmPVp2gxw17gGWC0rsg%3D%3D&sig=AOq0QJ8wRQIhAP8VjuFYVF0yjsG4IyhFlfrL12fpNcelcl_Jq4WFQE5jAiBiURWsyCaM5J8ExSrlSS7a4FBWuy0Ez8CDERdJbgdIJg%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:33)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:133)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr3---sn-a5mekn6s.googlevideo.com/videoplayback?expire=1679277276&ei=fGgXZLG6J8OTkwaB5IjQAw&ip=2a0d%3A5600%3A46%3A5001%3A0%3A0%3A0%3A2074&id=o-AFN7Q1By26oZ3ITzM65ctR6jIVosIBuxziA_LJ2CXGnF&itag=140&source=youtube&requiressl=yes&mh=iN&mm=31%2C26&mn=sn-a5mekn6s%2Csn-o097znzr&ms=au%2Conr&mv=m&mvi=3&pl=62&gcr=us&initcwndbps=593750&vprv=1&mime=audio%2Fmp4&ns=-jNYBUGpHEuV-scsEscObJcL&gir=yes&clen=3155648&dur=194.825&lmt=1669597530426169&mt=1679255376&fvip=5&keepalive=yes&fexp=24007246&c=WEB&txp=2318224&n=vXwyRo7A7F-ovx&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAOrr3pio5R5avXKmkwbLdDH0M5D7kAWr950_cFrCcgQcAiA8_KBX561DWidBHdo1hPRvbgjkmPVp2gxw17gGWC0rsg%3D%3D&sig=AOq0QJ8wRQIhAP8VjuFYVF0yjsG4IyhFlfrL12fpNcelcl_Jq4WFQE5jAiBiURWsyCaM5J8ExSrlSS7a4FBWuy0Ez8CDERdJbgdIJg%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:33)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:133)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
