### ISSUE TITLE
[BUG] : <Issue_Title> An issue with downloading

### ISSUE THREAD

**Issue by Kndziuu** [Shabinder/SpotiFlyer#2605]
**Describe the bug:**

I get this pop-up, when I'm trying to download the song
**Media Links Used:** 

https://youtu.be/DwPWGUhEtP0
**Expected behavior**

To download it
**Screenshots:**

![Screenshot_2023-04-06-21-03-14-220_com shabinder spotiflyer](https://user-images.githubusercontent.com/130086523/230471937-1eaa06ba-9e26-4299-bddd-4e0801d302bb.jpg)
![Screenshot_2023-04-06-21-03-09-387_com shabinder spotiflyer](https://user-images.githubusercontent.com/130086523/230471970-454e108a-bcde-4f95-97e0-aa742726e2e6.jpg)
![Screenshot_2023-04-06-21-03-06-728_com shabinder spotiflyer](https://user-images.githubusercontent.com/130086523/230472003-21c912a6-548e-4936-97f6-f86b0d493c39.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```
java.lang.Exception: off=0, len=4088 out of bounds (size=0)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Device Info (please complete the following information):**
 - Device: Redmi Note 11s
 - OS: Miui 13 and Android 11
 - Version: Miui 13.0.9
 - Country: Poland

**Additional context:**

I don't know why it stopped working, because it worked before.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
