### ISSUE TITLE
[BUG] : <unable to download>

### ISSUE THREAD

**Issue by solofireflyxdev** [Shabinder/SpotiFlyer#2628]
**Describe the bug:**

**Media Links Used:** 

https://youtube.com/playlist?list=PLjvdOjAAIeitN8qH28JvOHDBEqFVkQ2lt
**Expected behavior**

Parental warning Explicit lyrics!
**Screenshots:**

![Screenshot_20230412_101711_com.shabinder.spotiflyer.jpg](https://user-images.githubusercontent.com/107917094/231396254-93fcbaa6-4360-49f7-ac90-2a67a89ae330.jpg)

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (JNY-LX1 /JNY-L21):**
 - Device:   [Huawei P40 lite]
 - OS:   [Android 10 - Q]
 - Version:   [3.6.3]
 - Country: [sweden]

**Additional context:**

java.lang.Exception: off=0, len=4088 out of bounds (size=0)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Comment by solofireflyxdev** [comment]
> Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
>  - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
>  - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

Thanks for your help and services
