### ISSUE TITLE
Not downloading 

### ISSUE THREAD

**Issue by TRJK** [Shabinder/SpotiFlyer#2687]
java.lang.Exception: Client request(https://aac.saavncdn.com/635/MWlL3vChVSJZOQ2zBX0gZ4zxX9pUtaoQthX5H_320.mp4) invalid: 404 Not Found. Text: "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:776aa2e1-c01e-0010-0bfa-70f814000000
Time:2023-04-17T07:01:36.1645019Z</Message></Error>"
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.

**Comment by TRJK** [comment]
null' Error' Error:
 Message: No Match Found for query: No Query Result Found for QueryParams(trackName=Nenjukkul Peidhidum, trackArtists=[Harris Jayaraj, Hariharan, Devan Ekambaram, VV Prassanna], trackDurationSec=369, genre=[], year=1970, albumName=Vaaranam Aayiram (Original Motion Picture Soundtrack), albumArtists=[Harris Jayaraj], trackLink=https://open.spotify.com/track/4vlMdXsRpAIXYggwbNHZSv) from this source: null
Cause: Unknown Cause
StackTrace: 
```java.lang.Exception: No Match Found for query: No Query Result Found for QueryParams(trackName=Nenjukkul Peidhidum, trackArtists=[Harris Jayaraj, Hariharan, Devan Ekambaram, VV Prassanna], trackDurationSec=369, genre=[], year=1970, albumName=Vaaranam Aayiram (Original Motion Picture Soundtrack), albumArtists=[Harris Jayaraj], trackLink=https://open.spotify.com/track/4vlMdXsRpAIXYggwbNHZSv) from this source: null
	at ba.j.D(SourceFile:27)
	at ba.j.E(Unknown Source:18)
	at db.j.invokeSuspend(SourceFile:276)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:84)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
```

**Comment by TRJK** [comment]
Got this in soundbound

**Comment by Shabinder** [comment]
Install all the providers as shown in https://soundbound.shabinder.in/install

And then test

**Comment by Shabinder** [comment]
Its working for me 
![Uploading Screenshot_20230520-185210.png…]()

**Comment by Shabinder** [comment]
Its working for me
![Screenshot_20230520-185210](https://github.com/Shabinder/SpotiFlyer/assets/44765050/afaa757e-df77-4234-9fe0-41503bb46f2d)

**Comment by TRJK** [comment]
Playlist ( " https://open.spotify.com/playlist/5Gp9yEIjvSR1GQWziJwRiJ?si=RGKwj9vpT76FR2_8o8S_mA&utm_source=copy-link ")
Can't download songs from this playlist even if i open the playlist and scroll down app gets closed
