### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Manchesterisred10** [Shabinder/SpotiFlyer#2703]
java.lang.exception: client request(https://aac.saavncdn.com/030/fypo9enwjuklqmagc6bom82fiqllmx0dzo0pxa_320.mp4) invalid: 404 not found. text: "﻿<?xml version="1.0" encoding="utf-8"?><error><code>blobnotfound</code><message>the specified blob does not exist.
requestid:6e22b9e2-901e-006f-67bb-71378f000000
time:2023-04-18t06:06:53.9355889z</message></error>"
	at com.shabinder.spotiflyer.service.foregroundservice$enqueuedownload$2.emit(foregroundservice.kt:6)
	at com.shabinder.spotiflyer.service.foregroundservice$enqueuedownload$2.emit(foregroundservice.kt:1)
	at com.shabinder.common.core_components.file_manager.filemanagerkt$downloadfile$4.invokesuspend(filemanager.kt:54)
	at com.shabinder.common.core_components.file_manager.filemanagerkt$downloadfile$4.invoke(unknown source:11)
	at com.shabinder.common.core_components.file_manager.filemanagerkt$downloadfile$4.invoke(unknown source:6)
	at kotlinx.coroutines.flow.flowkt__errorskt$catch$$inlined$unsafeflow$1.collect(safecollector.common.kt:94)
	at kotlinx.coroutines.flow.flowkt__errorskt$catch$$inlined$unsafeflow$1$1.invokesuspend(unknown source:12)
	at h7.a.resumewith(continuationimpl.kt:10)
	at io.ktor.util.pipeline.suspendfunctiongun.resumerootwith(suspendfunctiongun.kt:74)
	at io.ktor.util.pipeline.suspendfunctiongun.access$resumerootwith(suspendfunctiongun.kt:0)
	at io.ktor.util.pipeline.suspendfunctiongun$continuation$1.resumewith(suspendfunctiongun.kt:17)
	at h7.a.resumewith(continuationimpl.kt:33)
	at io.ktor.util.pipeline.suspendfunctiongun.resumerootwith(suspendfunctiongun.kt:74)
	at io.ktor.util.pipeline.suspendfunctiongun.access$resumerootwith(suspendfunctiongun.kt:0)
	at io.ktor.util.pipeline.suspendfunctiongun$continuation$1.resumewith(suspendfunctiongun.kt:17)
	at h7.a.resumewith(continuationimpl.kt:33)
	at io.ktor.util.pipeline.suspendfunctiongun.resumerootwith(suspendfunctiongun.kt:74)
	at io.ktor.util.pipeline.suspendfunctiongun.access$resumerootwith(suspendfunctiongun.kt:0)
	at io.ktor.util.pipeline.suspendfunctiongun$continuation$1.resumewith(suspendfunctiongun.kt:17)
	at h7.a.resumewith(continuationimpl.kt:33)
	at kotlinx.coroutines.dispatchedtask.run(dispatchedtask.kt:100)
	at kotlinx.coroutines.internal.limiteddispatcher.run(limiteddispatcher.kt:12)
	at kotlinx.coroutines.scheduling.taskimpl.run(tasks.kt:2)
	at kotlinx.coroutines.scheduling.coroutinescheduler.runsafely(coroutinescheduler.kt:0)
	at kotlinx.coroutines.scheduling.coroutinescheduler$worker.executetask(coroutinescheduler.kt:14)
	at kotlinx.coroutines.scheduling.coroutinescheduler$worker.runworker(coroutinescheduler.kt:28)
	at kotlinx.coroutines.scheduling.coroutinescheduler$worker.run(coroutinescheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
