### ISSUE TITLE
[BUG] : <Songs Failing to Download>

### ISSUE THREAD

**Issue by Im-tan** [Shabinder/SpotiFlyer#2709]
**Describe the bug:**
So whenever I try to download my spotify playlist, it comes up with this super long error on all of the songs: DownloadLinkFetchFailed(errorTrace=Find Link for Wet Hands 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Wet Hands)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:44)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(JioSaavnRequests.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Yt1sMp3 Failed for w_vk7UwFBhc:io.ktor.client.features.ClientRequestException: Client request(https://yt1s.com/api/ajaxSearch/index) invalid: 403 Forbidden. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7b9d895539c58895')"></div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=AWkTvAH0BYJK7OBGvDixszISw4NRduWhPJMm3RIgTrU-1681827500-0-gaNycGzNCrs" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="pkLwjKLKwLHifXLPf9BvY1JKg185.qUF3b8Z2lNotM8-1681827500-0-AVetS-EaakRLspzC1DDKD8AOlau9mRaDxwj4-_njHOLkm4Mnl74Z_-DCxv3_kJrOFEf0v_dvWEhrzvQViCu7pG5Uq0vIO5_JDj0KAOgsbm0-X1fWyiW-q2Y45qX3oKKiAivwieVKsD7rdt7TWXkOglWP5M6fnC5zm38R6288qAF0XaOP9IVrUQw1vsZlLl-fIRRkra7h69dXfaVISrq9CC1cvdVzDvx-ABisTjLkteApMKAmeBs7H-AEqIkGHC4An1f-8vQfO-6YqAIlkSVZGEjBZGQnXtJMVbpZa72vGSdEoi2Cvk3gfNaz5Ywxx7CwNomXqXGb8ULfttQ2lSOZNM2H6nOKwkL39rNpNtQbD7XjACxfTupBNZIsrzPYIws2iZXxfo2Z7SqR-h6L6GFCt_XaE4YTTQ5DW0PeviG6clrry4pM1UOLbyrdpG3q1UKKpZpBVX0ACjIUB1xjcGm-ak-ngbkzfAxfD_cuznI2Vn1dVXwyATvoZQx-8Mjir7vxkp7IzMxVi3b7BV9Z-jlmqBqt0cEbIytYrVPANtw6H3aMqTTBR8mGMlmjkr4PfWnO4fX7seoEs8mM0nW5ztD8VNkTTtSn9bpXMzV3D0LwUa1Lpv1KktfB-7g1tBYJwqJe4gItcKpgUiY8ULDmvDA4bBkdAGbYcxToKGE9gXOCbKFotWMlheivkhLJTiwnBm9xhztXZAv6BFR9xN-0NqF0YjHy3UCt-irpTOO6KUSZE1_i1K_M62AOaL0YNG6BTz1RcpMAZGOVHXpxBiBVX-cRRZisgD11i6LWEemLSVLfQgxipulj3do3FnCh5ovJLfzPfV85YV62FtxNefIHb61oHk9cxI8vXhSxmy_Q7vRaQNCz-ZzA58oKqgT27930rdRsKqW8ME6Iy7c2Kgu_2A0iVSv7KYDOU5uuEqTUWqiIIvzfqqzbGKO4u-tLQsmg_yYMN3gZ4o942dq8DXHFzrPzRoem_ljJGE0fh6TcXnFooFQTpQoWpfxlSU_kugejzPpelHqU2L0T_0i3c8Yby4mtgyKH43EXpNtLGuQT7OgpjD1PoM8938Ypticbj4qOcP8_mCB4b81h2gaatMe8TAKYT43gAUofQoT1mZ_1h-PRhfe7hc_PeSON-cr33EiePprAWi_gtrdqKgpPiwkUkyZ0fmzZkatMb_qwGH7a9tckUWM0ObV2Ii5bCY1VmJ1j73IQtilaKyy8a7ZNPR4mt2y0FlhhLTSTI3DveSf4klOMKggsOVf9Cxr2EBlMskFdl5j6CVyrIgdpFTr-du6xhaXNHlB8sKKhA1LPzrWavIctYL2I58TEF9VbuBW_-Vz1pWqkN9W7znw18vonQ5GMDcl4_do2qnfCYpdSx-mZ6UYyHk9Grnmlf4DyzmRKm6Asm1pz0xbZMLfvEBoDSRYAp9N-fbSyR0j90HGZKQMzs466L-9FwCJh3B9kjKuuKswgM_mpP-96dz-DXkkE1G23wTsP-GR1LRH4KfRh84--XVI4zyWRhIZWEYoVJL7Ceu_W_NjuFoQ0lVrBd5K-TAUTpW3Nv2iSK11K4kheZztTWJ_bZ92DAVn0yvCpI0da5r9Y-ENbujyXQPFjSXFeCASkAvgsVXu9ldMPBS4jQM_2wtfKi6c0xI6CT-OkDLZRSEn5W951D1Q3x972RFi7SakludSUyoBZ5M0gm5pQH4wsXtrcUpPXNco7AlJZg4Jegz3pzWMNHh32epeWdAEHnHO-vNpTj3FKL3WyrDQyYxyl8koSPYkHeN0SJVFosLuDmYyIzW0-98IPC6WFG-fN1VYjKpkWWcXYls5GChWBwR-xCiM24j0IZTrLU7h1I-69za21chBtd-wGPNlqYP5BIn2QHZ3YgB29mJ5Y8TonesHPt7dK78EOEw-YguLD-EGAc2sUpOYt-BqYAJk9ehuDtFKGcGUERa_nQXWJOOEn43sccH9KOCUUGaYhL6JQ-tlsP9Oe5tc2T6Hn-hgndekvObZmeLcGIhbR1HVKkCKHPaZGpuO_uCWn_ZLHH1wQBRJLH7GV2tcSS-6O3jlND61rkTqOioQihPenIW1SjgI8Oawo3Ezc3OUC7r7FLH78kNKbPYU4ea1r649-N3nA1zW_lSJNDIfZTX-amRY33DExvU0eHRxMrkOxx5jGnAHb3dZOQwW2R7MiWy_DjBj4Uca7Y0Ml1l5ustCR-ejh6qRgdz55Vd7UM17oy04DcC2H6l88CRTZmeGV3YZkj0jKBfyerfUsRGpgHevyajTCtYb2TVWalCCwOfUuGUVD3to3ur92r0q5j1txd4ILdbXKB2b9M22vw-F-LJh6uwgh-kTPm7B2-Izxb8GNPisXvFOmCahYLKyQQpYOw4VeamutTx-LXC5bXaW7fAHTet5bcPqyTIgDklCNUymVE4J5188p6ThaRAFSUfIqcRx4ZZ2k7aTv5r3xse7v43XbWLkpN06f6gKO1SOk_KLhJlkMJ_HyocOeRYJB6_fDnr3j8vGqxz81dyH77_bmfrl30t8NUydNEKu4VeknZYGkpRUpmnxRQaBGb5deepnfxuLiAy_A_IAopMLkp9GQoJXcZXmOVmWoMjeVMLqRqxtC0yANgwznDqV6LUid6UzJMqak4JTudKXYxoyqkGhoAhPL1zwohYtssIHBA6g3Q5FimY9i2WNZfuVCQlONSuRiUw">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'yt1s.com',
            cType: 'non-interactive',
            cNounce: '92758',
            cRay: '7b9d895539c58895',
            cHash: '2ac23137282c890',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=AWkTvAH0BYJK7OBGvDixszISw4NRduWhPJMm3RIgTrU-1681827500-0-gaNycGzNCrs",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '60000',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'PUuUFejJ+/tkqv5stXI5chsPU6/f/bsui8DyS/2Gj+UZHyY2UZKcqZpUjC9MK2VARrUrkxDWhbXsJ2dRS92QIPb7bM0gWu5xBqtwcfxwpf+LSABy9RZy+0RFtEYYS3+aXHoX2tLkL6xBC5/l5jld/WKWBYp5rY3LSpVvFHWIyS257zur1pNIcopwBg/99UhXKKIHSuPSbqbwR24o3JF7yChfXk25NLLPUArTpf9ok9dWuqtRMui+KI8lhKZX9MKWCXhmXowrw2YKuuWOlQ3gOXuT3XLZgTV1u3Z5q+MdpjNWNC7OEXXipOOdipGHvF90AGFzYGrBFUiVAJDAP1faTxoh0Ln3DaG4ozWGopiLjRGWUDEVZn7UOIisC+dfi9J6H8GpRK3UKdmEEu3ReDlrXUSRJ2uzYinA9lTgSmcpVortm5lk8qxPIQGLOD0xo+BXu1DdxeWnQd/KeBa4CUnQRyq8DVt8Ew3WE91b+Y7W/qfI8vFjvtZRoZw26IhfvYJ5nN/rNvlSZoOa40qoDQOVXbNKvhojTr8hIIcpLEJQ/5Auf7HoGzW+QY8Ib1xfi94uf0ajgjgrNCzX38sB9bEOSw==',
                t: 'MTY4MTgyNzUwMC4zNjYwMDA=',
                m: 'O6vYH9CE6FnUJb1YG0Sz94qeQt1lTBCQx/nC3xrOM24=',
                i1: '3i9x6Xh/K4A5I4bPTtL/jg==',
                i2: 'kqR+yXfcpVHAZAHVArrqng==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7b9d895539c58895');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=7b9d895539c58895';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=AWkTvAH0BYJK7OBGvDixszISw4NRduWhPJMm3RIgTrU-1681827500-0-gaNycGzNCrs" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr4---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1681849100&ei=rKY-ZO-CH-WHp-oP3qCqiAY&ip=31.49.0.120&id=o-AOBAXxRmegEwMPzssvHlYGjhuZhOp4iSiLpIxZkkJxbw&itag=140&source=youtube&requiressl=yes&mh=4T&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9id&ms=au%2Crdu&mv=m&mvi=4&pl=25&gcr=gb&initcwndbps=2401250&vprv=1&mime=audio%2Fmp4&ns=jSuglrfu_EDAlJ30RB4wE9sM&gir=yes&clen=1111756&dur=68.499&lmt=1595274914714404&mt=1681826735&fvip=5&keepalive=yes&fexp=24007246&beids=24512778&c=WEB&txp=2311222&n=1yIQxDPx2-30BhjW7KI&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgd_NPD3JMx9acZB-KXk7cvDGbaf8CwV5wLl02EMVmKbUCIBtUJow6nGKH688SsuMrGltICIU_j5tElrq9FBD5W40p&sig=eA0QJ8wRQIhANIySQDp6TS572X4AerTqfqydH8r4IpqBGtCqvsYrwMjAiAMNFbvwqtAcZp4TPv3pAgrCVlyABeqz%3Dcm7EUacdDAhA%3D%3D%3Dv) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:33)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:133)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr4---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1681849100&ei=rKY-ZO-CH-WHp-oP3qCqiAY&ip=31.49.0.120&id=o-AOBAXxRmegEwMPzssvHlYGjhuZhOp4iSiLpIxZkkJxbw&itag=140&source=youtube&requiressl=yes&mh=4T&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9id&ms=au%2Crdu&mv=m&mvi=4&pl=25&gcr=gb&initcwndbps=2401250&vprv=1&mime=audio%2Fmp4&ns=jSuglrfu_EDAlJ30RB4wE9sM&gir=yes&clen=1111756&dur=68.499&lmt=1595274914714404&mt=1681826735&fvip=5&keepalive=yes&fexp=24007246&beids=24512778&c=WEB&txp=2311222&n=1yIQxDPx2-30BhjW7KI&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgd_NPD3JMx9acZB-KXk7cvDGbaf8CwV5wLl02EMVmKbUCIBtUJow6nGKH688SsuMrGltICIU_j5tElrq9FBD5W40p&sig=eA0QJ8wRQIhANIySQDp6TS572X4AerTqfqydH8r4IpqBGtCqvsYrwMjAiAMNFbvwqtAcZp4TPv3pAgrCVlyABeqz%3Dcm7EUacdDAhA%3D%3D%3Dv) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:33)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:133)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:204)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(FetchPlatformQueryResult.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:194)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:89)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Media Links Used:** 
https://open.spotify.com/playlist/6vsipZtfZMydO1khUHDPtw

**Expected behavior**
 I wanted the songs to download.

**Screenshots:**
 None available. 

**StackTrace:**
```
None available.
```

**Device Info (please complete the following information):**
 - Device:   HP All-in-one Core i3 8th Gen Computer
 - OS:   Windows 11 Home
 - Version:   22H2 (OS Build: 22621.1546)
 - Country: UK

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
