### ISSUE TITLE
[BUG] : Unable to download songs from Spotify.

### ISSUE THREAD

**Issue by ArmanSingh24** [Shabinder/SpotiFlyer#2776]
**Describe the bug:**
Unable to download songs from Spotify and Jio Saavn also.

**Media Links Used:** 
For Spotify-https://open.spotify.com/track/2qOfyyZc41LfQ63U9p3GVV?si=kTuZzEevQ4qKWTcZ_vF5HQ&dd=1
For Jio Saavn-https://www.jiosaavn.com/song/hookah-bar/RSQeZEZkekI

**Screenshots:**
Downloading from Spotify -
![IMG_20230425_061402](https://user-images.githubusercontent.com/109358065/234147841-f8ce5a67-4d49-4f08-8548-276efea8efa7.jpg)
Downloading from JioSaavn -
![IMG_20230425_062023](https://user-images.githubusercontent.com/109358065/234148608-b4fb54de-8300-4268-9c78-418bbf10c5e9.jpg)

**Stacktrace** (I don't know what this thing is, are you asking about this) -
WHAT WENT WRONG (FOR SPOTIFY) -
java.lang.Exception: Client request(https://aac.saavncdn.com/771/NhtpViG40ASlEcWjj8OpjSYZ5eI4oOG1G8DgwO_320.mp4) invalid: 404 Not Found. Text: "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:25578293-a01e-0074-420e-77098c000000
Time:2023-04-25T00:37:02.6529157Z</Message></Error>"
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Device Info**
 - Device: Redmi 9i
 - OS: Android 10
 - Version: 3.6.3
 - Country: India

**Comment by ArmanSingh24** [comment]
What happened here 😶

**Comment by ArmanSingh24** [comment]
I don't know about Gaana or YT Music if they are working or not.
