### ISSUE TITLE
Spotify download issue 

### ISSUE THREAD

**Issue by Ugotmo** [Shabinder/SpotiFlyer#2777]
DownloadLinkFetchFailed(errorTrace=Find Link for Over The Rainbow 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Over The Rainbow)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:299)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Yt1sMp3 Failed for jBKfPwdhA0c:io.ktor.client.features.ClientRequestException: Client request(https://yt1s.com/api/ajaxSearch/index) invalid: 403 Forbidden. Text: "<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7bd30ecabd829834')"></div>
        <form id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_f_tk=vBc6TdIW.j0_RTzZqSyfA6pOrxYvf6JWhZBCXjSbYao-1682388712-0-gaNycGzNCmU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="P73kDQxkKeYRYt3iTIVDfYZse0B8EujvYpYwsU7S5UI-1682388712-0-Afq3gtqaGwGRgpxqav5m7nSfofbX2ROcaK6q-mYtI2k0niRx7M4LX_BLu4pnEejHVADo11IX8Xs6FxkyevzVTIFJK30lvo22rf0Sb2FC2shPZcy1gpq_12SkXcVy31HghPEn46LwO6RDFl9yNaFfT449W2dy8SuII_deXHm3l0uMEtslhnh9w8_eG1iEMVwMuLyrYqjTAlxxrZwTJZK-B95JB8l8QnTngk9bZ2vEmwFg6KbrGvnJYfZsSCbWiPV5GpicI2FQb7waGsRBD0PwCo7Hqx43U0jUpPQ8SKoVi_HGEoJpXDz7i4qWz5-iYz1jcYKSwx4gsr9ajB17t3PZ1Qw7DvwdOQPMTegXTF8T_GFznfJA0P_Hu5fSte8J4Aqb19-0ehTngwC88MTSstGrHV1edLDnFSHLp2RBZ7YMq6stPK36l_ZzjmqM6k6dCz4vzmjdSJOxkHvX3Z2NeFZrfwjtatqVNwT6werNqBFpnU8EqvxxAinHW4MXvRjpmZUE9IVFfFMXwYY1nueP7LJ5W7vnqoZwfIsAtXlUImsebhEIMaZsa6flRjzS08IFX6xyT97Po3m223W2KUlSdi0JTvZP5wfCYiZRyuk3OmXtoEwKGs3-93Pfm1Z06jKfpfOw-dFk6s487rL5g8yDr2wnyGmfHfzkHIJWbjn4oQWbRLt7Vn8VvMgDEU3xA5XPEgl_7krJw2ON1eO58SrW3be4Z5ccR2dY1e-tLc4M_ITxvsnzSHWfeArm3-oDX2wyHGIBP8KoIsnOgVqhqAV8_-e68APZpahk62xdFUVcgYL8ebl9vL6Rg9qOVTarunw1EJ535uVVqQVmmo1YMGmqY1iMn4xw8-40-zp7FrVYzltqUumKRu4NIGCj7tsQwKWMUKBCFKx16gX-fGTXJ0QAP9TtbB8cAAP08GqpgcGPhEEcczgpz9V2HY_n4S9ZCgGBvOeScfZmFXdCceWBt8un4lrrObH-UkNVVFqvKdjmXUlaEuL7J6wn7QEF9ymdz2aHZXmao2zDanY3pHxapSlJOxBCFPJ7flyxP0xSUZ6P77WZS8tOHeOA0s2mqFSHSz-wKaVJuZ91VyAIdQLFS62DIp5cXCWCZyk6V-tYtvTXIAb42Tpw09ypB8mj2OEAOUblpueQ1Yl4O9Dc31ZhRpff1nf8Mgzo0qoeb8ihRYmq81hCFxstMKpnUYGb2CGW7qa9yiPj1xw2zQrMgtokU2o9Dw8oa388SWW8QS37RXBk2zHOpAutMCmMl9ed89W_lpS9k5ByhrxCsbR4_HV-JenAdUd3z8MEEk7QHeZ1Bee8eINno2W74EJfUdWrlh_QB-_Ft7hNmQ0ozCqdOmiEB2Yr1NMPcojGFvZ6huqjoSskfR_7dKeTOqKDLQnQlehBMWmA2_fqSLl-Sv5KcLeFgqJ4wvbv1KA506DgZV967Z2uERyQKpVJ8UbTjlxtUiwaRUPOTdlBTbrMQNFx7QaozvA9zQUO0wo74UpOrggWC08JDNo0d2fvq_iOUukxWm8-e5r4JwQaM2xMqVsobIpRs2CT_gxeN0ZWYD7xjfL_BceVP1uAfSBtdxUqMiaOKbFOhlcf0cKBZAlfVL3VOb-1abCb-VNQlq9TlENN54N84-dEslZmIJ9vH23CkbpFW4HYXc27tWWJFlRD0AKFSbxbjF-FsvvWJTMPygUaUiAdPR6eik7um5FnTKpiuvk4AOfi_i2ANUKkGZNUi7iCGEkIC0UFFe-ouLK41-uXlqD4D2RqA1RwjnN9wsmrRGkMNhJLHTUfzCu5DtHchSLNyr1Z8CPIuJmMwAiji3L3giEjh1jgU__xbEtlzK42a0T1iQXGJBCF1wS36lMx-29ruo10mE7BXAWNtCBBsuJsymxf1wFd_AfeYoMHmtaRoYHkzh-oMGMf6-zVvA_VtLFzQLqNH1swGOMT-ISGFUOX8dpbnNnXOEm5hFoutmgBH5rER7JeEAQtu7t_j3fdhXOQHY8RSAa8q4n1gwy6kQyF6uNxOfwdVuOoovMW8EyyWnkEJ5G6GwiQzee4escmRWlEkq4HkqNBQj96szTUCr2yt7xirg7KjdmmJJXGc6SJ-rU0fgMB5aHZ83j1Yr6Hy3hZZ8iUOFArVPNOE2GQiaw4sqlQyMB8BuuN1FvJBseeOwi6qts_NmF-4p8qolvvIvP1OV6CLVBeJYWGXhN-g5CYcFT9DnI4ZDdcFf5mAEvmMds3SaGzHKxr1r0MkfXEsQMAu8d_ya587Hsspbw6wbir42c5LinTrbEagsCelRh9f2btlG29cReYLhnc8C9PJbrgx7TGrA0-R-fZaEeSL5qY00nYyeOYiUF4QbO3O-6e4nH2j_kG8oQQiWJXm_w4qg8U5l10I5OH_w1N7XH9AAfgeU8H-Sq8aqalOvfazQquvhgHSxNpfh5IBl84c1ed7GRwEYOgo95n_tw5oojh2bNGAGKjnwjzmq9T3FdJE17g6Si1rH8UvmjD4XcZ18ziiy5uRuhPBZz1x8rixNohoGqHSZ7UXs9ZZZyEbz2WrXbbf9poqa5SVqwE5doHhL82wl0UZJw-hPZqnvpsNHe6ZGudbhL6-5ChNfgQzusD">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'yt1s.com',
            cType: 'non-interactive',
            cNounce: '66919',
            cRay: '7bd30ecabd829834',
            cHash: 'a1b02b780860c6f',
            cUPMDTk: "\/api\/ajaxSearch\/index?__cf_chl_tk=vBc6TdIW.j0_RTzZqSyfA6pOrxYvf6JWhZBCXjSbYao-1682388712-0-gaNycGzNCmU",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cMTimeMs: '60000',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==',
                ra: 'S3RvciBjbGllbnQ=',
                rm: 'UE9TVA==',
                d: 'V1+MxuuTcK2cjOf8+uAvRiACJ0xuCZLk7HJZDaAOVGKCGQqlxLHjj65Z3h444w9bUq+HcI0RU8ikVLbO0RdLBkPa5zVkqcadtWA5qix0XmDB6aXfjXljiUms4WL4kU0EqC82pGMsXAove0OUtca+XhBGtwxAbkju5wP2QHLrIhOsyGcjZvHxJlKtMTBnjVmBRVJwGQCdE4l+lGXXN3sb6FYB2gTNROgB7WmBUM/QknwOnuuzW2WdYiSLcTURpl0HAtpYux0GEQ0tKvqxZy53eMXJ3sjapAxQj3El7xM7qU40VdDEkXJL7W66j82K1qW+Bx+cx1+WsZRJ+qyWzxj74GKBOgIdDmGgwIvd+zx0LRVK/YAOJhunXFtU+Umo99cF6aignjKxFBJKJNOE3PnxLcpDQjrCfRbhm9PeJQ6Tp1Zd5gFQGLwQANfV+HcCUedUqKYF9W/c112BHYNeb4BFlkfDird8A2sVjCC3385+oOTIl0h2I5SntKZjwwAdKf2wWtiGFNDc2+K/ZJiEhMKwrczBpYEkcXLdkQNn6H3bYUwSKbaTZn3I3sxTnQR9QcJy1F3+ewfO7AkDWZc/nyMoRg==',
                t: 'MTY4MjM4ODcxMi4xMTQwMDA=',
                m: '0GX8LGbdIn6zxWeb6aZWH8EJGl6hoFqeQpT1g/IWIMQ=',
                i1: 'Fpij3wQHeq4/81bVu/09rA==',
                i2: 'eiFAegFne98a6yrG5HgUDA==',
                zh: 'slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=',
                uh: 'oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=',
                hh: 'LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7bd30ecabd829834');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=7bd30ecabd829834';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/api\/ajaxSearch\/index?__cf_chl_rt_tk=vBc6TdIW.j0_RTzZqSyfA6pOrxYvf6JWhZBCXjSbYao-1682388712-0-gaNycGzNCmU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://rr4---sn-o097znsk.googlevideo.com/videoplayback?expire=1682410312&ei=6DZHZMTWGYubkwbAoIDwDw&ip=173.230.148.226&id=o-ACI-1SZzP6gu-paZ2sS4jVMTEzrFV8pg8AgOLm0kVvko&itag=140&source=youtube&requiressl=yes&mh=fG&mm=31%2C26&mn=sn-o097znsk%2Csn-a5meknd6&ms=au%2Conr&mv=m&mvi=4&pl=22&gcr=us&initcwndbps=206250&vprv=1&mime=audio%2Fmp4&ns=Z0n4ewt-vUd5ULl48CuDfcMN&gir=yes&clen=6605429&dur=407.959&lmt=1571533318831962&mt=1682388295&fvip=1&keepalive=yes&fexp=24007246&c=WEB&txp=1311222&n=7V1KMT8bleZhOfvcQBb&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgOD0m65nnvZi6FhIvsqzCOHvR313SOVfVeKmuMIeWoRICIAMLr7E8mLH8eNQVbhvHLBvnMumcwFZHRiK_Y9LIbcmp&sig=Kq0QJ8wRgIhANjSnAZWqMx68KU9bie3e%3DzPhWjckKh9T-jmulzlwsW_AiEAv7SP0o94cR1-XPIAGs87_TNpULDb7WiI9TP5KlXo7I6) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://rr4---sn-o097znsk.googlevideo.com/videoplayback?expire=1682410312&ei=6DZHZMTWGYubkwbAoIDwDw&ip=173.230.148.226&id=o-ACI-1SZzP6gu-paZ2sS4jVMTEzrFV8pg8AgOLm0kVvko&itag=140&source=youtube&requiressl=yes&mh=fG&mm=31%2C26&mn=sn-o097znsk%2Csn-a5meknd6&ms=au%2Conr&mv=m&mvi=4&pl=22&gcr=us&initcwndbps=206250&vprv=1&mime=audio%2Fmp4&ns=Z0n4ewt-vUd5ULl48CuDfcMN&gir=yes&clen=6605429&dur=407.959&lmt=1571533318831962&mt=1682388295&fvip=1&keepalive=yes&fexp=24007246&c=WEB&txp=1311222&n=7V1KMT8bleZhOfvcQBb&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgOD0m65nnvZi6FhIvsqzCOHvR313SOVfVeKmuMIeWoRICIAMLr7E8mLH8eNQVbhvHLBvnMumcwFZHRiK_Y9LIbcmp&sig=Kq0QJ8wRgIhANjSnAZWqMx68KU9bie3e%3DzPhWjckKh9T-jmulzlwsW_AiEAv7SP0o94cR1-XPIAGs87_TNpULDb7WiI9TP5KlXo7I6) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:199)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:86)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:0)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:42)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:178)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:1873)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
