### ISSUE TITLE
Issue with downloading the song 

### ISSUE THREAD

**Issue by AnayaAcharya24** [Shabinder/SpotiFlyer#2948]
READ THIS!
	If some Song Download Failed with StackTrace having any of the following reason:
		- DownloadLinkFetchFailed(trackName=For Those About to Race, jioSaavnError=java.util.NoSuchElementException: Collection is empty., ytMusicError=MP3ConversionFailed(extraInfo=Client request invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY !
			- Please Dont Open issue! , Online Converter Was Busy! , try again after some time and download will be successfull . 
-->

**Describe the bug:**
<After pasting the link for some time it starts loading and then suddenly the song stops getting downloaded>

**Media Links Used:** 
<https://open.spotify.com/track/54SQet8YMttOgTqDNGcGpe?si=HC5uwk3_QaG4BVQ2ge9scg >

**Expected behavior**

**Screenshots:**
<!-
![Screenshot_20230513-084256](https://github.com/Shabinder/SpotiFlyer/assets/133472582/9a98ecd5-4721-41c2-b921-8479ce5f0e0b)
![Screenshot_20230513-084238](https://github.com/Shabinder/SpotiFlyer/assets/133472582/923d0219-23ad-4013-9e67-0fc61189754e)
. --->

**StackTrace:**
java.lang.Exception: Client request(https://aac.saavncdn.com/231/nSEymXYiWiJ8MWvQjLIrNgTk0PEneLhUDJevjY2zO8Hh5n_320.mp4) invalid: 404 Not Found. Text: "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:05d8ff1b-501e-0070-104b-85848b000000
Time:2023-05-13T03:35:09.1549528Z</Message></Error>"
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)

```

**Device Info (please complete the following information):**
 - Device:   [Android, Samsung galaxy A12, ]
 - OS:   
 - Version:   
 - Country: [ India ]

**Additional context:**
< The song suddenly stops getting downloaded in the half>

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
