### ISSUE TITLE
[BUG] : <Problem @ Soundbound Plugin>

### ISSUE THREAD

**Issue by DonKingKarl** [Shabinder/SpotiFlyer#3012]
null' Error' Error:
 Message: No Match Found for query: No Query Result Found for QueryParams(trackName=Hating Me - Original Mix, trackArtists=[Tough Love], trackDurationSec=352, genre=[], year=1970, albumName=Loving You / Hating Me, albumArtists=[Tough Love], trackLink=https://open.spotify.com/track/7t4dWvLoR3z22GlkhFYKQ3) from this source: null
Cause: Unknown Cause
StackTrace: 
```java.lang.Exception: No Match Found for query: No Query Result Found for QueryParams(trackName=Hating Me - Original Mix, trackArtists=[Tough Love], trackDurationSec=352, genre=[], year=1970, albumName=Loving You / Hating Me, albumArtists=[Tough Love], trackLink=https://open.spotify.com/track/7t4dWvLoR3z22GlkhFYKQ3) from this source: null
	at ba.j.D(SourceFile:27)
	at ba.j.E(Unknown Source:18)
	at db.j.invokeSuspend(SourceFile:276)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:84)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
```

**Comment by Shabinder** [comment]
follow video installation and then try (Install all providers)
https://soundbound.shabinder.in/install
