### ISSUE TITLE
For all those complaining about the format and ""not being able to download""

### ISSUE THREAD

**Issue by TheStezusChrist** [Shabinder/SpotiFlyer#3031]
Don't worryi have your back if you are looking for answers.

1.First get an app like this 
[Mp3 and format converter](https://play.google.com/store/apps/details?id=mp3videoconverter.videotomp3.videotomp3converter)
![Google Play Store.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/e8b158ed-cffa-44d8-a516-53d470819733)

2 Next paste the link and download the song 

.![Soundbound.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/59e2d113-8d11-4f5e-81d5-d1bc31e24bc5)

3. Go to files and look up "soundbound"
And select this one ![ Files.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/a5d96758-d7ff-4b27-8a67-5ee2609b2a80)

4. open converter  and select format conversion 

![MP3 Converter.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/b319d8bb-9038-4d3a-8c65-cf5645f4eb4b)

5 click the drop down tab
![ideo to MP3 Converter.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/2be115db-7c1d-41d5-9b7c-098c8d365b61)

7. Select the folder you want 
![3 Converter.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/5de17dea-0795-4cf8-8972-60bcc4cf9e8d)

8. Select songs you want to convert 
![o MP3 Converter.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/e33c228d-ee2a-418d-b828-d901272cf7c4)

9. Convert them to mp3![3ideo to M3 Converter.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/2c44ccfb-f7c7-4815-8c40-7d9e7607f6ec)

.
.
.
How to find the file they are in 

1.![Files.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/35695814-95cc-45d7-b4e6-7b7b8626a65d)

2.![My Files.jpg](https://github.com/Shabinder/SpotiFlyer/assets/128417893/7b4e8b32-69fc-4783-b1bf-91025f1adaed)

**Comment by TheStezusChrist** [comment]
Also, M4a is better anyway 🤣🤷.I'm just letting everyone know that. Unless you are running on old software, I see no reason to complain about this.  But here yall go

**Comment by ahamed-sha-11** [comment]
java.lang.Exception: Client request(https://aac.saavncdn.com/731/WgJLPoJQUEQo15M2IEFllk8cRsIVvRdearCuyks_320.mp4) invalid: 404 Not Found. Text: "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:793a3d2b-a01e-004b-2502-8ec12f000000
Time:2023-05-24T05:40:00.4604573Z</Message></Error>"
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)
