### ISSUE TITLE
[BUG] : No Songs/Albums/Playlists are dowloading from Spotify

### ISSUE THREAD

**Issue by Vishwan-T** [Shabinder/SpotiFlyer#3048]
**Describe the bug:**

Spotify songs are not downloading. Tried multiple individual songs and playlists also.

**Media Links Used:** 

1.https://open.spotify.com/playlist/37i9dQZF1EIZyYcHNHFSkW
2.https://open.spotify.com/album/3YdrTcu1YnQAcjJwnNeYgI

**Expected behavior**

**Screenshots:**

![Screenshot-20230601-135405](https://github.com/Shabinder/SpotiFlyer/assets/51510648/81908929-55de-4f84-b0d5-5953110abec8)

**StackTrace:**
```
java.lang.Exception: Client request(https://aac.saavncdn.com/572/JuVXToH7HLUqdXF8Gd2a3nMQZDtAMqpsksALOIOO_320.mp4) invalid: 404 Not Found. Text: "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:a89d583d-001e-0042-5461-9484fc000000
Time:2023-06-01T08:14:44.7290289Z</Message></Error>"
 at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
 at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
 at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)
 at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
 at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
 at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)
 at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
 at h7.a.resumeWith(ContinuationImpl.kt:10)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
 at h7.a.resumeWith(ContinuationImpl.kt:33)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
 at h7.a.resumeWith(ContinuationImpl.kt:33)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:74)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:0)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:17)
 at h7.a.resumeWith(ContinuationImpl.kt:33)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
 at h7.a.resumeWith(ContinuationImpl.kt:33)
 at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
 at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
 at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
 at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
 at h7.a.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
 at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)
```

**Device Info (please complete the following information):**
 - Device:   Moto E40
 - OS:   Android 11
 - Version:   3.6.3
 - Country: India

**Additional context:**

**Comment by taimourz** [comment]
Facing the same issue. I pasted the link to a playlist that I created. It's public but I don't know why is it not downloading even a single song 
![Uploading Screenshot_2023-06-04-19-42-40-427_com.shabinder.spotiflyer.jpg…]()

**Comment by Shabinder** [comment]
#3013
