### ISSUE TITLE
[BUG] : I can't download any song from Spotify (with sources extension) please fix this

### ISSUE THREAD

**Issue by adamperkowski** [Shabinder/SpotiFlyer#3181]
**Describe the bug:**

I got this error:
```SAAVN' Error' Error:
 Message: No Match Found for query: QueryParams(trackName=In the End, trackArtists=[Linkin Park], trackDurationSec=216, genre=[], year=1970, albumName=Hybrid Theory (Bonus Edition), albumArtists=[Linkin Park], trackLink=https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq, interestedEntityType=All, ISRC=null) from this source: in.shabinder.soundbound,extensions.SAAVN
Cause: No SAAVN Match Found for In the End : DownloadLinkFetch Failed
StackTrace: 
```java.lang.Exception: No Match Found for query: QueryParams(trackName=In the End, trackArtists=[Linkin Park], trackDurationSec=216, genre=[], year=1970, albumName=Hybrid Theory (Bonus Edition), albumArtists=[Linkin Park], trackLink=https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq, interestedEntityType=All, ISRC=null) from this source: in.shabinder.soundbound,extensions.SAAVN
	at pa.k.i0(SourceFile:29)
	at pa.k.v(SourceFile:96)
	at ac.i.<init>(SourceFile:48)
	at vb.o.invoke(SourceFile:35)
	at com.arkivanov.decompose.router.children.DefaultChildItemFactory.invoke(SourceFile:46)
	at com.arkivanov.decompose.router.children.ChildItemFactory$DefaultImpls.invoke$default(Unknown Source:13)
	at com.arkivanov.decompose.router.children.ChildrenNavigator.a(SourceFile:288)
	at com.arkivanov.decompose.router.children.ChildrenNavigator.navigate(Unknown Source:9)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(SourceFile:3)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(SourceFile:1)
	at com.arkivanov.decompose.Relay.a(Unknown Source:41)
	at com.arkivanov.decompose.Relay.accept(Unknown Source:25)
	at com.arkivanov.decompose.router.slot.DefaultSlotNavigation.navigate(Unknown Source:17)
	at com.arkivanov.decompose.router.slot.SlotNavigatorExtKt.navigate(Unknown Source:12)
	at cc.h0.invoke(SourceFile:24)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Unknown Source:12)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(SourceFile:5)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(SourceFile:156)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTaskKt.resume(Unknown Source:79)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(SourceFile:96)
	at kotlinx.coroutines.CancellableContinuationImpl.b(SourceFile:35)
	at kotlinx.coroutines.CancellableContinuationImpl.e(SourceFile:43)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:8)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(Unknown Source:25)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.a(SourceFile:45)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SourceFile:21)
	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(Unknown Source:26)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:95)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(SourceFile:34)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:23)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:178)
	at androidx.compose.ui.platform.AndroidComposeView.l(SourceFile:68)
	at androidx.compose.ui.platform.AndroidComposeView.d(SourceFile:227)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:89)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4409)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
	at android.view.View.dispatchPointerEvent(View.java:15331)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7003)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6779)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6198)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6255)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6221)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6386)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6229)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6443)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6202)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6255)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6221)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6229)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6202)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9367)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9318)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9286)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9506)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:298)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:169)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8289)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: DownloadLinkFetchFailed(trackName=No SAAVN Match Found for In the End, errorTrace=null)
	at in.shabinder.soundbound.extension.shabinder.saavn.requests.SaavnRequests$DefaultImpls.findBestSongDownloadURL(SaavnRequests.kt:106)
	at in.shabinder.soundbound.extension.shabinder.saavn.requests.SaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:84)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	... 5 more
```

YOUTUBE' Error' Error:
 Message: No Match Found for query: QueryParams(trackName=In the End, trackArtists=[Linkin Park], trackDurationSec=216, genre=[], year=1970, albumName=Hybrid Theory (Bonus Edition), albumArtists=[Linkin Park], trackLink=https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq, interestedEntityType=All, ISRC=null) from this source: in.shabinder.soundbound.extensions.YOUTUBE
Cause: Collection is empty.
StackTrace: 
```java.lang.Exception: No Match Found for query: QueryParams(trackName=In the End, trackArtists=[Linkin Park], trackDurationSec=216, genre=[], year=1970, albumName=Hybrid Theory (Bonus Edition), albumArtists=[Linkin Park], trackLink=https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq, interestedEntityType=All, ISRC=null) from this source: in.shabinder.soundbound.extensions.YOUTUBE
	at pa.k.i0(SourceFile:29)
	at pa.k.v(SourceFile:96)
	at ac.i.<init>(SourceFile:48)
	at vb.o.invoke(SourceFile:35)
	at com.arkivanov.decompose.router.children.DefaultChildItemFactory.invoke(SourceFile:46)
	at com.arkivanov.decompose.router.children.ChildItemFactory$DefaultImpls.invoke$default(Unknown Source:13)
	at com.arkivanov.decompose.router.children.ChildrenNavigator.a(SourceFile:288)
	at com.arkivanov.decompose.router.children.ChildrenNavigator.navigate(Unknown Source:9)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(SourceFile:3)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$eventObserver$1.invoke(SourceFile:1)
	at com.arkivanov.decompose.Relay.a(Unknown Source:41)
	at com.arkivanov.decompose.Relay.accept(Unknown Source:25)
	at com.arkivanov.decompose.router.slot.DefaultSlotNavigation.navigate(Unknown Source:17)
	at com.arkivanov.decompose.router.slot.SlotNavigatorExtKt.navigate(Unknown Source:12)
	at cc.h0.invoke(SourceFile:24)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Unknown Source:12)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(SourceFile:5)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(SourceFile:156)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTaskKt.resume(Unknown Source:79)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(SourceFile:96)
	at kotlinx.coroutines.CancellableContinuationImpl.b(SourceFile:35)
	at kotlinx.coroutines.CancellableContinuationImpl.e(SourceFile:43)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:8)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(Unknown Source:25)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.a(SourceFile:45)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SourceFile:21)
	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(Unknown Source:26)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:95)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(SourceFile:81)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(SourceFile:34)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(SourceFile:23)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(SourceFile:178)
	at androidx.compose.ui.platform.AndroidComposeView.l(SourceFile:68)
	at androidx.compose.ui.platform.AndroidComposeView.d(SourceFile:227)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:89)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3133)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4409)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
	at android.view.View.dispatchPointerEvent(View.java:15331)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7003)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6779)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6198)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6255)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6221)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6386)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6229)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6443)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6202)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6255)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6221)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6229)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6202)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9367)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9318)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9286)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9506)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:298)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:169)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8289)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(SourceFile:1)
	at in.shabinder.soundbound.extension.shabinder.youtube.YoutubeProvider.sortByBestMatch(YoutubeProvider.kt:139)
	at in.shabinder.soundbound.providers.DownloadableProvider.b(SourceFile:108)
	at in.shabinder.soundbound.providers.DownloadableProvider$findBestMatchURL$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:84)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	... 5 more
```

**Media Links Used:** 

https://open.spotify.com/playlist/2nQb15OcxdOZycNxa9OVr2?si=J6_nfeeBScGkbInVjEd_-Q

**Expected behavior**

It should download the playlist.

**Screenshots:**

![Screenshot_2023-07-19-09-19-42-346_in shabinder soundbound](https://github.com/Shabinder/SpotiFlyer/assets/75480869/3855d1af-0ce3-48dd-a670-04a8d000bfed)
![Screenshot_2023-07-19-09-19-45-770_in shabinder soundbound](https://github.com/Shabinder/SpotiFlyer/assets/75480869/38aaedd1-2ea2-4551-9322-86b5c8f1ea3b)

**Device Info (please complete the following information):**
 - Device:   [Redmi Note 10 Pro]
 - OS:   [Android]
 - Version:   [13]

**Comment by adamperkowski** [comment]
there are many dupplicates, dev doesn't seem to care / be able to fix it
