### ISSUE TITLE
[BUG] : <Some songs wont download>

### ISSUE THREAD

**Issue by Zimaster681** [Shabinder/SpotiFlyer#3200]
**Describe the bug:**

Some songs refuse to download and I don't think its for the reasons you warned above in the message.

This is the error that comes for me: 

[java.lang.Exception:](http://java.lang.exception/) off=0, len=4088 out of bounds (size=0)
	at [com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)](http://com.shabinder.spotiflyer.service.foregroundservice%24enqueuedownload%242.emit%28foregroundservice.kt:6)/)
	at [com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)](http://com.shabinder.spotiflyer.service.foregroundservice%24enqueuedownload%242.emit%28foregroundservice.kt:1)/)
	at [com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:54)](http://com.shabinder.common.core_components.file_manager.filemanagerkt%24downloadfile%244.invokesuspend%28filemanager.kt:54)/)
	at [com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown](http://com.shabinder.common.core_components.file_manager.filemanagerkt%24downloadfile%244.invoke%28unknown/) Source:11)
	at [com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown](http://com.shabinder.common.core_components.file_manager.filemanagerkt%24downloadfile%244.invoke%28unknown/) Source:6)
	at [kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:94)](http://kotlinx.coroutines.flow.flowkt__errorskt%24catch%24%24inlined%24unsafeflow%241.collect%28safecollector.common.kt:94)/)
	at [kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown](http://kotlinx.coroutines.flow.flowkt__errorskt%24catch%24%24inlined%24unsafeflow%241%241.invokesuspend%28unknown/) Source:12)
	at [h7.a.resumeWith(ContinuationImpl.kt:10)](http://h7.a.resumewith%28continuationimpl.kt:10)/)
	at [kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)](http://kotlinx.coroutines.dispatchedtask.run%28dispatchedtask.kt:100)/)
	at [kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)](http://kotlinx.coroutines.internal.limiteddispatcher.run%28limiteddispatcher.kt:12)/)
	at [kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)](http://kotlinx.coroutines.scheduling.taskimpl.run%28tasks.kt:2)/)
	at [kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)](http://kotlinx.coroutines.scheduling.coroutinescheduler.runsafely%28coroutinescheduler.kt:0)/)
	at [kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)](http://kotlinx.coroutines.scheduling.coroutinescheduler%24worker.executetask%28coroutinescheduler.kt:14)/)
	at [kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)](http://kotlinx.coroutines.scheduling.coroutinescheduler%24worker.runworker%28coroutinescheduler.kt:28)/)
	at [kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)](http://kotlinx.coroutines.scheduling.coroutinescheduler%24worker.run%28coroutinescheduler.kt:0)/)

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   Samsung galaxy S10+
 - OS:  the newest android that the S10 has
 - Version:   [3.6.3]
 - Country: [eg: India, will help in detecting if service is accessible to u]

**Additional context:**

This message was generated by every failed song.
I tried to download a playlist but a good portion of the songs didn't download.

**Comment by supperka** [comment]
DownloadLinkFetchFailed(errorTrace=Find Link for The Walking Dead Theme (Easy Street Season 7) 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for The Walking Dead Theme (Easy Street Season 7))
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:299)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)



Fetching From YT Failed:NoMatchFound(trackName=The Walking Dead Theme (Easy Street Season 7), message=The Walking Dead Theme (Easy Street Season 7) : Žádná shoda nenalezena!)
	at com.shabinder.common.providers.youtube_music.YoutubeMusic.getYTIDBestMatch(YoutubeMusic.kt:179)
	at com.shabinder.common.providers.youtube_music.YoutubeMusic.access$getYTIDBestMatch(YoutubeMusic.kt:0)
	at com.shabinder.common.providers.youtube_music.YoutubeMusic$getYTIDBestMatch$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)


)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:1873)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at h7.a.resumeWith(ContinuationImpl.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:55)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:17)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:0)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:24)
	at h7.a.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:0)


This is my problem.

**Comment by Zimaster681** [comment]
Just noticed something interesting.
I tried to down Casper by Robert Grace by posting in the app a YT music link and it failed to download. I believe it's because they're named the same way.
When I tried to download I'm Sane by Axie with the YT music link it downloaded fine. I think it's because it's named a bit differently on YT.
