### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by rioisvirtual** [Shabinder/SpotiFlyer#3350]
can you help me i cant download the music
![image](https://github.com/Shabinder/SpotiFlyer/assets/151386474/506e3ae6-d466-4f11-9997-b57bc694d55e)
 and this code
com.github.kokorin.jaffree.JaffreeException: Failed to execute, was interrupted
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:189)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:146)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: com.github.kokorin.jaffree.JaffreeException: TCP negotiation failed
		at com.github.kokorin.jaffree.net.TcpServer.run(TcpServer.java:69)
		at com.github.kokorin.jaffree.process.Executor$1.run(Executor.java:83)
		at java.base/java.lang.Thread.run(Unknown Source)
	Caused by: java.lang.NullPointerException: it.timeMillis must not be null
		at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend$lambda-1$lambda-0(DesktopMediaConverter.kt:32)
		at com.github.kokorin.jaffree.ffmpeg.FFmpegProgressReader.readProgress(FFmpegProgressReader.java:146)
		at com.github.kokorin.jaffree.ffmpeg.FFmpegProgressReader.negotiate(FFmpegProgressReader.java:54)
		at com.github.kokorin.jaffree.net.NegotiatingTcpServer.serve(NegotiatingTcpServer.java:44)
		at com.github.kokorin.jaffree.net.TcpServer.run(TcpServer.java:66)
		... 2 more
Caused by: java.lang.InterruptedException
	at java.base/java.lang.ProcessImpl.waitFor(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:179)
	... 15 more

**Comment by rioisvirtual** [comment]
@Shabinder
