### ISSUE TITLE
[BUG] : Song downloads then results in error

### ISSUE THREAD

**Issue by Holecene** [Shabinder/SpotiFlyer#3357]
**Describe the bug:**
Entire song will download and then isn't palyable, resulting in an error. It asks me to copy some code in case I want to submit an issue.

**Media Links Used:** 
Multiple Spotify links, none work but here's 2:
https://open.spotify.com/track/6pjI3CKUkIGbvSgo7TuRuu?si=278b0693f90b41aa
https://open.spotify.com/track/7tm4pF2JvKc4GGKSagRuS9?si=5ee6655e616846f5

**Expected behavior**
Expected the song to be usable once downloaded

**Screenshots:**
N/A

**StackTrace:**
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_co
```

**Device Info (please complete the following information):**
 - Device:   [Dell Inspiron 15 - 7000 Gaming]
 - OS:   [WinOS]
 - Version:   [11]
 - Country: [Australia]

**Additional context:**

**Comment by AngelJRomero21** [comment]
Spotiflyer dejo recibir Actualizaciones. Deberia de Buscar otra opcion
