### ISSUE TITLE
[BUG] : Unable to connect to Internet

### ISSUE THREAD

**Issue by Cyclopropinon** [Shabinder/SpotiFlyer#3415]
**Describe the bug:**
spotiflyer fails to open any links. Spotify, Youtube.
Small Error Box appears:
![grafik](https://github.com/Shabinder/SpotiFlyer/assets/119750500/20f10c6b-3e4c-4833-86cf-a1c4fbf4ac52)
On my browser (Firefox as well as Links2) I can open both Youtube & Spotify ==> I have Internet connection.
Last year when I have been using this app, it worked fine.
After a few months of not using it, I now decided to use it again, and it doesnt work anymore.

**Media Links Used:** 
https://open.spotify.com/playlist/1JLw7Y5YvlsA10XjaKHTxE
https://www.youtube.com/watch?v=Zwh40iLEl0Q
(also tried with a ton of other links. too much to dig up and paste here)

**Expected behavior**
Load the Link and show the Download Menu.

**Screenshots:**

**StackTrace:**
```
Debug: (Kermit) Requesting New Token
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
io.ktor.client.features.ClientRequestException: Client request(https://open.spotify.com/) invalid: 429 Too Many Requests. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:47)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:54)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:33)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:133)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Debug: (Kermit) Spotify Auth Failed: Please Check your Network Connection
```

**Device Info (please complete the following information):**
 - Device:  Lenovo ThinkPad T410
 - OS:   Linux/Ubuntu 22.04.3 LTS
 - Version:   3.6.1 (Issue on both `.deb` and `.jar` Version; Stacktrace from `.jar` Version)
 - Country: Germany

**Comment by bastifpv** [comment]
Have the same issue

**Comment by tcntad** [comment]
Same issue here as well

**Comment by AceNagata** [comment]
same issue here

**Comment by Habbut** [comment]
same issue with

-     Device: iMac "Core i5" 3.3 27" (5K, 2020)
-     OS: Linux/Ubuntu 22.04.4 LTS
-     Version: 3.6.3-1 (Issue .deb Version)
-     Country: Germany

**Comment by tropisch** [comment]
got the same problem
