### ISSUE TITLE
[BUG] : Downlaod Failed

### ISSUE THREAD

**Issue by HarryPotter42MC** [Shabinder/SpotiFlyer#3452]
**Describe the bug:**
 I cannot download some songs from a spotify playlist

**Media Links Used:** 
https://open.spotify.com/album/0k7ALIqqds5oGFtpMsaHLK?si=kQnWAZBJRk-PqICO8OnUFA

**Expected behavior**
All 16 Songs should download

**Screenshots:**

**StackTrace:**
java.lang.Exception: Connection reset
    at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:6)
    at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$2.emit(ForegroundService.kt:1)
    at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
    at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
    at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
    at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
    at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
    at h.w.j.a.a.resumeWith(ContinuationImpl.kt:4)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Device Info (please complete the following information):**
 - Device:   Samsung Galaxy S21
 - OS:   Android 14
 - Version:   some version before 4.0.0 (I cant update)
 - Country: Germany

**Additional context:**

**Comment by HarryPotter42MC** [comment]
Just request 1 download at a time and it works
