### ISSUE TITLE
[BUG] : <Not downloading, the app told me to report it>

### ISSUE THREAD

**Issue by iicecey** [Shabinder/SpotiFlyer#3463]
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:163)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1140)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1074)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1111)
	... 16 more

**Describe the bug:**
There was a error sgin so i clicked on it and it told me to send in the info and do a bug report

**Media Links Used:** 
https://www.youtube.com/watch?v=_lJinafvHy4

**Expected behavior**
I thought it would download

**Screenshots:**
![Screenshot 2024-04-17 at 9 12 43 PM](https://github.com/Shabinder/SpotiFlyer/assets/120227859/69808992-de58-436d-96c4-26b72cfa61d9)

this is constantly on the screen

![Screenshot 2024-04-17 at 9 26 56 PM](https://github.com/Shabinder/SpotiFlyer/assets/120227859/f474fdc4-a4eb-4c2f-9076-16571c188e5e)

This showed up when I used yt music on a playlist

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:  Macbook Pro 13in 2019
 - OS:   MacOS
 - Version:   Ventrua
 - Country: USA

**Additional context:**

**Comment by emmanuelmavely** [comment]
Install [ffmpeg](https://ffmpeg.org/download.html) and [add environment path](https://docs.telerik.com/teststudio/features/test-runners/add-path-environment-variables) to its bin folder.

Then try again.
