### ISSUE TITLE
[BUG] : <Issue_Title>Songs from spotify are not downloading 

### ISSUE THREAD

**Issue by amoli-exe** [Shabinder/SpotiFlyer#3582]
Error Code: 
UnknownReason(exception=null, message=Unknown error)
	at com.shabinder.common.providers.DesktopActualKt$downloadTracks$2$1$1$1.emit(DesktopActual.kt:49)
	at com.shabinder.common.providers.DesktopActualKt$downloadTracks$2$1$1$1.emit(DesktopActual.kt:39)
	at com.shabinder.common.core_co

![Screenshot 2024-12-20 204259](https://github.com/user-attachments/assets/4559119a-d38f-43b5-a0a0-2882fc24979f)

**Comment by gazzer1312** [comment]
i have the same issue
