### ISSUE TITLE
[BUG] : <Internet error>

### ISSUE THREAD

**Issue by ZukeDST** [Shabinder/SpotiFlyer#472]
**Describe the bug**
Badly support short offline moments (1/2s), and will aborth the download instead of waiting

**Media Links Used:** 
 https://youtube.com/playlist?list=PLnr8edW-T21Vx4AHF9p2v8lXGr_vNT_Wu

**Expected behavior**
A longer try for the downloading

**StackTrace:**
```
java.lang.Exception: Software caused connection abort
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:12)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at com.shabinder.common.di.DirKt$downloadFile$2.invokeSuspend(Dir.kt:37)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

```

**Device Info (please complete the following information):**
 - Device:   [Oppo A9 2020]
 - OS:   [Android]
 - Version:   [3.2.1]

**Additional context**
During the short time that my phone use to switch from mobile data to WiFi (I didn't turn off any of these, it just switch to WiFi when possible), around 20 downloads stops and show the same error message

**Comment by Shabinder** [comment]
Try again in v3.3.0 and if still doesn't work try with a vpn
