### ISSUE TITLE
Playlist download from gaana not working[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by Srivathsa25** [Shabinder/SpotiFlyer#521]
**Describe the bug**

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1]
 - OS:   [e.g. iOS, Android, WinOS, MacOS]
 - Version:   [e.g. 3.2.1]

**Additional context**
java.lang.Exception: Request timeout has expired [url=https://aac.saavncdn.com/949/628ab027d9676f9e299ef627fdaada59_320.mp4, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:12)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$2.invokeSuspend(FileManager.kt:36)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Seems like Internet Issue try again in v3.3.0 and it should work: 
https://github.com/Shabinder/SpotiFlyer/releases/tag/v3.3.0
https://github.com/Shabinder/SpotiFlyer/tree/main#-install

**Comment by Srivathsa25** [comment]
I have tried from many devices, and even changed my network but did not
work..

**Comment by Shabinder** [comment]
May I suggest you try using with a VPN on 3.3.0

**Comment by Srivathsa25** [comment]
Thanks, I'll check it out.

I can't find v.3.3.0 apk can u send it via mail
