### ISSUE TITLE
[BUG] : Windows MSI doesnt work but JAR does

### ISSUE THREAD

**Issue by RaulmmBr** [Shabinder/SpotiFlyer#551]
Windows version, msi, and jar, wont open.
I have tested on windows 10 and 7.

**Comment by True-King** [comment]
same here

**Comment by Shabinder** [comment]
try opening the jar from cmd and then share the error log which appears there

**Comment by exilvm** [comment]
Only the .exe version doesn't work, the .jar works just fine.

**Comment by Shabinder** [comment]
> 
> 
> Only the .msi version doesn't work, the .jar works just fine.

Use MSI until I can figure whats wrong with .msi

**Comment by zamarax** [comment]
Same issue as MSI, appears your countly server is not working correctly, see below

`PS C:\Users\corey\Desktop> java -jar SpotiFlyer-windows-x64-3.3.0.jar
Info: (Kermit) null\SpotiFlyer\ already exists
Info: (Kermit) C:\Users\corey\SpotiFlyer/.images\ already exists
Info: (Kermit) null\SpotiFlyer\Tracks/ already exists
Info: (Kermit) null\SpotiFlyer\Albums/ already exists
Info: (Kermit) null\SpotiFlyer\Playlists/ already exists
Info: (Kermit) null\SpotiFlyer\YT_Downloads/ already exists
[INFO]  Countly [network] Server: https://counlty.shabinder.in
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] Listing crash
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Storage] Listing session
[DEBUG] Countly [SDKCore] recovering session 1632499105749
[DEBUG] Countly [Storage] read session_1632499105749
[DEBUG] Countly [Storage] Pushing async session_1632499105749
[INFO]  Countly [SessionImpl] No data in session end request
[DEBUG] Countly [SDKCore] session 1632499105749 recovery won't recover
[DEBUG] Countly [Storage] read user_0
[DEBUG] Countly [Storage] No data for file user_0
[DEBUG] Countly [SDKLifecycle] Application created
[INFO]  Countly [ModuleDeviceIdCore] [onContextAcquired] Starting device ID acquisition
[DEBUG] Countly [ModuleDeviceIdCore] [onContextAcquired] Loading previously saved device id:[86a2400a-9775-4486-b377-d235532b2f88] realm:[0] strategy:[0]
[DEBUG] Countly [SDKCore] non-limited onDeviceId DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0), old DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)
[DEBUG] Countly [ModuleDeviceIdCore] onDeviceId [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [ModuleSessions] onDeviceId DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0), old DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)
[DEBUG] Countly [SDKCore] 5
[DEBUG] Countly [Storage] read timedEvent_0
[DEBUG] Countly [Storage] No data for file timedEvent_0
[DEBUG] Countly [SessionImpl] begin
[DEBUG] Countly [Storage] Pushing async session_1632503737745
[DEBUG] Countly [Countly] onConsent: features = [Lly.count.sdk.java.Config$Feature;@1217633
[DEBUG] Countly [SessionImpl] end
[DEBUG] Countly [Storage] Pushing async session_1632503737745
[INFO]  Countly [SessionImpl] No data in session end request
[DEBUG] Countly [SessionImpl] begin
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503737749: [1632503737749] begin_session=1&session_id=1632503737748&metrics=%7B%22_os%22%3A%22Windows+10%22%2C%22_os_version%22%3A%2210.0%22%2C%22_locale%22%3A%22en_CA%22%7D&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503737749
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503737749] begin_session=1&session_id=1632503737748&metrics=%7B%22_os%22%3A%22Windows+10%22%2C%22_os_version%22%3A%2210.0%22%2C%22_locale%22%3A%22en_CA%22%7D&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503737747&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503737749] begin_session=1&session_id=1632503737748&metrics=%7B%22_os%22%3A%22Windows+10%22%2C%22_os_version%22%3A%2210.0%22%2C%22_locale%22%3A%22en_CA%22%7D&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503737747&tz=-240&hour=13&dow=5
[DEBUG] Countly [Cly] event: key = app_launch
[DEBUG] Countly [EventImpl] setSegmentation: segmentation = {}
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [EventImpl] record: {"hour":13,"count":1,"segmentation":{},"dow":5,"key":"app_launch","timestamp":1632503737759}
Debug: (Kermit) System Time:1632503737 , Token Expiry:1632502706
Debug: (Kermit) Requesting New Token
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=BQAEqtc-Sjxi9OVvyB3ydctKiYKzqnwCNEsiwOmqFX54-DotgAsBPwmvIvIE5fz8-EZfeJ3awiMcooUQ24A, token_type=Bearer, expiry=3600)
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503737749]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503737749 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503737749
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503767757: [1632503767757] session_duration=30&session_id=1632503737748&events=%5B%7B%22hour%22%3A13%2C%22count%22%3A1%2C%22segmentation%22%3A%7B%7D%2C%22dow%22%3A5%2C%22key%22%3A%22app_launch%22%2C%22timestamp%22%3A1632503737759%7D%5D&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503767757
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503767757] session_duration=30&session_id=1632503737748&events=%5B%7B%22hour%22%3A13%2C%22count%22%3A1%2C%22segmentation%22%3A%7B%7D%2C%22dow%22%3A5%2C%22key%22%3A%22app_launch%22%2C%22timestamp%22%3A1632503737759%7D%5D&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503767758&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503767757] session_duration=30&session_id=1632503737748&events=%5B%7B%22hour%22%3A13%2C%22count%22%3A1%2C%22segmentation%22%3A%7B%7D%2C%22dow%22%3A5%2C%22key%22%3A%22app_launch%22%2C%22timestamp%22%3A1632503737759%7D%5D&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503767758&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503767757]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503767757 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503767757
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503797766: [1632503797766] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503797766
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503797766] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503797766&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503797766] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503797766&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503797766]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503797766 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503797766
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503827774: [1632503827774] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503827774
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503827774] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503827775&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503827774] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503827775&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503827774]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503827774 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503827774
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503857778: [1632503857778] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503857778
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503857778] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503857778&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503857778] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503857778&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503857778]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503857778 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503857778
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503887784: [1632503887784] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503887784
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503887784] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503887786&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503887784] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503887786&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503887784]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503887784 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503887784
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[INFO]  Countly [ModuleSessions] updating session
[DEBUG] Countly [SessionImpl] update
[DEBUG] Countly [Storage] Pushing async session_1632503737748
[DEBUG] Countly [ModuleRequests] New request 1632503917794: [1632503917794] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88
[DEBUG] Countly [Storage] Pushing async request_1632503917794
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request
[DEBUG] Countly [Networking] Preparing request: [1632503917794] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503917794&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [send] Sending request: [1632503917794] session_duration=30&session_id=1632503737748&device_id=86a2400a-9775-4486-b377-d235532b2f88&timestamp=1632503917794&tz=-240&hour=13&dow=5
[INFO]  Countly [network] [processResponse] Code [200] response [{"result":"Success"}
] for request[1632503917794]
[DEBUG] Countly [network] Success
[DEBUG] Countly [Networking] Request 1632503917794 sent?: OK
[DEBUG] Countly [Storage] removing request_1632503917794
[DEBUG] Countly [Networking] [check] state: shutdown [false], tasks running [false], net running [false], device id [DID 86a2400a-9775-4486-b377-d235532b2f88 (0, 0)]
[DEBUG] Countly [Storage] readOne request`

**Comment by Shabinder** [comment]
Countly working correctly or not will never affect App.
I just tested Jar in my Windows and It worked correctly. Can you share screen record of what actually is happening as it may provide some insight

**Comment by Shabinder** [comment]
Guys Try again, I fixed the issue in v3.3.1
@karankad you can try again publishing this

**Comment by schirinowski** [comment]
Thanks, @Shabinder, Spotifly opens after installing v3.3.1. It didn't before, when v3.3.0 was installed.

**Comment by philipprochazka** [comment]
Hi, 
Thanks for your great work. I have unfortunately found an small issue.
I don't know what the issue is if I am missing UTF-8 or the program just cannot Czech letters, but anytime
I get something with Czech diacritics, they are either not written out correctly to the filename
or it does not want to download at all.  I`m currently running the .msi version
for example:

DownloadLinkFetchFailed(errorTrace=Find Link for Léto 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Léto)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:44)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(JioSaavnRequests.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)



Fetching From YT Failed:NoMatchFound(trackName=Léto, message=Léto : Žádná shoda nenalezena!)
	at com.shabinder.common.providers.youtube_music.YoutubeMusic.getYTIDBestMatch(YoutubeMusic.kt:110)
	at com.shabinder.common.providers.youtube_music.YoutubeMusic.access$getYTIDBestMatch(YoutubeMusic.kt:56)
	at com.shabinder.common.providers.youtube_music.YoutubeMusic$getYTIDBestMatch$1.invokeSuspend(YoutubeMusic.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:204)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(FetchPlatformQueryResult.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
