### ISSUE TITLE
[BUG] : Can't download any song

### ISSUE THREAD

**Issue by DolanD2** [Shabinder/SpotiFlyer#563]
**Describe the bug**

I can't download anything from Youtube

**Media Links Used:** 
  - Paste Song/Album/Playlist Link where you encountered this issue

https://youtu.be/GZmIWI6UGPg

**Expected behavior**

I expected that the app will download what i wanted it to lol

**Screenshots**
If applicable, add screenshots / screenrecording to help explain your problem.

**StackTrace:**
```
Paste Stacktrace here if available
```
MP3ConversionFailed(extraInfo=Client request(https://hostpro.onlineconverter.com/file/error) invalid: 404 Not Found. Text: "Not Found", message=MP3 Converter unreachable, probably BUSY ! 
CAUSE:Client request(https://hostpro.onlineconverter.com/file/error) invalid: 404 Not Found. Text: "Not Found")
	at com.shabinder.common.di.providers.requests.audioToMp3.AudioToMp3$DefaultImpls.convertToMp3(AudioToMp3.kt:35)
	at com.shabinder.common.di.providers.requests.audioToMp3.AudioToMp3$convertToMp3$1.invokeSuspend(Unknown Source:10)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Device Info (please complete the following information):**
 - Device:  Samsung Galaxy A30s / SM-A307FN
 - OS:   Android 11, OneUi 3.1
 - Version:   3.2.1

**Additional context**

I tested only YouTube, i don't have Spotify so i don't know if it would work with spotify songs.

**Comment by Shabinder** [comment]
Use Latest Apk, v3.3.0
