### ISSUE TITLE
Can't download songs

### ISSUE THREAD

**Issue by Evel270** [Shabinder/SpotiFlyer#573]
java.lang.Exception: Client request(https://r3---sn-i5heen7s.googlevideo.com/videoplayback?expire=1631955450&ei=mlVFYd-PNcT-1gL5vbyIBg&ip=31.17.25.31&id=o-ANx4DMufaeBbS9JFiU4juIq-evVk_DjA_S4suJxZXu2n&itag=140&source=youtube&requiressl=yes&mh=rc&mm=31%2C29&mn=sn-i5heen7s%2Csn-i5h7lnll&ms=au%2Crdu&mv=m&mvi=3&pl=24&gcr=de&initcwndbps=1902500&vprv=1&mime=audio%2Fmp4&ns=BwgpfswO7iw_coPLCxATjkoG&gir=yes&clen=2087404&dur=128.772&lmt=1614141940863801&mt=1631933580&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=wql2hVtx8doH-O&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAK-gVu3hc5hd4NtdEfLd7hd0OIHyl4PCkc2pIGIGAecHAiBYD9_XgcyoX2ICovy3Q9J0HIOfKPpfCEGhx0UBEM6sYg%3D%3D&sig=AOq0QJ8wRQIhAImoFfwibDxxCe1usXed0Ua6_CThALLlUi3pLD0D2LJuAiA3EQm_5eS0afr38BbOhzUBedwm3EAizY51bzNLDTUN6A%3D%3D) invalid: 403 Forbidden. Text: ""
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by fayaz07** [comment]
I tried to download an album from youtube music, youtube, jio saavn
tried even individual from jio saavn - nothing worked - not worth downloading it.

**Comment by Shabinder** [comment]
> I tried to download an album from youtube music, youtube, jio saavn
> tried even individual from jio saavn - nothing worked - not worth downloading it.

Just becuz you are not able to use it doesnt mean it doesnt works.
Instead of helping out by sharing details in a proper formatted bug report just saying it doesnt works helps no one.

**Comment by fayaz07** [comment]
Well, I would add few when I run it from android studio
just tried the apk :(

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
