### ISSUE TITLE
Songs not downloading 

### ISSUE THREAD

**Issue by Grannynorma** [Shabinder/SpotiFlyer#577]
Can't download from saavn through app phone is oppo a 83

**Comment by Avejac** [comment]
Am getting below error code when I try downloading some songs on YouTube
java.lang.Exception: Request timeout has expired [url=https://r1---sn-ap90pquxaxjvh-ocvl.googlevideo.com/videoplayback?expire=1632103064&ei=OJZHYZ_TFrCimLAPtrqhwAk&ip=41.84.152.6&id=o-ADmedeNWIhV_jdF_5CVPXBReRbw66cSeRolk7H7791rQ&itag=140&source=youtube&requiressl=yes&mh=rM&mm=31%2C29&mn=sn-ap90pquxaxjvh-ocvl%2Csn-hc57en7d&ms=au%2Crdu&mv=m&mvi=1&pl=21&gcr=ke&initcwndbps=215000&vprv=1&mime=audio%2Fmp4&ns=rPZ5wVHpxftou9ZsJ520g30G&gir=yes&clen=3090151&dur=190.891&lmt=1544732222035052&mt=1632081171&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5533432&n=ZFyn6wzv5C6xEn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMW_LtiElKJZI-K_DC7j_fkezCAYW4s5WrDIETV3TdjDAiAVmsoqwaQZKIgk5BmN6SOfstFyuAFaN0SqgyscqAmWzQ%3D%3D&sig=AOq0QJ8wRQIgBw_ZwDa8qvMAF4M9_lw8tH4M3I324Mnmlvzn6Ug1P2MCIQDV4_rkxIRMa-rzdS7LFX-jWDWXR2TJMSvfU-NSgZtl1Q%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Try again in v3.3.1 above said issue wont occur however fill bug report else issue wont be considered
