### ISSUE TITLE
[BUG] : ffmpeg issue on MacOS

### ISSUE THREAD

**Issue by lordelan** [Shabinder/SpotiFlyer#589]
It shows a warning that "No FFmpeg found at path" and this error when downloading a song:

`com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:170)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)`

**Comment by lordelan** [comment]
Installed ffmpeg with brew but still no luck.

**Comment by Shabinder** [comment]
can u simple run ffmpeg in console ?

share screenshot after executing **`ffmpeg`** in Terminal

**Comment by lordelan** [comment]
![Screenshot 2021-09-22 at 10 44 53](https://user-images.githubusercontent.com/23257650/134312151-ea54e35c-43bb-4a93-a51c-36dcfd01c60c.png)

**Comment by lordelan** [comment]
Yes I can :) (iTerm2)

**Comment by Shabinder** [comment]
Before I upstream the issue to Jaffree Library can you check once again after closing the program and restarting your pc

**Comment by lordelan** [comment]
Did with no success unfortunately.

**Comment by Shabinder** [comment]
Ohk then, seems an Issue with Jaffree, will upstream the issue there

**Comment by Shabinder** [comment]
Here it is, https://github.com/kokorin/Jaffree/issues/223

**Comment by lordelan** [comment]
Thanks a lot!

**Comment by kokorin** [comment]
@lordelan @Shabinder 
An exception clearly says: "No such file or directory".
It's hard to add anything else having only exception. Are there any logs available?

Usually it happens if ffmpeg was installed **after** JVM started or if JVM was started from a console which in it's turn was launched before ffmpeg installation. To be 100% sure I would suggest full reboot if possible.

**Comment by Shabinder** [comment]
@kokorin 

> An exception clearly says: "No such file or directory".

this happens bcuz it tries to reference a file named **ffmpeg in his path**  whereas actually, one doesn't exist.
But if that is the case how is he able to run `ffmpeg` ? 🤔 

> Usually it happens if ffmpeg was installed **after** JVM started or if JVM was started from a console which in it's turn was launched before ffmpeg installation. To be 100% sure I would suggest **`full reboot`** if possible.

I thought so too and suggested same, but @lordelan says issues persisted

**Comment by Shabinder** [comment]
@lordelan 

can you share the path of ffmpeg , call `which ffmpeg`
It will return Path to FFmpeg if it actually is in PATH, if returns nothing then call `locate ffmpeg` and add its **output to Mac's PATH** and restart App to see if it works

and share full Path , call : `echo $PATH`

**Comment by lordelan** [comment]
@Shabinder 
`which ffmpeg` throws me the correct (and expected) path
`/usr/local/bin/ffmpeg`

**Comment by Shabinder** [comment]
> `which ffmpeg` throws me the correct (and expected) path
> `/usr/local/bin/ffmpeg`

@kokorin 
if above is the case do you know if there could be any reason why Jaffree would throw File `Not Found Exception for ffmpeg`?

**Comment by kokorin** [comment]
@Shabinder It could be so that the app runs under another user, or it could have another PATH var

**Comment by lordelan** [comment]
Interestingly enough I had the same issue in Windows but I solved it by downloading the bin folder of ffmpeg and pointing a path environment variable to it.

**Comment by 1xKarthik** [comment]
the same issue on Mac M1, tried both installs of homebrew and manual static install of ffmpeg. The path is available and ffmpeg works in cmd, but the app is not able to detect it on both instances.
From the error message, its checking the ffmpeg in a folder, can you let us know which folder it is looking for?
![image](https://user-images.githubusercontent.com/3351150/140958948-640261bb-a36d-42fd-b721-3b7c0b90c267.png)

`com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:172)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:114)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more
`

**Comment by kokorin** [comment]
@Shabinder there is new Jaffree version available, it logs some system information if failed to start ffmpeg/ffprobe process.
Please, update dependency and configure logging to log at least warning level of `com.github.kokorin` package.

**Comment by Shabinder** [comment]
> @Shabinder there is new Jaffree version available, it logs some system information if failed to start ffmpeg/ffprobe process. Please, update dependency and configure logging to log at least warning level of `com.github.kokorin` package.

I am actually rewriting the whole app, so was looking to build that a release the updated version with that.

But if it gets delayed then will release a new hotfix in Spotiflyer itself

**Comment by henryteng07** [comment]
@1xKarthik did you find a solution?

**Comment by enricobachiorrini** [comment]
This solved the problem for me: https://github.com/Shabinder/SpotiFlyer/issues/891#issuecomment-1164216867
