### ISSUE TITLE
[BUG] : I don't know... Song when tried from Spotify downloaded like a part of it and not full and when youtube link link gave this error

### ISSUE THREAD

**Issue by Jamesk21504** [Shabinder/SpotiFlyer#590]
java.lang.Exception: Client request(https://r2---sn-qxaelnes.googlevideo.com/videoplayback?expire=1632346303&ei=X0xLYci1CIHi1wL9wrKIDg&ip=36.82.98.4&id=o-ADTB2ITh1pH_1IG5SfCGjkFOV_HHBzuvBrbv3XFnetz7&itag=140&source=youtube&requiressl=yes&gcr=id&vprv=1&mime=audio%2Fmp4&ns=zPp_gXZ4WzCk3Vdf8-cc_c0G&gir=yes&clen=2992533&dur=184.749&lmt=1631621076047506&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=4UDJFDlJvL28mfBU&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJZUh7TOwazuQa-CHExHSCldfgfvd_rr9nGYPbohD5WnAiEA-AKVRSPnWQ0seJPDdLdTVX2kSHW8HEfbLCiAayrrqNY%3D&title=Paradise&cms_redirect=yes&mh=Rk&mip=103.205.113.22&mm=31&mn=sn-qxaelnes&ms=au&mt=1632338935&mv=m&mvi=2&pl=24&lsparams=mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRgIhAIg4FlMURiZI6_jG1Xl0oLlcXbN-inqtJpSKTaiHP1FJAiEAupRTlGAEE4yR58i_QqKO7mE1jp5sMQjlXa3dFWfv9J8%3D) invalid: 403 Forbidden. Text: ""
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Spotify link https://open.spotify.com/track/60STJ5y9RdFsbFBVwsLpEP?si=5AGxuv4dQBia5Wfq0pBIvA&utm_source=copy-link&dl_branch=1

YouTube music link
https://music.youtube.com/watch?v=7e2vhpWGflw&feature=share

**Comment by Shabinder** [comment]
Removed Manual YT Extractor from Codebase so you wont encounter above issue again
