### ISSUE TITLE
[BUG] : Failed Downloading

### ISSUE THREAD

**Issue by Pzoryder** [Shabinder/SpotiFlyer#591]
Having trouble on downloading a playlist on Spotify.

https://open.spotify.com/playlist/3cenHL17XDenqV7rN6rDi3?si=VyRAmSy2S6Om7L7-VybgqQ&utm_source=copy-link&dl_branch=1

The error told me to copy paste the 
code while reporting a bug
The code is given below

java.lang.Exceptionn: unexpected end of stream
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

This is the code^^^

![IMG_20210923_232358](https://user-images.githubusercontent.com/91289090/134578731-85572d39-4e03-42d6-8a7c-d675d4c42f66.jpg)

Device: Redmi note 8
OS: Android 10
Version: 3.3.0

**Comment by Shabinder** [comment]
Thanks for reporting the issue, you can retry download and it should work fine. however will research on cause of this issue

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
