### ISSUE TITLE
[BUG] : Error while downloading from Spotify

### ISSUE THREAD

**Issue by phamedq** [Shabinder/SpotiFlyer#620]
Error while using a vpn and this app to download songs from Spotify. (without vpn the app shows no Internet connection) 
Tried with single music, album, playlist and authors but no luck so far. 

A simple link for ex: https://open.spotify.com/playlist/4NskVobwsyH6zxaRTRbKOv

**Expected behavior**
It should've started downloading or for better results if the items are not available shown them. 

**ERROR CODE: for single music download 
DownloadLinkFetchFailed(errorTrace=Find Link for When the Sea Lets Go 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for When the Sea Lets Go)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:19)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Fetching From YT-Music Failed:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="3">
  <script type="text/javascript">
    //<![CDATA[
    (function(){
      
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "74685",
        cRay: "695b05dfed65fafa",
        cHash: "2e20ba80fcb5c35",
        cFPWv: "b",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==",
          ra: "S3RvciBjbGllbnQ=",
          rm: "UE9TVA==",
          d: "e+chydtX1EPbX8BsbJi3koGxtE/r7Te9saL26Ic1if9Gv7e+kWhFrT1WfZwbS9tsSKJVfAys3bzL2krMTrYbcWf9yR0+8FAyxfTGoypkaD8d6EKj+N39GxWQ32QKSRMGb3pi8jjUSDmXD7pCzPDHLzlPjlv4eLLKXvHL0g/QEPDaHneR7oEJDJmQjWAjSo6pkS625Q6dggJZJEzc5m/DSbm3SO730PkuhLtBV2ecDWGQkWtPN1L9j4QWRlyn8vjGtfl2WZDKkEm28NDzueVAKrz0jmnt+ZwejsnRkiDRdFKLWHasQzTDQMI5Gam2zomY8HMYDiNEZ+S0yGBeeS4iqnMF2wXhjOkKm4In5zcWpp73yEYvbyRCIB1hHVbZ5AcKOlHCqLEW2HPIZpS+FKt0bq9xKHv2ewsaONEUT0F3tz4mD1feissLmoRIdE2XTjKlujtOLY+EY/tIp2gnUjIMpW+iqjYvbV2nxOwRYiHciTh0cSgpAJrdsEnFOjginQi34OXclAbFzSMKPttYo8ubSQ==",
          t: "MTYzMjgxMTY3My41OTEwMDA=",
          m: "SAb4fjQhip4K+mqteWC38qidI2vlImxxByKleX2nRYY=",
          i1: "nnEpvN+Lla5BJiTmXMFs2g==",
          i2: "N/r2PuUnO0FqT6f4Ui2aPQ==",
          zh: "slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=",
          uh: "oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=",
          hh: "LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
      
    })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yt1s.com.</h1>
    
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>
   
  <form class="challenge-form" id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_jschl_tk__=pmd_VP2DeYTMfXO.d1pAN80n9vL.y32jA2wG3I8o.FXa2yY-1632811673-0-gqNtZGzNAiWjcnBszQb9" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="KGNYnFMh8Pr8YkqZ9w0gmjU34NReROzI3QLBtlc_nPw-1632811673-0-AcA6XGa4BemlxJfiOOtgcrH5zBX9qMaFqd8e0-cW_gS1YNgvSWafUOYXFhZxK_ZCKEoO8Sc_dt2GuWmvrgSeVAvrTywHKoLkHljDTb7PaOn-KZEkzKnWQt7eRyxTRaDVBFjz2b9nrmB9s_1TAJ6k_TJTJ8yeLoFfDcxwkiWmT9fi6GzIvTGnc7KKkZBgUCzInGWaEthjsGTkGrORbmhjACJp1GNPWALhAqm_FzBB5uXFtKo9ujT4gw53mKvGwheAoGtyKzGd7qzWuCkaOM0vGLZP3MCoP4nGG-FHffSH-YNemqzxdej5nMK-E5AGxEOAhOl5hO0gaYY3z_wsBH6N1dmaO_3MRGTMfMV4Kb6vvyh2L9szxm4yaFWK8NdKtogVN6JDMbTH6OJYAfDiOJiMsRhfp1-wfghh8vjHJwgs7xjMKdZzeUwlmt8WU33ni0JojkwbTgZydTLiLjJM9yFamb0SIqxI7MgELXBNMW_bFE6p" />
    <input type="hidden" name="r" value="qomc4R02OicWRx1wVSqGMKu79_Sq2qmA2tfN0XrT5L8-1632811673-0-AYLMhPzpLBDAzaKNM8VNo4xU38M72EkD7TqI+C6RBhbsIQpEkzk5K6BvC4mrpV10/iuOX4wYIRi75mOrSjWuLlfZ/IqNj5duJINSZXFhCj4EQSR9YkjNFoVD/QEbLH8iNuXZgwqxR540omkXj/tfXyqxQCAhmkZwi+RPZ6a2FBtb39jhXvRuN7i7t80t4lxZrtCB/uAyBRilyuBi5wZU3aMjtopq9e7yNXM0LPQkiwryhuVs2BTIF72h2f3a5s+sWFyWy7AawPO+rUr7AefTTL8LB58T0XaXMysti6xrQyci6dWL+5xow1TAnFLYRAIvnNlaZgLzxoZnv8LYmoQW4oWInrVcdukHyTPUZ3o6+jAb/UHg3tFipkp4e5u3i0yDVRrtT/6So60eU0qsvmcmUdAz3yEqrHGWdj5RqeMlzy2lXpiAne5g1nUqdxF54bduFnfT8bmsJd5BAQlfhpAp2LsW3ccqiq3APekRwAywOUshHgLMmgNLbQ8XlI5JGT7fVkKPO8Lgf1wylUbX8dDYV3pu62Qf41IkzG5u8XUVFRBROdWWT/e8f+pmIuZMNxAJaP/3Q0aY97pMv9alPnIh97qZZuDixzRgVHDH3+Xiek31Vn/YrrW6pQHhSwpsNT4VY8yrxAsiPrziFtaINnQeKXYtaeZNZ31UChVKqlXdTM05iLLlyffZRD9u3xh1Ny4Ej6NRHdfJi8J8QQRgdWohOAklRFKELvFBNiGYwtspnPAx27BrEgsFbsQRZucOKgAG0c2ppzmq2uBB2J3/OA1ecEHJ3/xrM9mOlFb5KWlSBCJYC5f3peVCfLzxjG3CJNUP2K94kKsU6d3/MetNsxWyv1vxCPL5zWq2h9XKQSHxBMJ422OdG9UCTJDndBEhtfFnuW52X9kxGX1ck7ODe7/DcFe0mWkP5hrZXYYIx3FLF3T4VLsbKrQfS5tos9Rw4GqKEPl4UDEIkUiKO2c+K3HKxQkbSMDOXavVCjk17ospPVfnA1ViCL6Sxf/ISHZ1hXXJwnFMW1d7PrfYgdpv3iuSb9RUavf+5W61cVkrdeHK9wrm3iCM5AX+GjBLnXI6V3xEtVtRw8uTiQEu8ICzciAjbfbwUifr698+VygTCt+NDDFpp3N5wqxwFkQ3WJdotC2NXSJrKxhaRlP6a4Urjt19QFm+3yFZL3uSmST9UZrEnYK3Kp7E7atXrV7BWCu9T25l8Ivxw/ZO6s/EWkCcx40ZtC69RFEIQt5yywlEJ/kdLJmiCUdEGlgOz1fMA10EqiZQI55MVRC+M6PGLHuw/+XwdDMZyTQn1PxQOBIYevcH+pVW5sRi+7ISJXAta1MaKKPY0xHrmLi5fcXfmn8rOCvJw0p1M5Slrs2isQdIoUkLhv+YhOyNmxZUR3524e/gCQtPjA027rOVtQ/Qj1tCXLLMlJ3H8DYRCKp4XHpmKrO7nBZrb61Jt00Tdq3mQh7Pobwzd6/GQeK4HK/L91FUGBn2rIWZ4JgLNytzG+ZJtN+6WsJVZJw8tE7nXh9nFQSestGNpZU4H70WmY8zB6DX/pX+5TkoQTHnS5WZR49ypTiFFGSucx2aFxlOc4zT2GuVd7VDbo0DUGYYE/B0/gE5NMW6vyzUmDoF6BwxXFT1+mQXJYvFiZqAhsebGcaB85WyrCMh7j5nhtGncWd1AP0VKbzmPc+wvrkOFK86kwWHUuBjOVhpOKtGGRIQdwN7tRRiA1Z9rQ=="/>
    <input type="hidden" value="5b7930cbf4bea4198adcca8b32a304e2" id="jschl-vc" name="jschl_vc"/>
    
    <input type="hidden" name="pass" value="1632811674.591-zdeRGD2nQX"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
     
    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=695b05dfed65fafa");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=695b05dfed65fafa";
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>
  

  
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=695b05dfed65fafa')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>695b05dfed65fafa</code></span>
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:15)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:59)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Device Info 
 - Device:   Xiaomi X3 Pro
 - OS:   Android 11
 - Country: Iran

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
