### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YuriHeh** [Shabinder/SpotiFlyer#630]
java.lang.Exception: Client request(https://r6---sn-tt1e7n7k.googlevideo.com/videoplayback?expire=1632978671&ei=j_JUYdnFAoSa8wTlqbSYBQ&ip=162.253.71.25&id=o-AL7u_3ko1wOGzJ4v-ixD8R6I0QpGQPKQwJtzJTbEGLSy&itag=140&source=youtube&requiressl=yes&mh=uN&mm=31%2C29&mn=sn-tt1e7n7k%2Csn-tt1eln7e&ms=au%2Crdu&mv=m&mvi=6&pl=24&gcr=ca&initcwndbps=1336250&vprv=1&mime=audio%2Fmp4&ns=PCLx62JTwZNNIZK0RKrIWU4G&gir=yes&clen=2968188&dur=183.242&lmt=1632930535225257&mt=1632956925&fvip=6&keepalive=yes&fexp=24001373%2C24007246&beids=9466587&c=WEB&txp=2311222&n=-8cSh9lBtrqMIiK&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIluF03qiZ_GIik7ExXOqCN_KBszCZYnpNvPFVrVRp32AiAZUxqopc_nxC-FEHElZAx599e0L5GstrKB6RS1lxmuFA%3D%3D&sig=vC9pFhbZ1yLWv%3DQD_oQHdZnVnd6UwlYa4NSN5W2TgVB%3DQICgZHBD05ooH01AsWG_BWV0JKwsjkkBD38z7IzhE-v52NgIQRw8JQ0qOee) invalid: 403 Forbidden. Text: ""
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$3.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
use latest 3.3.2 app
