### ISSUE TITLE
[BUG] : Some files download in 128kbps

### ISSUE THREAD

**Issue by Jamesk21504** [Shabinder/SpotiFlyer#633]
DownloadLinkFetchFailed(errorTrace=Find Link for No No 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for No No)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:19)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Fetching From YT-Music Failed:java.lang.IllegalArgumentException: Required value was null.
	at com.shabinder.common.utils.ExtKt.requireNotNull(Ext.kt:1)
	at com.shabinder.common.providers.youtube_to_mp3.requests.Yt1sMp3$DefaultImpls.getLinkFromYt1sMp3(Yt1sMp3.kt:8)
	at com.shabinder.common.providers.youtube_to_mp3.requests.Yt1sMp3$getLinkFromYt1sMp3$1.invokeSuspend(Unknown Source:10)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:59)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Link used 
https://open.spotify.com/track/2ehI5ZKz2sEuDnPVLy3fd2?si=rn382NebSoWh6n9PQG38og&utm_source=copy-link&dl_branch=1

So far I haven't encountered any other bug except some songs downloading in 128kbps bitrate which wasn't much of a bother But thought I'd report

**Comment by IdontCareFree** [comment]
Uninstalled App and then reinstalled app from downlaod page
Android 10
Samsung s9+
DownloadLinkFetchFailed(errorTrace=Find Link for Save Your Prayers 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Save Your Prayers)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:19)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)



Fetching From YT-Music Failed:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="3">
  <script type="text/javascript">
    //<![CDATA[
    (function(){
      
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "90718",
        cRay: "6971543fcd7a40d8",
        cHash: "9ed41de8eaa5e5c",
        cFPWv: "g",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==",
          ra: "S3RvciBjbGllbnQ=",
          rm: "UE9TVA==",
          d: "3wAWrDDQG3zecy3SiXUbPy6N34K+0jxogCkvKqX1L2rKX+G5UcDz4U9L8mIV39Z9lAHavCKotgaBYQLHjQ0OAdoYrjMYMHDt4i370FJlHf8wI+ZGEruoQCHZp7RVhzfwnhoNwRc7XUqbJuh/3xvN9l2qyJ18v/W3aG4DyuLOZuRwmix+QHEs1XokS32maqRZYQ1zWRAp0OAtxQxGfScopmOhv/zjEpFnDlZXp/+UoDKjSVoH/f4zUDr6etD6iKf+Ym4yAsCxnRoPMtussFtfQYT0ivLwgRVZjhqbcZMn2+yPHNpSAzMxiLmszyW1QePBanwExMYCklmxWdUG51jblkLDMuaVhrSD0hsYz2FdiGkaP87iUt/V5oB5Q3N2PUPa1zDhkrTFsnN/4xkDdggaRdxdRwvGMdgK3Rflz4HPV1mZzt7XB1rHofijSUY04j40uRcYIpIQ7PVDmwWLSNNcSRGre5Lw/U3fXrLoTSKoxGDBbVZDWRP3OYdLLtWoQAG7fs1o2NqiylcQSYwZrjjuF1S+4IPicMRE+/2hyKJ+r2QCYktT/CAXj1yP4BvSJcDc",
          t: "MTYzMzA0NTU3MC41MzIwMDA=",
          m: "BzQavXA8QQvIm3dGL+ABlCId9QJU9l294z1/3rr2m+0=",
          i1: "EXzwF+g8YZlDCRneYovEgw==",
          i2: "UUUqzC+QhOqLllse2yV5wg==",
          zh: "slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=",
          uh: "oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=",
          hh: "LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
      
    })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yt1s.com.</h1>
    
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>
   
  <form class="challenge-form" id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_jschl_tk__=pmd_uVLNi9VcsVexP8hD18zqCtaswePT4.hFqJQAPH650NY-1633045570-0-gqNtZGzNAiWjcnBszQg9" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="DmHV3kDii3tsP5VXSwf3oRhdsi4hHGi6T84PjrRTfTU-1633045570-0-Ab1VlP4G82AABNg15mTSYUdGKRCXVWXbgVledj15G8tZFdSZajxuXoOvgerLTa-jbAX9LTJYEkXvRW5xTwE8oue7gVp9jdKz-94PBtKVgt52hE0YztupMAboSaHLrwIWbdXqGlPCN_nU2xRUVUJIa_3kfjPl4U2-WpJxTONMaxH7I_Q7cWAP3r8QDaoWKPTxqAn5oIP0n1h26xLldpibgml8_5DekdEKIltRLLLFo5FgR26Yp8x9MV5VGo2U3xnVQTDnJ-GPpFDh3tNiGhs_K46UpQ-mEK-s5dtrFTdMhHmYDK7hoqIVoY7QLsgqnsWTspYLuzWaDAQQuwpJ7auTL9rhEOfeo_daOo7t3z8QE_rgGWk8OAI6hnGYahTpxeSzgDhhqkGOFzPBLOqIbtLIBefR4Sq9rg_P94pQ8mb5lXLM6_NUutaj-VatRcnUrNbOSR7DChRRGa8RkkCgMYBf3P--GbHhiQ5LC0AmUNKLgd3E" />
    <input type="hidden" name="r" value="Jsu0oZOFH1ZvQcLuZxKSwYoNmIscbETj49amjJ27F94-1633045570-0-AQB9yw3+tXT6PJqJk1H6rNviipXK2HI+AJ42l7BHJv1d+guK2LVKtFX7xSwrb552Eqw7lECubNYhJIVH1LqFMQXTADNRi3zBfPd0X1VA5whD4XdZVFIhv+eCa57EJYKJUWwQYzEMHZSUahFa4BAwPQ3f/2jMTnwZi33d2Jyp19h29N4NcKsiIcQQmLLHYpUwEphsT4ey9jBbwVedaoS1qbqlcZnHnBEz+xqR6sxXPSzXTXVLMYjk9xlCGfyLB6wKb7kxw4s3f71MbkTcEmdRGvv0yB+ab2TqHFXpWP4O2htYFQ1WsB6eKcpZPAf+FrUN494E37aK8k375VSIQduLSwziLod1EObSePQ2jmTS8szshkuulxqVZu0TlRoEaUdzL0N9jzTb+pq2xw6Yb77hvpkwAn8VmRNgrVqExcJE39QQrS0yyo8J0wo0+qxcckMGihnh9xF2+7mI9SGKlb4UUDn5cVYDLSJdcR/e+6sedA0xWTWERUms1CAVDbD43lYYjsWt+kmuEs5MxB9FMFqur7cd81YzdOacp1nKf6RPzlJ2M/CfxsOMyfFsuOU/GizX0VoOzM8hmHCYsFBDUjUZfGQAShd+hJjcdVxHvfIjIUkweW5eNXLYW5K0MkOHourDJK3FpM7HVM5pux9Urqr81VuHgVOJt9M76uLQM8ABykrJJxJrcacYOQ7wIwMLcdau5hMuaEl7OyAGPmcbI2lHyt9TrRYgeSuisdx6feuZG3rcESDIlzRCK5yVCFWmlDo1Kmm+Lth3ZXataI046/76HLgmPeqbtBYqnTK0HTagXgNGRSjR8Amk+/223rWSjgsnMSWNkhzZUTKw99s2qIFgMojRAPfoByFBd0esdvMvDm7U+wj3nEdsuaIdbOJdpXgN/V1gLPWIia/ICSFBKuyPVNdOi1Yl6xmX0EMPZHfR7HnB8Ds8tsgunkeuWDvUTHDuQdy6JwT6D6T/g5e0YmFWKFUjWmyL4f5qMSXvGzxQTgecrrH0zoVV5cPnssQfEKeXrr0YpR8gDUqPS7Y/zGKCG3Iel7IjuUHxDcCyUTeVoObB2o7FWeeuwkRrwwfL/FzzqQlsRZy23vn22XZ+U2drPzHgXxgQltFzWlJlZKHc1Fhu7flLFq+8MniNkIQOYQTaxDl/4I4Xl9i5pav1FAS8G+fYI3j1jMm3RhvJRMzsctwzW8NO5iqdF03A9AicbMJDT6xy5/WvmCJEdZIFQmWecVdyGy+yp6l/qPehHcoKSuvww78ohkYdph2ycXj4m8ecUuiCKes65hqRV6zxMVl0HVtrEa3GM6dw5+cj/tPGmVigm63wnZj2ldC5PgyS1eUaGpTW9CPJOOVANxc6QeOlVCtytqn2D8szJ4POCYjXbYMdQbBzNM4saLCVRz8/a4VlSlGtENX+ks3EYNAsGvYop5GVQN41oaydOfceQr6w6E4Kn7SfSoFX5AAd4MCL9GP1L9hg2YkpzoWS2UcnXNVSyWyCKkug8xX+tBTuTpibbsBuG/TA2ojRkdrtu/mqWudGc28pTGX5GnzUY7P2KWsgr79Y4wYXehAEyJrG12/gPFiheipuRttZVQcLapqhwh9xAdZ405esaRw8g7LKerhDv33/oEKAe/snn72Aj9BisNz/7Bl4Tpjjze9o5jn7//uLnuK3lT1bFJcPD7KJg9gvd3q+GL60QY9T1ktM5hSqm+ul6DUZfrkO++PoAI1ym+kBcXQJ+bHk5qJCSYs64YCe7oxk2fhV7lknCMa6kVw68b+kM73ifTV0ZBDMTymB9mZElGoh5StuNpYkMYO1ZMIhDXHzY5KiPUUqMP6s1XDPQBNm6j/p4ebvyqJ5VrX65eN4fgdBAgfTMOq/bjqpX9BbTcVQ3Oj96Um/hoRMxKhosvfmlDx6ypH8AHRFWOFyvWnclENYy1N+amP02nIDDdFedCYFpsTyzkdSTNuMWMYiQLZdQRK/rghsjffCKnCTsAprgv36x8AB1YnZ7lbsnzgz77wwvnaPi8TlENAuEdI7SD2bF3w3fui94zeJX1vy/ZptGA=="/>
    <input type="hidden" value="07aafe268010240af16f80f45bd67420" id="jschl-vc" name="jschl_vc"/>
    
    <input type="hidden" name="pass" value="1633045571.532-UYe8D6PTce"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
     
    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=6971543fcd7a40d8");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=6971543fcd7a40d8";
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>
  

  
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=6971543fcd7a40d8')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>6971543fcd7a40d8</code></span>
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:15)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)


)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:59)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
![Screenshot_20211001-004757](https://user-images.githubusercontent.com/87644619/135545200-f72abb3c-907c-4e58-9591-f31c9c06880c.jpg)

**Comment by Jamesk21504** [comment]
Actually worked... Downloaded in 128kbps but it actually did download after uninstalling and reinstalling

**Comment by IdontCareFree** [comment]
I download the apk straight from the website again and then reinstalled it
Playlist:
https://open.spotify.com/playlist/6JCtPDJwo0e5B9vD2uZ7vt?si=arv7xU75TPGzeRqITsWmRA&utm_source=copy-link&dl_branch=1

**Comment by Shabinder** [comment]
>and some songs I downloaded before on spotiflyer are showing up as not downloaded

See #611 

> Downloads in 128kbps only

See #562

**Comment by IdontCareFree** [comment]
Changes to 128kbps still not working
