### ISSUE TITLE
[BUG] : <Issue_Title>

### ISSUE THREAD

**Issue by IamLimp** [Shabinder/SpotiFlyer#665]
DownloadLinkFetchFailed(errorTrace=Find Link for FEEL NOTHING 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for FEEL NOTHING)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:19)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Fetching From YT-Music Failed:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="35">
  <script type="text/javascript">
    //<![CDATA[
    (function(){
      
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "59621",
        cRay: "69c0faac395715ee",
        cHash: "6fde347fb6ca55d",
        cFPWv: "b",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==",
          ra: "S3RvciBjbGllbnQ=",
          rm: "UE9TVA==",
          d: "stLf+oU+hBjsAeTMl9ht3kP8Xnjfw2p4BojwkE5/SR7aWSJcRR/JoWqhgyFu8iZihqpB2EequcXb8KaJu/WUxyE2E4dC3i9YHDWtO0GWCzR1SjrxpfMxxQf2mmrSkpmoJCQF+XlE5qoWDzI7jC3FsUjZmswB8YtPWfOqgkZtk++RXv7AIWcrnFzGbFg8vXZ5TD8zYk4y7vC4v0FCuwviniGHsrjMB2gHY8TjIVFGWA1dRpOAkjE/ajxw0SgdDW3Q/MYQ0yxtyOuI4HV0hBJwVnkl36H09ZPdXJytFm+xvcuM4n79+YH8HUuvoO4h+b7kUQHgECfk6b/RFQ2md11n8ZBXfVG18hMqDaIk929FoWktIS+aGhcQiMlvKkYgoc3gLYO7OQ8CXmc4p98VD+fvv0qIdbm/IKCSphUhxHP+iacQXeqj+FCijiNM2XJPHMTYVswz17LJF7xjVWEQwHrA9HKx/y4z9li+fhS9YCj8AsYVuzvz7g/OKEzUb/J56+0tNk3/kf7tNW1W7BRDWGZsC3uYYwfVoSCMljkGh/fv4An7W7+8ye0NH3sNSbEO/Lef",
          t: "MTYzMzg4MDc2Mi4yODUwMDA=",
          m: "Mslw6xoGcuMtP70kkhWsBAf1xXDAmYZrjtll5ypGw9I=",
          i1: "4DD36Rri7XC40FwRExhblA==",
          i2: "6n7J6n6aFo7e3IDIEpwB7Q==",
          zh: "slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=",
          uh: "oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=",
          hh: "LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
      
    })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yt1s.com.</h1>
    
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>
   
  <form class="challenge-form" id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_jschl_tk__=pmd_GUPY837ZiL_bLQeHwpXucXxi_JS7XpRDQf2.Cm6o5HM-1633880762-0-gqNtZGzNAmWjcnBszQg9" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="3hRSw7OSXHe9w313i.4mbJBW3FjGx9nDQISjOOdxdO0-1633880762-0-ARKzYJcDNWncgzccuwurYD3CJJVNJP-YJUwLHFx5rP1tBlcNHNzIffTS_cQtvHgvN4c7cmmFozMFpLz2uktQsBgKSnm4Yu6QmPc80cR_09056y9_QMSt6wOkINewqT1M2A3f4o6CGlAxDzdZYiBHE6tDO4lJoMVL_RtIuQe60gRwwaZzKXf1w2GE7WgIxJZawB-uKOqxAKQ2KYGHgshVOepfPQ-VfuvyHCDUQYqXjoXQE7-HenJqcfG0tgyp9s625g4W0sWivVplHwwXzN11rgRRHr4p7s7DA9wUXAWtAP5YVe-lkaGLNHLoCpaD8y0f59PTFJo-e9f9TCER4-t8uWt0rQlIcdtcpkIxB5V1b8oGNls742o4Vh389ybvOJiMYiUNrUVRAFy8WEkx5FVXXSqDpWGEjjndqmwVWsR-RiclYThjs6a4o3WFigUfQjJPGTlVcKMXaV22GnJCDTuv7FP4pRKWI6yZJ8-ZKif4JVIi5FPosXk9jwdDPlvC4eKGvIrHIVbkb91BhEAPj4n45QxgAZaAxkWuITrl5aWCqVuz" />
    <input type="hidden" name="r" value="Q0dN6wt_H2Yc9bk_6rG4rSFapm4ZSNuTCeKUcEGUa0I-1633880762-0-AV6uItdHH30MRYA529mMw/9E01gDt7e723EC18hyeqCkJmDUMPsZE6snaee6tHQZ9ZPpEdxVAwA4nH6l5OxHmtnnvgkfbO3vWRjDwMSbDUI6jG1c08XOlxEvUb96dt5xVuqzmLcScAOvhSMJMS0O8uEUXCmBVlS1UXfjT/zd9OLLTQbQp7YHVCMO7A4nu3VrOYn0BG4BrYrMRJWbCJtuSbF+0PZhJG0MKSYAuGMo7RhfkPZZGW9WvrAGEfgb+RZA8xYhC0UzfusZE//qfFwHO8VVIQ24+juG7dxqSGVAM+QLlrJRvxBL2xRB09BZfrhaxP4MiGuowovEU/i1kZzLOqDG2bZCRtl65QGx9VAbipiKhsiI2ax41iHmtDD02ChsF8yNRvkw98Bp4zOV76TwJeO6mHS7XqKU67K5s50hMJ208HVBb2poMnCl+8DrkdUOwFZccGjilf8/f+DQkkCerMHBeU2TnVKtjqBlchDTuYO4EuI5iwm4jNAevHTZuG4yzM0uPAf2lRsTj1SixCuu1BVly3m7QUpRgZrVn5eLCBSiapLRAjCR7wfN6vr+FyUhAsyqbrOqXS6mre0nAEj8KEX+HAKCuGeoQHfV6JFMXrxuh1NVEzxpC8LwLtfm7jNuw6IhHoNx4gLwiJAe0wzHNmuTbBIR0rYels/x0eO3muEGAJTtkYJEoBR5nLmI5BHiPe1npRnovmN5ki7qgupRooAXvoZhpD2USyEqx61Ttso1Hn+eQSXEO7EfnPvyumkYDJWByw5nZDXSWVeWDPjxV0rruPCF2t5BCykhYq43GBD63lKiBJdtv0Lgp8lVfyQOmvcOlsp8HG5Z+ciwBJUvAmup2X6yhEfYJHOBERcax2rkfRu2Wn1pU3RzN1V7C114CN4n5Il2jQiST5Q1r9y1xIdMq1YrBl0PJLj/cJt/UJV9M2dEG9A5lncBUCffxbXiMwQ3IFfG31pOfsv67iPzkwAOizxTnyKvokuOfFnlfmPAH5pSepAtfZep0fQLG8sEmWmbXf1lUrE5F86Da0j2jMtI0tc9F0q55LpV4avTp3twKwimC0aAKdMjP3INRIIW1FsQH9z2RLagy1YzssfX/6fXJam/IUAyaVXmXsYdap/w5E5RDHYV7NLbC+uqDIw2SUEUpj/75AfJUCSmiYdSQuGp3rOczdAgbrPYlhpkdzEghOrlMUSPRnJK3UX9/B6rmZesKfMp7u26QJYpNayqAolPbLNxO01HAwaql649Wc7E0VjFy65ShGwBHmF8mrNLuGSIuv1b25esePXGu+bRNaUOLZRiXNW2YmDHepk7vjzP2YcE2e9yNgrPADWVdatYkLwKqqH6E9CInWq+W2d42/JWhbRZYYb5glPGJ8vMljxq/syHj0Q3pPHCvwbxJ0FElrJwxALuYCb/z8+Mz8ZJPrBWz7rGPJjmR/66u7h6jA6tA445j7ITpMNfloJ/+4LWaTF4qmDEWUPYx7iNoAEgMP1ilsS43o8iTEcB/YbB53/i6+K/X4fjqemJyOKtOiT8omrYK34gj80tHcsTrjxC9PoCyYY/Kh+hYd2/UgElSn2vsBXA9PBItb7d4oV0BMwoqYrq583G0/iJZaidlU1IeMCB31a+6GAR6aSi9FtTjvcxqAedQYf7szOaK5IWEco6X4NJt6DO/M76boBI/dEZXeL7wUBjP2FxXUfKtwxZuXtHa/Dgo9f2xpEOcPqR4uAwtOq5FFf1aeA49ELTPdTiBlkEjUGoeuXj27NgqB8SQzeIHrVYlZproyDEIDY0WpRdQXzbSCdapcWT8+PmU6c1jrNIz+6UEr6wFwg6tmex4AF/eLnY2kwqyGnJ7HadZAyudxspsgmv8wd083oAfURy7YHEjt/GYrmP/aQtZ8RhoxZ9mWQgN/vmL1Qo2RMqYrrC88F2BYrlk1+UyKMANca/E3bp7JX0lNOLB+e7TmOU3YsAcqKbOqJOmvM+Cfhy35NQYa/uWKpxh94MbxMODpyKz50hpDhS3rIhAm/0qNyfHlxrppP7Tsq3ZZn/huY2nh02ew=="/>
    <input type="hidden" value="37ca2de92ead50612336d0c49b845dad" id="jschl-vc" name="jschl_vc"/>
    
    <input type="hidden" name="pass" value="1633880763.285-9VM4sOBBZC"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
     
    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=69c0faac395715ee");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=69c0faac395715ee";
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>
  

  
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=69c0faac395715ee')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>69c0faac395715ee</code></span>
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:15)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:59)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at q7.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at q7.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Try with a VPN to USA / India, it should work
