### ISSUE TITLE
[BUG] : Download Error on MacOS Big Sur

### ISSUE THREAD

**Issue by nasw1h** [Shabinder/SpotiFlyer#697]
**Describe the bug:**
14 out of 19 songs in this playlist failed to download

**Media Links Used:** 
https://open.spotify.com/playlist/1ESEPqEIVNRddtGWyxy2go?si=kZNkIbNETLW-z4vL78Ztnw

**Expected behaviour**
Download successfully without any error

**Screenshots:**
![image](https://user-images.githubusercontent.com/51323070/138552755-957b98da-52c9-4080-93a7-cc09d95dc378.png)

**StackTrace:**
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:172)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:114)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 16 more

```

**Device Info (please complete the following information):**
 - Device:   MacBook Air (13-inch, 2017)
 - OS:   MacOS Big Sur
 - Version:   11.6 (20G165)
 - Country:   India

**Additional context:**
Tried out this app on mobile and everything worked fine with the same link. Nice work btw.

**Comment by naxwh** [comment]
Ok, I installed it. But still it shows like this
![Screenshot 2021-10-30 at 7 41 50 AM](https://user-images.githubusercontent.com/51323070/139517023-031657ce-a07c-49ae-b0d1-3b76bb21ca04.png)

As you can see there is ffmpeg on my /usr/local/bin/
![image](https://user-images.githubusercontent.com/51323070/139517064-1cd62807-7af7-482e-8b8a-108864578235.png)

**Comment by 2V3EvG4LMJFdRe** [comment]
Yeah, same for me on macOS High Sierra.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
