### ISSUE TITLE
[BUG] : App crashes when launched

### ISSUE THREAD

**Issue by ElongatedVeggie** [Shabinder/SpotiFlyer#701]
**Describe the bug:**
App crashes on Android 6 when launched. Both with GitHub and F-Droid releases

**Expected behavior**
The app should launch without crashing

**StackTrace:**
```
FATAL EXCEPTION: main
Process: com.shabinder.spotiflyer, PID: 10575
android.content.res.Resources$NotFoundException: File res/O_.png from xml type xml resource ID #0x7f0800b0
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2929)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2884)
	at android.content.res.Resources.getXml(Resources.java:1264)
	at com.shabinder.common.uikit.AndroidImagesKt.imageVectorResource(AndroidImages.kt:14)
	at com.shabinder.common.uikit.ExpectImagesKt.getCachedPainter(ExpectImages.kt:1)
	at com.shabinder.common.uikit.AndroidImagesKt.SpotiFlyerLogo(AndroidImages.kt:1)
	at com.shabinder.common.uikit.screens.splash.SplashKt.Splash(Splash.kt:52)
	at com.shabinder.common.uikit.screens.SpotiFlyerRootUiKt.SpotiFlyerRootContent(SpotiFlyerRootUi.kt:86)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1$1$1$1.invoke(MainActivity.kt:57)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1$1$1$1.invoke(MainActivity.kt:1)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at m.a.a.a.s$c.invoke(WindowInsets.kt:2)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at m.a.a.a.s.a(WindowInsets.kt:14)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1$1$1.invoke(MainActivity.kt:4)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1$1$1.invoke(MainActivity.kt:1)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b$a2.invoke(Surface.kt:53)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at a.c.b.M(Unknown Source)
	at a.c.b.N(Unknown Source)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1$1.invoke(MainActivity.kt:4)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1$1.invoke(MainActivity.kt:1)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.D(Unknown Source)
	at a.a.d.o0.invoke(MaterialTheme.kt:2)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at a.a.d.q2.a(Text.kt:6)
	at a.a.d.p0$a.invoke(MaterialTheme.kt:6)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at a.a.d.p0.a(MaterialTheme.kt:159)
	at com.shabinder.common.uikit.configurations.ThemeKt.SpotiFlyerTheme(Theme.kt:6)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1.invoke(MainActivity.kt:4)
	at com.shabinder.spotiflyer.MainActivity$onCreate$1.invoke(MainActivity.kt:1)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.a.a.b.i0.a(ComposeView.android.kt:2)
	at a.a.a.b.c$a.invoke(ComposeView.android.kt:2)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at a.a.a.b.j0.a(CompositionLocals.kt:17)
	at a.a.a.b.s$i.invoke(AndroidCompositionLocals.android.kt:7)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at a.a.a.b.s.a(AndroidCompositionLocals.android.kt:89)
	at a.a.a.b.f2.invoke(Wrapper.android.kt:4)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.c.b.o(Unknown Source)
	at a.a.a.b.g2.invoke(Wrapper.android.kt:23)
	at a.a.b.g2.b.invoke(ComposableLambda.jvm.kt:6)
	at a.a.b.a$g.invoke(Composer.kt:7)
	at a.a.b.w1.d(SnapshotState.kt:8)
	at a.a.b.a.V(Composer.kt:22)
	at a.a.b.q.c(Composition.kt:9)
	at a.a.b.b1.a(Recomposer.kt:6)
	at a.a.b.q.b(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$a.invoke(Wrapper.android.kt:16)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.b(Wrapper.android.kt:1)
	at androidx.compose.ui.platform.WrappedComposition.e(Wrapper.android.kt:5)
	at a.n.n$a.a(LifecycleRegistry.java:3)
	at a.n.n.a(LifecycleRegistry.java:14)
	at androidx.compose.ui.platform.WrappedComposition$a.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:14542)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2845)
	at a
```

**Device Info (please complete the following information):**
 - Device:  LG G4
 - OS:   Android 6
 - Version:  V3.5.0 F-Droid and GitHub Release

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
