### ISSUE TITLE
[BUG] : <FFmpeg not found at path>

### ISSUE THREAD

**Issue by SRG-UK** [Shabinder/SpotiFlyer#704]
No FFmpeg found at path. (this is when i start the app up), and this when it fails to download a song:  

com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:172)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:114)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more

on 3 separate songs

I was trying to download a single song from youtube

- Device:   PC
- OS:   Windows 10
- Version:   3.5.0
- Country: United Kingdom

**Comment by jazxii** [comment]
did anyone found the solution to this?

**Comment by pbanj** [comment]
> What one do i get off the website there is many different ones


The one for your operating system ![image](https://media.discordapp.net/attachments/399670410565910529/904685642183741440/Screenshot_20211101-065625.png)

**Comment by SRG-UK** [comment]
where do i put the files from the zip?


> > What one do i get off the website there is many different ones
> 
> The one for your operating system ![image](https://camo.githubusercontent.com/455d39ba053a5c5d42c31a47794f2b4a0c9db0eb8c6a00c790403537d8325017/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3339393637303431303536353931303532392f3930343638353634323138333734313434302f53637265656e73686f745f32303231313130312d3036353632352e706e67)

**Comment by SRG-UK** [comment]
@Shabinder could you help me please?

**Comment by Shabinder** [comment]
@SRG-UK follow this guide : https://www.thewindowsclub.com/how-to-install-ffmpeg-on-windows-10

**Comment by SRG-UK** [comment]
> @SRG-UK follow this guide : https://www.thewindowsclub.com/how-to-install-ffmpeg-on-windows-10

thank you!

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
