### ISSUE TITLE
android 9

### ISSUE THREAD

**Issue by Flow100** [Shabinder/SpotiFlyer#724]
DownloadLinkFetchFailed(errorTrace=Find Link for Digital Distance 

Fetching From Saavn Failed:DownloadLinkFetchFailed(errorTrace=No SAAVN Match Found for Digital Distance)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$DefaultImpls.findBestSongDownloadURL(JioSaavnRequests.kt:19)
	at com.shabinder.common.providers.saavn.requests.JioSaavnRequests$findBestSongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Yt1sMp3 Failed for nVuTIAW6hZo:io.ktor.client.features.ServerResponseException: Server error(https://yt1s.com/api/ajaxSearch/index: 503 Service Temporarily Unavailable. Text: "<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="35">
  <script type="text/javascript">
    //<![CDATA[
    (function(){
      
      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "79923",
        cRay: "6aab2be56ff668ef",
        cHash: "4a6de381a6ebf13",
        cPMDTk: "",
        cFPWv: "b",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly95dDFzLmNvbS9hcGkvYWpheFNlYXJjaC9pbmRleA==",
          ra: "S3RvciBjbGllbnQ=",
          rm: "UE9TVA==",
          d: "6XGqhPJC07er/8BGrsHw/SPCGSEjGMf54AwPCiOlGhMykdly/1IkH/RgCUUJzkZwvMuEzKecJ/++UKrHCcsXfNklFx2N8s964gy268nn4GwKzW6NDXkFhCcy3MlHtdjG6R88uZ6B3pRRli5bI69fB9QPgrSNjNaH7uncg2wB79KJm4WiNjC6bFUa/rU2WbxP3G5XM2QruRlepdzWYlG0bSjDKNxsdvkq18gKp8jDd3hYMZbRXEBCAegyblRlov76tbBxLSG+YR4vPrPztFjlEQhlfTx3e+yon7Ab2pfPbsBs9tzA7TXLK0Ih7PpVwWuA1DnHNmLKh+3h8olG8wPyrNKzKYILYTUyPgWY5H/QbnZFbGxoRQvQAxdXFP60XZdlpPgqFpRQgvTfp/XWnpdVq4R1ahxyDOZSHCerS1Imo4A/sLBPfjE9jamQZVaFos62HVHaR+YnBv3Y75jiXR8OCUnSssPMktb8PBsPAznHJ6aP+qzyGELJGUd1mgWdwsJimWkEwh6eZsMgksFx9Va4piF3l9N0ixGHRjiNmw0NJuEMNY3Y2IJxRaT496++y+25YkRtbxaUZA/fe3d3v8OVgA==",
          t: "MTYzNjMzNjQ0Ni4zMDQwMDA=",
          m: "jlXjK7gX5+00wKtwThCyiS/E+yXT21YmtaFZrN79Qp8=",
          i1: "ZYPYT6hZby/GFaMEV68Elw==",
          i2: "RKuYibNhlzfrERat4YbINQ==",
          zh: "slbOGnEscRNxFiOnTsX0AKh1TuDl2qbz+DoFMtxCWD8=",
          uh: "oz7OrxkrnxacOh3btzIq4iwAY0NK/hCkZ0LN2B2nTlI=",
          hh: "LBSS74KkcrNPPaDUVSmWQv8ZxJLhGAngcURUX8gX1AQ=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};
      
    })();
    //]]>
  </script>
  

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">
    
    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yt1s.com.</h1>
    
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>
   
  <form class="challenge-form" id="challenge-form" action="/api/ajaxSearch/index?__cf_chl_jschl_tk__=DDIigeSMEIeuxjvXncNBp0i.dvvK_nKcAbryfdLZsBE-1636336446-0-gaNycGzNBn0" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="0hkiSv4RP_VOGVtUDvWEJEtQgW_Y4i23P8Hk.lWNs6Q-1636336446-0-AVHgk4kgsizztaWNXE2FBL3FRSMEgPm0FfHtFC2v8Xl51pKdbDSwnlqgvOQygXAV5vB2yoDlBJ0J3IaUDzRfwm6szK8fjmbNEYTevkTA-uTeQ4mEmG7F5LO6XufEkfan9TP7L2leipzhtl1V3FQRi8MYMo2HroqVr7Dfz-WNrhEmOfYb5Fq_WjUbFQW94-q_hIjm9Jqb4wjD7xHR-6Wu8miF1kSXFY8_c9qzaT8GWJ5Cs_QKJCrRczud0MadV2-lQvFvclKYJhBd8ux9x73i_Fx34IHskoWC_xMZp_lyWv3r1k6Cl7c8bt9PxR2z5Yg7gSPi7Fuh73iXrKgF91KSRAgnwYDncI501iJLg07DuIqUq7mSizMGx59oeMcHHOZiB_Vu6FsKzMMrseshraRQG_iOs3UPDpOrJ2VLiyjNLYxuyccnJN6Jj9DONJDkwu3DwV0ItsROxhgzC-b2G1qYiuPeMtlj56e2UaKWhppqwYGGZ1PQiFivyiYVX12O6wJksA3t0L1Z1lEZmorVoK6e8rcgNs6OBJLQuFkPCvEw3JMczIADSSsZb8A2R0uF2dIktg" />
    <input type="hidden" name="r" value="1tCgMsAwLLSH5.6m0sdOWrH5QInI3fKOPKAGKPM3fno-1636336446-0-AbT+iZd4RkP5F9TOB34Ewc+wlr91bE7CNtD/5fx6wRYjPQ4JwIO3l3bgsWN9FcHR94iv/XL2Jc69xX+yTDUZGNnZQilcxhrJ6YEu4qh8/hvQhs5450SyRlhqk8GZK6AGqaY28G9HQtW727Yju0gMEmqOFzQaefhgnZ4w+MWEPhs9/TjhaNltcy1jWYbyziCJsjExKyRGpVXdhP582fk5ya7w5RqRdDNFilSjuSkrWIH9gMKcgiGOevyNJX+rr1eNACce0YofESQrn42CX5davU4v21QV3vPTmig3wxvnbzhD7KyD5RffJ9qOH8Y+HZKQisOTBFS1XFh0x1zKPEg8Z8VzquvBzEMCaLo3Buni8NpKef0a07uX8WaMBHsksCDceGeBP7yXjoiJEF1qD19Fx8mDcvzuyKkHMNow9/oJ5NY/CugyPmpYIfvsR4LVMB+AXQ9jobeYFQBtOtmD4sWCnwARUNZjH995I1u0Fkak05kQ/HGcWIFXEC7qXIivCjYRqdeFglW5TPAZhsrwrve6gRTL6MXsvvNsIt1x2Tr7rJ9iGjMJe2FF168J3SkQVAPt8Pw3sQ/ipsIqza8SIBCxRGCcl8kHMv7VbAaDl2k59a6lJ9cVYCXae3GDgGVog25TNeCS24fEkTJ2WU6NUBNHxK62cVbZVXsPJIm8JRY82VSNu94UjqC8SrA0EUIRdfBNraX6Q+hlWiXW+kQCp6q+a0ZcfE+uCvkcrQyun/U9Qwn82P4MPk/AwJA0ASy5rBINgyLyedBZlOvTXeC32grmtFWQX5a89bGRho96iKilF1Whv7oZ9/9jeiaEkLGT7rVbK/EMJRc2TMg60aL2bHsDC7W/L/oNKi1Qil4hkL8XT+nC336/dQHH8qzhoByo7Md/8WHXwoPqpYf9TP4NgN3w+tPZausxTP1E4hBv6ya/dJoLB0gGTIGK8g1HMiTaMu3IIl/Wysom5wHhl2vqklII0PilPFSbTlflgRaAtegQhOqe0jyxti5ghaglWfmGH7Prqp4GG/avcluqBmZspTxhEwuv6XW3UhSW0clODrwzlHr+XaWdzsFjn8qQi1fDAXeUSbhCMfLvHxSNB9ngbGZdBlFPm00xjZTNVbNnJMyAxcZQsr+ApDGvQcBtO+sFdgtO7Bkt9q6r5NU/+sb+HmGmVIHRUI9fP1E8sEgsbxLsA0t0aXjdv0q7cj7swC5tqD+z54vi3Wb4YQbRMGvxusyXUdYlRLFExGNBsDZGcX+YIkfHf61dXW+omI45fl9TyCuCwh3UOSFJcGhDGpdGA4Mb3Dy+TfnfyqKGuNQsYgbL0JBS3Gc41PDPED5HyEnl8tGQNQkivsg6egaMUJ5M8F/h3XfQtPqvARGgFkT+cCrVWwb94R7aplmPlg/DVRmrOr9sUNwxY7kIPf9MLJ5XyFrws69sDt1NQ/xjoG3wd/CKJBhhtY6nOMp56X9AAyZI8UOQ1IvPopuUN/q5kpTUY6sjd9ew/BTXjWUz7mCUmjy54iXLJpCjUZiqALzlPJHgIvZJKBbt7TbY/zFcdqYP3+jZ06NBXc1csuu977oWgslAcA+sFUE2cxAdRgySMJandxpzkg=="/>
    <input type="hidden" value="eee0d9a34b75c8051d2d250125cc8b42" id="jschl-vc" name="jschl_vc"/>
    
    <input type="hidden" name="pass" value="1636336447.304-c+XuHpyp3w"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
     
    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=6aab2be56ff668ef");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=6aab2be56ff668ef";
          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>
  

  
  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=6aab2be56ff668ef')"> </div>
</div>

          
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>6aab2be56ff668ef</code></span>
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>
"
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:15)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Extracting Manually...

YT Manual Extraction Failed!io.ktor.client.features.ClientRequestException: Client request(https://r1---sn-4g5edn6y.googlevideo.com/videoplayback?expire=1636358046&ei=PoOIYYTnK9Oj1gL8_oiYDA&ip=2a02%3A810b%3Ac7bf%3Ae290%3Af553%3Ae90a%3A6820%3Ad195&id=o-AD_-5puuGQpibb_OjEqTxxVHKaUtGAg8LexT2KCPG_lI&itag=140&source=youtube&requiressl=yes&mh=73&mm=31%2C26&mn=sn-4g5edn6y%2Csn-f5f7kn7e&ms=au%2Conr&mv=m&mvi=1&pl=33&gcr=de&initcwndbps=1772500&vprv=1&mime=audio%2Fmp4&ns=BWsHkmRhThzWephkDb0k5WAG&gir=yes&clen=4871212&dur=300.869&lmt=1579689477192021&mt=1636336131&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=q8rnjsxXAfhiS0Vw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgHS4bo7_614d00BiXIiGKsDa3cLuup2V8x_-zSgqWVUgCIHFJs8INoN9bEpSIb6agyFATw8B54lbIZ5amLDQJoptd&sig=AOq0QJ8wRQIhAKAyibI4MZvn43BcDvo1O968JFktywotScEyTUUOldCkAiAFoYWyxHHNoE2cRG-zvKr-TacIps9Umg_QyVMKKmBARA%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:17)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:6)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:1)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:4)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:10)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

Fetching From YT Failed:io.ktor.client.features.ClientRequestException: Client request(https://r1---sn-4g5edn6y.googlevideo.com/videoplayback?expire=1636358046&ei=PoOIYYTnK9Oj1gL8_oiYDA&ip=2a02%3A810b%3Ac7bf%3Ae290%3Af553%3Ae90a%3A6820%3Ad195&id=o-AD_-5puuGQpibb_OjEqTxxVHKaUtGAg8LexT2KCPG_lI&itag=140&source=youtube&requiressl=yes&mh=73&mm=31%2C26&mn=sn-4g5edn6y%2Csn-f5f7kn7e&ms=au%2Conr&mv=m&mvi=1&pl=33&gcr=de&initcwndbps=1772500&vprv=1&mime=audio%2Fmp4&ns=BWsHkmRhThzWephkDb0k5WAG&gir=yes&clen=4871212&dur=300.869&lmt=1579689477192021&mt=1636336131&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=q8rnjsxXAfhiS0Vw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgHS4bo7_614d00BiXIiGKsDa3cLuup2V8x_-zSgqWVUgCIHFJs8INoN9bEpSIb6agyFATw8B54lbIZ5amLDQJoptd&sig=AOq0QJ8wRQIhAKAyibI4MZvn43BcDvo1O968JFktywotScEyTUUOldCkAiAFoYWyxHHNoE2cRG-zvKr-TacIps9Umg_QyVMKKmBARA%3D%3D) invalid: 403 Forbidden. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:17)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:8)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(Unknown Source:4)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:6)
	at io.ktor.client.features.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:1)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:4)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:11)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(Unknown Source:8)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:10)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

)
	at com.shabinder.common.providers.FetchPlatformQueryResult.findBestDownloadLink(FetchPlatformQueryResult.kt:84)
	at com.shabinder.common.providers.FetchPlatformQueryResult$findBestDownloadLink$1.invokeSuspend(Unknown Source:12)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
