### ISSUE TITLE
[BUG] Issues downloading 'Lush Life' by Orion, specifically. 

### ISSUE THREAD

**Issue by SnowyBirdot** [Shabinder/SpotiFlyer#791]
Fantastic app by the way, this is the only major problem I've had so far! 

java.lang.Exception: Client request(https://redirector.googlevideo.com/videoplayback?expire=1639603983&ei=rwq6YanbFJWj1wayhqfoCw&ip=196.242.18.239&id=o-AIMeFqwxiPe1NnqHE_qZ7keznJTvrGx0-0AJXIEYp7tc&itag=140&source=youtube&requiressl=yes&mh=Ap&mm=31%2C26&mn=sn-25glen7l%2Csn-5hne6nzs&ms=au%2Conr&mv=u&mvi=4&pl=24&gcr=us&vprv=1&mime=audio%2Fmp4&ns=hlem0FSvsjomcQVYVnDgowIG&gir=yes&clen=2947232&dur=181.973&lmt=1612809254196849&mt=1639581305&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=0C1oUYd17gUTGA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgf41jS8kPADn3KqkMPsKQmB37xAu8jC45QItubSgU3loCIQDdrNBqm7umjHg3wvNorL_LVsyepD2OntS0C8xW78ymvA%3D%3D&sig=%3DQR5afcb9bbS3CYwwme9El4_WMUW8FGzIBAWUeykSs9ZCQIC4Bl60YNI4aGmfCIYAMd4zx7eNxGgN_7GaAduHLqWEjbgIQRw8JQ0qOAOx&title=Lush+Life) invalid: 403 Forbidden. Text: "<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/videoplayback?expire=1639603983&amp;ei=rwq6YanbFJWj1wayhqfoCw&amp;ip=196.242.18.239&amp;id=o-AIMeFqwxiPe1NnqHE_qZ7keznJTvrGx0-0AJXIEYp7tc&amp;itag=140&amp;source=youtube&amp;requiressl=yes&amp;mh=Ap&amp;mm=31%2C26&amp;mn=sn-25glen7l%2Csn-5hne6nzs&amp;ms=au%2Conr&amp;mv=u&amp;mvi=4&amp;pl=24&amp;gcr=us&amp;vprv=1&amp;mime=audio%2Fmp4&amp;ns=hlem0FSvsjomcQVYVnDgowIG&amp;gir=yes&amp;clen=2947232&amp;dur=181.973&amp;lmt=1612809254196849&amp;mt=1639581305&amp;fvip=4&amp;keepalive=yes&amp;fexp=24001373%2C24007246&amp;c=WEB&amp;txp=2311222&amp;n=0C1oUYd17gUTGA&amp;sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&amp;lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&amp;lsig=AG3C_xAwRQIgf41jS8kPADn3KqkMPsKQmB37xAu8jC45QItubSgU3loCIQDdrNBqm7umjHg3wvNorL_LVsyepD2OntS0C8xW78ymvA%3D%3D&amp;sig=%3DQR5afcb9bbS3CYwwme9El4_WMUW8FGzIBAWUeykSs9ZCQIC4Bl60YNI4aGmfCIYAMd4zx7eNxGgN_7GaAduHLqWEjbgIQRw8JQ0qOAOx&amp;title=Lush+Life</code> from this server.  <ins>That’s all we know.</ins>
"
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:12)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:2)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
