### ISSUE TITLE
[BUG] : <cant_download_long_songs>

### ISSUE THREAD

**Issue by GRG-The-Second** [Shabinder/SpotiFlyer#821]
**Describe the bug:**

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```
java.lang.Exception: Request timeout has expired [url=https://rr5---sn-q4flrnlz.googlevideo.com/videoplayback?expire=1640581483&ei=C_XIYZnTDYjPuAL_pam4Dg&ip=8.20.123.189&id=o-AAi5YiURgR_Z1wMvTFsIfWvqt5r5VZRcq25AEAH8SWAy&itag=140&source=youtube&requiressl=yes&mh=gq&mm=31%2C29&mn=sn-q4flrnlz%2Csn-q4fl6ns6&ms=au%2Crdu&mv=m&mvi=5&pl=24&gcr=us&initcwndbps=1585000&vprv=1&mime=audio%2Fmp4&ns=7x5b9i2Z0JE0iTqwwrTgti8G&gir=yes&clen=19528153&dur=1206.466&lmt=1584996162143307&mt=1640559676&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=2311222&n=gcegMzdqueW-LsVd&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOh1kG60-NsNhgqEVsbUwe5LyJqSkeLibbh9d_mXIDOfAiEAxgGiIE_x5rcK8KayBpOdgTlZ2cM4GdaGrgxU7LXKdbg%3D&sig=AOq0QJ8wRQIgChnRFe9NCcl2w4G9ZU6CcbfpY9p4cpLzB30UK2_REM4CIQDHuUIri6yWMCzvnKW0ofuPj9i170JBSEu-h5WPSlWhJA%3D%3D, request_timeout=360000 ms]
	at com.shabinder.spotiflyer.service.ForegroundService$enqueueDownload$$inlined$collect$1.emit(Collect.kt:9)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invokeSuspend(FileManager.kt:5)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:11)
	at com.shabinder.common.core_components.file_manager.FileManagerKt$downloadFile$4.invoke(Unknown Source:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:6)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1$1.invokeSuspend(Unknown Source:12)
	at u.v.j.a.a.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Device Info (please complete the following information):**
 - Device:   Samsung Galaxy S8 Active
 - OS:   Android 9
 - Version:   [e.g. 3.2.1]
 - Country: United States Of America 

**Additional context:**

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
