### ISSUE TITLE
[BUG] : Spotiflyer doesn't download all songs from album

### ISSUE THREAD

**Issue by Jokou-tech** [Shabinder/SpotiFlyer#836]
**Describe the bug:**
I was trying to download the album "The Wall (Remastered)" and "Mother - 2011 Remastered Version" didn't download.

**Media Links Used:** 
https://open.spotify.com/album/6WaIQHxEHtZL0RZ62AuY0g?si=yTsyGf93TpasoDIxAUo0IA

**Expected behavior**
It was supposed to download "Mother - 2011 Remastered Version" but it didnt

**Screenshots:**

**StackTrace:**
```
"UnknownReason(exception=null, message=Unknown Error)
at com.shabinder.common.providers.DesktopActualKt$downloadTracks$2$1$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:144)"
```

**Device Info (please complete the following information):**
 - Device:  Linux vm
 - OS:   Kali linux
 - Version:  2021.4
 - Country: Greece

**Additional context:**
It says "UnknownReason(exception=null, message=Unknown Error)
	at com.shabinder.common.providers.DesktopActualKt$downloadTracks$2$1$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:144)"

**Comment by Jokou-tech** [comment]
i fixed it.
