### ISSUE TITLE
Songs not downloading from Spotify

### ISSUE THREAD

**Issue by itscerealkilla** [Shabinder/SpotiFlyer#84]
When I press on download the songs don't download : it never completes. When I select download all it works but some songs download at .8 speed.

**Comment by Shabinder** [comment]
What do you mean by .8 speed?
and by it never completes, do you mean it is stuck in midway or never starts?
maybe UI is not updating did you tried checking /Downloads/Spotiflyer/... location for your Download?

**Comment by itscerealkilla** [comment]
Hey,Maybe it's just this specific song, but when it downloads, it plays at 0.8 speed in a music player so if I want to hear the normal speed of the song I have to set the play speed to 1.2x speed.I have checked and it doesn't download. The circle keeps "loading" and it never finishes. The notification also doesn't count it as interrupted. I do not know exactly where it is stuck, but it doesn't seem to start.
-------- Original message --------From: Shabinder Singh ***@***.***> Date: 13/04/2021  18:19  (GMT+01:00) To: Shabinder/SpotiFlyer ***@***.***> Cc: itscerealkilla ***@***.***>, Author ***@***.***> Subject: Re: [Shabinder/SpotiFlyer] Songs not downloading from Spotify (#84) 
What do you mean by .8 speed?
and by it never completes, do you mean it is stuck in midway or never starts?
maybe UI is not updating did you tried checking /Downloads/Spotiflyer/... location for your Download?

**Comment by Shabinder** [comment]
> Hey,Maybe it's just this specific song, but when it downloads, it plays at 0.8 speed in a music player so if I want to hear the normal speed of the song I have to set the play speed to 1.2x speed.I have checked and it doesn't download. The circle keeps "loading" and it never finishes. The notification also doesn't count it as interrupted. I do not know exactly where it is stuck, but it doesn't seem to start. 


Hey, Seems like a very weird issue, like playback speed less, etc.
Can you share the Playlist URL and tell which song is giving such an issue?

**Comment by itscerealkilla** [comment]
Hey,This is the song that's causing problems : https://open.spotify.com/track/4bYLspjdlNAV19Ej8bnwzo?si=yFiZmhcAQjC7Q3EKbfu6MAThe not downloading problem is with every song that I have tried. They only download when I press "Download All". Single downloads don't work for me.Also thank you for replying!
-------- Original message --------From: Shabinder Singh ***@***.***> Date: 13/04/2021  18:40  (GMT+01:00) To: Shabinder/SpotiFlyer ***@***.***> Cc: itscerealkilla ***@***.***>, Author ***@***.***> Subject: Re: [Shabinder/SpotiFlyer] Songs not downloading from Spotify (#84) 

Hey,Maybe it's just this specific song, but when it downloads, it plays at 0.8 speed in a music player so if I want to hear the normal speed of the song I have to set the play speed to 1.2x speed.I have checked and it doesn't download. The circle keeps "loading" and it never finishes. The notification also doesn't count it as interrupted. I do not know exactly where it is stuck, but it doesn't seem to start.

Hey, Seems like a very weird issue, like playback speed less, etc.
Can you share the Playlist URL and tell which song is giving such an issue?

**Comment by Shabinder** [comment]
@itscerealkilla Thanks for reporting the issue, I will check it out as soon as possible.

**Comment by itscerealkilla** [comment]
You're welcome! Hope you managw to fix it. And does the problem where the song is slowed happen to you as well?Again, thank you for responding. Amazing app otherwise!
-------- Original message --------From: Shabinder Singh ***@***.***> Date: 13/04/2021  19:22  (GMT+01:00) To: Shabinder/SpotiFlyer ***@***.***> Cc: itscerealkilla ***@***.***>, Mention ***@***.***> Subject: Re: [Shabinder/SpotiFlyer] Songs not downloading from Spotify (#84) 
@itscerealkilla Thanks for reporting the issue, I will check it out as soon as possible.

**Comment by Mahamad-Walid** [comment]
I have an issue whenever I try to download a song I get this error. 


DownloadLinkFetchFailed(trackName=MA YORAM, jioSaavnError=java.util.NoSuchElementException: Collection is empty., ytMusicError=NoMatchFound(trackName=MA YORAM, message=MA YORAM : NO Match Found!), message=No Downloadable link found: MA YORAM, 
 YtMusic Error's StackTrace: NoMatchFound(trackName=MA YORAM, message=MA YORAM : NO Match Found!)
	at com.shabinder.common.di.providers.YoutubeMusic.getYTIDBestMatch(YoutubeMusic.kt:13)
	at com.shabinder.common.di.providers.YoutubeMusic.access$getYTIDBestMatch(YoutubeMusic.kt:1)
	at com.shabinder.common.di.providers.YoutubeMusic$getYTIDBestMatch$1.invokeSuspend(Unknown Source:12)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
 
  
 JioSaavn Error's StackTrace: java.util.NoSuchElementException: Collection is empty.
	at i.r.m.p(_ArraysJvm.kt:5)
	at com.shabinder.common.di.providers.requests.saavn.JioSaavnRequests$DefaultImpls.findMp3SongDownloadURL(JioSaavnRequests.kt:8)
	at com.shabinder.common.di.providers.requests.saavn.JioSaavnRequests$findMp3SongDownloadURL$1.invokeSuspend(Unknown Source:10)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
 
 )
	at com.shabinder.common.di.FetchPlatformQueryResult.findMp3Link(FetchPlatformQueryResult.kt:18)
	at com.shabinder.common.di.FetchPlatformQueryResult.access$findMp3Link(FetchPlatformQueryResult.kt:1)
	at com.shabinder.common.di.FetchPlatformQueryResult$findMp3Link$1.invokeSuspend(Unknown Source:12)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:10)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:3)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:1)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:3)
	at i.t.k.a.a.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
