### ISSUE TITLE
[BUG] : Warning! FFmpeg not found at path

### ISSUE THREAD

**Issue by saurabhkundu1** [Shabinder/SpotiFlyer#891]
**Describe the bug:**
 I am seeing this issue on opening Spotiflyer. “Warning! FFmpeg not found at path” Just this and when I try to download anything there comes an error reporting where it says to copy this and paste while reporting error.

**Media Links Used:** 

**Expected behavior**

**Screenshots:**

**StackTrace:**
```
Paste Stacktrace here if available
```com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invokeSuspend(DesktopMediaConverter.kt:34)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.media_converter.DesktopMediaConverter$convertAudioFile$2.invoke(DesktopMediaConverter.kt)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$Operation.execute(ParallelExecutor.kt:172)
	at com.shabinder.common.core_components.parallel_executor.ParallelExecutor$launchProcessor$1.invokeSuspend(ParallelExecutor.kt:114)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:304)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 17 more

**Device Info (please complete the following information):**
 - Device:   [e.g. iPhone6, Samsung J2, PocoF1] PC
 - OS:   [e.g. iOS, Android 10, WinOS, MacOS] Zorin OS
 - Version:   [e.g. 3.2.1] 16
 - Country: [eg: India, will help in detecting if service is accessible to u] India

**Additional context:**
<!--- Add any other context about the problem here. --->

**Comment by wunderkind2k1** [comment]
Hi saurabhkundu1,
do you still have that issue?

I had the same problems on OSX (don't know your os) - It didn't work for my by simply clicking on the .jar (though ffmpeg was installed correctly).
After I started the .jar file from Spotiflyer in a bash with `java -jar <your jar file>` it found ffmpeg and worked perfectly.

Hope this might help.

**Comment by bverkron** [comment]
> I had the same problems on OSX (don't know your os) - It didn't work for my by simply clicking on the .jar (though ffmpeg was installed correctly). After I started the .jar file from Spotiflyer in a bash with `java -jar <your jar file>` it found ffmpeg and worked perfectly.

Worked for me on macOS as well, though not sure what ffmpeg is even used for when downloading from Spotify. I was able to download from Spotify even with the ffmpeg error.

**Comment by Shabinder** [comment]
Spotiflyer is discontinued, please install [Soundbound](https://soundbound.shabinder.in/install) with our new **plugins**. 
 - For reporting Issues or Requesting Features in Soundbound, you can visit its [helpdesk](https://soundbound.shabinder.in/helpdesk).
 - Also you can join our [Telegram Community](https://soundbound.shabinder.in/telegram) to stay up to date.
