### ISSUE TITLE
Error running on Linux

### ISSUE THREAD

**Issue by markus681** [Shabinder/SpotiFlyer#91]
Hello, ich have problems Installing SpotiFlyer on Linux.
Using Xubuntu :
`Linux laptop 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Error message : 
```
markus@laptop ~/SpotiFlyer (main)> ./gradlew :desktop:run
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:buildSrc:compileKotlin
The `kotlin-dsl` plugin applied to project ':buildSrc:buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.8/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

> Task :buildSrc:buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


> Configure project :
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.32`.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':common:dependency-injection:compileKotlinDesktop'.
> Could not resolve all task dependencies for configuration ':common:dependency-injection:desktopCompileClasspath'.
   > Could not find com.shabinder.downloader:youtube-api-dl:0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://jcenter.bintray.com/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://repo.maven.apache.org/maven2/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - file:/home/markus/.m2/repository/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://jitpack.io/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://dl.bintray.com/ekito/koin/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://kotlin.bintray.com/kotlinx/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://dl.bintray.com/icerockdev/moko/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://dl.bintray.com/kotlin/kotlin-js-wrappers/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom
     Required by:
         project :common:dependency-injection

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 55s
```

seems to me that the source isnt available, if i call the first link `https://dl.google.com/dl/android/maven2/com/shabinder/downloader/youtube-api-dl/0.1/youtube-api-dl-0.1.pom`
in my Browser i get an 403 Error.
I'am using PiHole as my DNS, but i put my Laptop to direct Internet accsess.

so i have no clue about Programming

if neede for more Information just ask please

Please Help

THX Markus

**Comment by Shabinder** [comment]
Hey, the thing is **youtube-api-dl-0.1** is not yet published to use it you need to build and publish it to your mavenLocal .
Which I won't recommend you to do.

Instead, delete the source code you downloaded and use repo from this commit:
**https://github.com/Shabinder/SpotiFlyer/tree/c9696fa4aa7f99f614bc1d65ae0a8dd5f223a4af**

This should build successfully, but be advised that Desktop app is still in very early stages, so expect some issues here and there.

**Comment by markus681** [comment]
Thanks for the fast feedback, i will try it.
It dosent matter if its buggy, i will try the app, tried so far much programms to download, so iam still searching :-)
:+1:

**Comment by Shabinder** [comment]
Did you get it to work?

**Comment by markus681** [comment]
Unfortunately not yet, but it is fixable, it complains about Java backward compatibility, i have Version 55 an it needs at least 58.
I dont have the log anymore, but i will retry it if i fixed the Java Error...

**Comment by markus681** [comment]
I let it run again for the Error Message

```
markus@laptop ~/SpotiFlyer> ./gradlew :desktop:run
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.32`.

> Task :desktop:run FAILED
Fehler: Beim Laden der Klasse MainKt ist ein LinkageError aufgetreten
        java.lang.UnsupportedClassVersionError: MainKt has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 56s
21 actionable tasks: 1 executed, 20 up-to-date

**Comment by markus681** [comment]
now i installed openjdk-14-jdk and openjdk-14-source and now it is running :-)

heres the output from console, maybe it helps

```markus@laptop ~/SpotiFlyer> ./gradlew :desktop:run
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :buildSrc:buildSrc:compileKotlin
The `kotlin-dsl` plugin applied to project ':buildSrc:buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.8/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

> Configure project :
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.32`.

> Task :common:main:compileKotlinDesktop
w: /home/markus/SpotiFlyer/common/main/src/commonMain/kotlin/com/shabinder/common/main/integration/SpotiFlyerMainImpl.kt: (47, 46): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'

> Task :common:list:compileKotlinDesktop
w: /home/markus/SpotiFlyer/common/list/src/commonMain/kotlin/com/shabinder/common/list/integration/SpotiFlyerListImpl.kt: (48, 46): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'

> Task :common:compose:compileKotlinDesktop
w: /home/markus/SpotiFlyer/common/compose/src/commonMain/kotlin/com/shabinder/common/uikit/SpotiFlyerListUi.kt: (76, 53): Parameter 'index' is never used, could be renamed to _

> Task :desktop:run
Info: (Kermit) /home/markus/SpotiFlyer/ already exists
Info: (Kermit) /home/markus/SpotiFlyer/.images/ created
Info: (Kermit) /home/markus/SpotiFlyer/Tracks/ created
Info: (Kermit) /home/markus/SpotiFlyer/Albums/ created
Info: (Kermit) /home/markus/SpotiFlyer/Playlists/ created
Info: (Kermit) /home/markus/SpotiFlyer/YT_Downloads/ created
Debug: (Kermit) Creating Spotify Provider
Debug: (Kermit) System Time:1619178881 , Token Expiry:null
Debug: (Kermit) Requesting New Token
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=********, token_type=Bearer, expiry=3600)
<============-> 97% EXECUTING [4m 46s]
> :desktop:run
> IDLE

**Comment by markus681** [comment]
so the programm is running but doesent download anything...

```markus@laptop ~/SpotiFlyer> ./gradlew :desktop:run

> Configure project :
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.20` that might work differently than in the requested version `1.4.32`.

> Task :desktop:run
Info: (Kermit) /home/markus/SpotiFlyer/ already exists
Info: (Kermit) /home/markus/SpotiFlyer/.images/ already exists
Info: (Kermit) /home/markus/SpotiFlyer/Tracks/ already exists
Info: (Kermit) /home/markus/SpotiFlyer/Albums/ already exists
Info: (Kermit) /home/markus/SpotiFlyer/Playlists/ already exists
Info: (Kermit) /home/markus/SpotiFlyer/YT_Downloads/ already exists
Debug: (Kermit) Creating Spotify Provider
Debug: (Kermit) System Time:1619179618 , Token Expiry:1619182483
Debug: (Kermit) Spotify Provider Created with TokenData(access_token=********, token_type=null, expiry=1619182483)
[MVIKotlin]: Main thread id is undefined, main thread assert is disabled
[DefaultDispatcher-worker-6] INFO io.ktor.client.HttpClient - REQUEST: https://music.youtube.com/youtubei/v1/search?alt=json&key=********
[DefaultDispatcher-worker-6] INFO io.ktor.client.HttpClient - METHOD: HttpMethod(value=POST)
[DefaultDispatcher-worker-6] INFO io.ktor.client.HttpClient - RESPONSE: 200 OK
[DefaultDispatcher-worker-6] INFO io.ktor.client.HttpClient - METHOD: HttpMethod(value=POST)
[DefaultDispatcher-worker-6] INFO io.ktor.client.HttpClient - FROM: https://music.youtube.com/youtubei/v1/search?alt=json&key=********
Debug: (YT Music) Match Found for 12 Days Of Christmas - true
Debug: (ListStore: flow Updated) 1
Debug: (ListStore: flow Updated) 1
java.io.FileNotFoundException: /home/markus/SpotiFlyer/Albums/We_Need_A_Little_Christmas/12_Days_Of_Christmas.mp3 (Datei oder Verzeichnis nicht gefunden)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
        at com.shabinder.common.di.Dir.saveFileWithMetadata(DesktopDir.kt:90)
        at com.shabinder.common.di.DesktopActualKt$downloadTracks$2$1$4.invoke(DesktopActual.kt:100)
        at com.shabinder.common.di.DesktopActualKt$downloadTracks$2$1$4.invoke(DesktopActual.kt:100)
        at com.shabinder.common.di.DesktopActualKt$downloadTrack$lambda-8$$inlined$collect$1.emit(Collect.kt:149)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at com.shabinder.common.di.DirKt$downloadFile$2.invokeSuspend(Dir.kt:63)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 17s
21 actionable tasks: 1 executed, 20 up-to-date

**Comment by Shabinder** [comment]
I am not super active on Desktop App Testing as I am focussing on Ios Build, It seems I messed up the desktop app while developing features for Android App ,

Fixing Desktop App to a working Condition wont take me long , but I dont have yet time to do that, however will do asap.

Till then maybe use Android App

**Comment by markus681** [comment]
Dont worry, iam still testing programms for Spoti, now i have 2 for Windows which aim to get it direct from Spoti...lets see how they work...i now the most uses youtube as source for music, but i would like to have at least 320K if i get it from Spoti, i also use deemix which support flac at 1411k if available, so i am still looking for a tool that can accsess Spoti directly and decrypt it, best on linux, iam only working with linux, windows only in vm...

So far Thanks for the Support
